######################################################################
# HISTORY
# $Log:	Makefile,v $
# Revision 1.2  90/02/25  17:30:36  bww
# 	Created for new and improved SSP format.
# 	[90/02/25  17:29:27  bww]
# 
######################################################################

IDIR			= /usr/etc/

PROGRAMS		= netmsgserver
OFILES			= nmserver.o cam_stuff.o crypt.o crypt_des.o \
			  crypt_multperm.o crypt_newdes.o crypt_xor.o \
			  datagram.o deltat.o deltat_handler.o \
			  deltat_send.o deltat_utils.o des.o \
			  dispatcher.o ipc.o ipc_block.o ipc_swap.o \
			  keyman.o km_procs.o km_utils.o lock_queue.o \
			  logstat.o ls_rec.o mem.o multperm.o netipc.o \
			  netname.o network.o nm_enable.o nm_extra.o \
			  nm_init.o nn_handler.o nn_procs.o pc_handler.o \
			  pc_startup.o po_message.o po_notify.o \
			  po_utils.o portcheck.o portops.o portrec.o \
			  portsearch.o ps_auth.o rwlock.o sbuf.o \
			  srr.o srr_handler.o srr_utils.o timer.o \
			  transport.o uid.o ${RPCMOD_${RPCMOD}_OFILES} \
			  netnameServer.o logstatServer.o
RPCMOD_ON_OFILES	= ipc_exception.o ipc_msg.o ipc_rpc.o tcp.o vmtp2.o
RPCMOD_OFF_OFILES	= ipc_in.o ipc_out.o vmtp1.o
MIG_DEFS		= netname.defs logstat.defs

RPCMOD			= ON
CFLAGS			= -I../conf
LINTFLAGS		= -u -lthreads -lmach
LIBS			= ../lib/libvmtp.a -lthreads -lmach -lcs

include ${MAKETOP}Makefile-common

logstat.o: logstat.h
