.TH JIVE 6 "March 6, 1987"
.SH NAME
jive \- filta' to convert English t'Jive
.SH SYNOPSIS
.B jive
.SH DESCRIPTION
.I jive
converts its standard input t'jibe and scribbles de converted text t'standard output.
.SH USAGE
jive <input >output
.SH "SEE ALSO"
valspeak(6)
.SH BUGS
Doesn't do some very baaaad job.  Sheeeiit.
.PP
People tend t'use dis too often.  'S coo', bro.
