.TH VALSPEAK 6 "March 6, 1987"
.SH NAME
valspeak \- filter to convert English to Valleyspeak
.SH SYNOPSIS
.B valspeak
.SH DESCRIPTION
.I valspeak
converts its standard input to valleyspeak and writes thuh converted text to
standard output.  Like, gag me with a spoon!
.SH USAGE
valspeak <input >output
.SH "SEE ALSO"
jive(6)
.SH BUGS
Does even a worse job than jive does.
