...\"	index formatting macros
...\"
...\"
...\"	Iy  --  called between letters of the alphabet
.de Iy
.if !\\$1 \{\
.	fl
.	sp 5v
.	ne .75i
.	in \\n(I#u						\" do indent
\s30\&\\$1\s0
.	sp 1
.	rm I! I@
'	br \}
..
...\"
...\"
...\"	Ix  --  called for an individual index item
.de Ix
'in \\n(I#u						\" do indent
.if !\\$1\\*(I! \{\
.br
.sp .5v                           	\" make sure we're at the start of a line
.ti 0							\" major is always at left margin
\&\\$1\c\"						\" and - output "Major"
.ds I! \\$1\"					\" save major name
.	rm I@
'	br \}
.ie \\$2\\*(I@ \{\
.	ie \\$4 , \\$3\c\"	\" same minor - just output page #
.	el , \fB\\$3\fP\c\"			\"     highlight version
'	br \}
.el \{\
.	br							\" make sure we're on a new line
.	fl
.	ie \\$4 \&\\$2, \&\\$3\c\"	and output "Minor, page#"
.	el \&\\$2, \fB\\$3\fP\c\"	\"     highlight version
.	ds I@ \\$2\"				\" save minor name
'	br \}
..
...\"
...\"	the string I! is used to hold the last major index name
.ds I!
...\"
...\"	the string I@ is used to hold the last minor index name
.ds I@
...\"
...\"	the register I# is used to hold the current indent
.nr I# .5i
...\"
...\"	to get around formatter and sorting limitations:
'fl
...\"
...\"
...\"
...\"	do everything in two column mode:
.2C
.rs
.nh			\" NO hyphenation
.na			\" no justification
.nr Hu 1
.HU "Index"
.tr ~-^\&\"	\" tilde becomes a dash, hat goes to null
.Ix "$HOME" "and configFile resource" "14~1" ""
.Ix "$HOME/$LANG/.mwmrc" "" "11~3" ""
.Ix "$HOME/.motifbind" "" "11~3" ""
.Ix "$HOME/.mwmrc" "" "11~3" ""
.Ix "$HOME/.Xdefaults" "" "11~3" ""
.Ix "$HOME/.Xdefaults" "" "13~2" ""
.Ix "$HOME/.Xdefaults~\fIhost\fP" "" "11~3" ""
.Ix "$HOME/.Xdefaults~host" "" "13~2" ""
.Ix "$HOME/Mwm" "" "11~3" ""
.Iy
.Ix ".mwmrc" "" "13~1" ""
.Ix ".mwmrc" "and configFile resource" "14~1" ""
.Ix ".Xdefaults" "" "13~1" ""
.Ix ".Xdefaults" "and resource description file" "14~1" ""
.Iy
.Ix "/usr/include/X11/bitmaps" "and bitmapDirectory" "14~2" ""
.Ix "/usr/lib/X11/$LANG/system.mwmrc" "" "11~3" ""
.Ix "/usr/lib/X11/app~defaults/Mwm" "" "11~3" ""
.Ix "/usr/lib/X11/app~defaults/Mwm" "" "13~2" ""
.Ix "/usr/lib/X11/app~defaults/Mwm" "and resource description file" "14~1" ""
.Ix "/usr/lib/X11/rgb.txt" "" "13~7" ""
.Ix "/usr/lib/X11/system.mwmrc" "" "11~3" ""
.Ix "/usr/lib/X11/system.mwmrc" "" "13~1" ""
.Ix "/usr/lib/X11/system.mwmrc" "and configFile resource" "14~1" ""
.Iy "3"
.Ix "3~dimensional appearance" "" "3~12" ""
.Iy
.Ix "@" "in menu specification" "14~3" ""
.Iy
.Ix "_MOTIF_WM_HINTS" "" "11~5" ""
.Ix "_MOTIF_WM_HINTS" "" "12~7" ""
.Ix "_MOTIF_WM_HINTS" "and clientDecoration resource" "13~13" ""
.Ix "_MOTIF_WM_HINTS" "and clientFunctions resource" "13~13" ""
.Ix "_MOTIF_WM_HINTS" "and transientDecoration resource" "13~13" ""
.Ix "_MOTIF_WM_HINTS" "flags field" "12~7" ""
.Ix "_MOTIF_WM_HINTS" "functions field" "12~8" ""
.Ix "_MOTIF_WM_INFO" "" "12~9" ""
.Ix "_MOTIF_WM_INFO" "flags field" "12~10" ""
.Ix "_MOTIF_WM_INFO" "wmWindow field" "12~10" ""
.Ix "_MOTIF_WM_MENU" "" "12~9" ""
.Ix "_MOTIF_WM_MENU" "adding to window menu" "12~9" ""
.Ix "_MOTIF_WM_MESSAGES" "" "12~5" ""
.Ix "_MOTIF_WM_MESSAGES" "" "12~9" ""
.Ix "_MOTIF_WM_MESSAGES" "and f.send_msg" "12~9" ""
.Ix "_MOTIF_WM_MESSAGES" "and WM_PROTOCOLS" "12~9" ""
.Iy "A"
.Ix "Accelerator" "" "6~8" ""
.Ix "Accelerator" "" "6~13" ""
.Ix "Accelerator" "" "6~21" ""
.Ix "Accelerator" "" "7~17" ""
.Ix "Accelerator" "" "E~1" ""
.Ix "accelerators" "" "11~13" ""
.Ix "accelerators" "" "14~4" ""
.Ix "Accepting focus" "" "9~1" ""
.Ix "active window" "" "11~3" ""
.Ix "activeBackground resource" "" "13~9" ""
.Ix "activeBackground" "resource" "16~2" ""
.Ix "activeBackgroundPixmap resource" "" "13~10" ""
.Ix "activeBackgroundPixmap resource" "" "16~3" ""
.Ix "activeBottomShadowColor resource" "" "13~9" ""
.Ix "activeBottomShadowColor" "resource" "16~2" ""
.Ix "activeBottomShadowPixmap resource" "" "13~10" ""
.Ix "activeBottomShadowPixmap resource" "" "16~3" ""
.Ix "activeForeground resource" "" "13~9" ""
.Ix "activeForeground" "resource" "16~2" ""
.Ix "activeTopShadowColor resource" "" "13~9" ""
.Ix "activeTopShadowColor" "resource" "16~2" ""
.Ix "activeTopShadowPixmap resource" "" "13~10" ""
.Ix "activeTopShadowPixmap resource" "" "16~3" ""
.Ix "Adding callbacks" "" "3~6" ""
.Ix "Adding callbacks" "" "3~7" ""
.Ix "Advanced program, font selection" "" "3~15" ""
.Ix "Advanced programming techniques" "" "3~13" ""
.Ix "any value" "" "18~23" ""
.Ix "Application defaults files" "" "3~11" ""
.Ix "ApplicationShell" "" "2~3" ""
.Ix "ApplicationShell" "" "4~1" ""
.Ix "Argument lists for widgets" "" "3~6" ""
.Ix "Argument values" "defining in UIL" "18~20" ""
.Ix "Argument values, setting" "" "3~13" ""
.Ix "Arguments" "coupled in UIL" "19~8" ""
.Ix "Arguments, retrieving and modifying" "" "3~15" ""
.Ix "ArrowButton widgets" "" "5~11" ""
.Ix "ArrowButton" "" "2~4" ""
.Ix "ArrowButtonGadget" "" "2~18" ""
.Ix "at symbol (@)" "" "14~3" ""
.Ix "Atom" "" "E~1" ""
.Ix "attributes" "changing windows" "12~6" ""
.Ix "autoKeyFocus resource" "" "13~5" ""
.Ix "autoKeyFocus resource" "" "16~4" ""
.Ix "autoRaiseDelay resource" "" "13~5" ""
.Iy "B"
.Ix "background resource" "" "13~9" ""
.Ix "background" "resource" "16~2" ""
.Ix "backgroundPixmap resource" "" "13~10" ""
.Ix "backgroundPixmap resource" "" "16~3" ""
.Ix "base_width, base_height" "WM_NORMAL_HINTS" "12~3" ""
.Ix "behavior resources" "specific appearance" "13~2" ""
.Ix "binding" "a menu to a mouse button or key" "14~9" ""
.Ix "binding" "a menu to a mouse button or key" "14~11" ""
.Ix "bindings" "keyboard, see keyboard bindings" "14~16" ""
.Ix "bindings" "keyboard, see keyboard bindings" "14~19" ""
.Ix "bitmapDirectory resource" "" "14~2" ""
.Ix "bitmapDirectory resource" "" "15~2" ""
.Ix "bitmapDirectory resource" "" "16~5" ""
.Ix "Boolean literals" "" "18~12" ""
.Ix "Border drawing" "" "3~12" ""
.Ix "bottom" "window menu selection" "11~13" ""
.Ix "bottomShadowColor resource" "" "13~9" ""
.Ix "bottomShadowcolor" "resource" "16~2" ""
.Ix "bottomShadowPixmap resource" "" "13~10" ""
.Ix "bottomShadowPixmap resource" "" "16~3" ""
.Ix "BulletinBoard" "" "2~15" ""
.Ix "BulletinBoardDialog" "" "2~15" ""
.Ix "BulletinBoardDialog" "" "5~2" ""
.Ix "button bindings" "definition" "14~12" ""
.Ix "buttonBindings resource" "" "14~15" ""
.Ix "buttonBindings resource" "" "14~18" ""
.Ix "buttonBindings resource" "" "16~5" ""
.Ix "buttons" "large square image" "11~10" ""
.Ix "buttons" "maximize" "11~10" ""
.Ix "buttons" "minimize" "11~10" ""
.Ix "buttons" "on window frame" "11~7" ""
.Ix "buttons" "small square image" "11~10" ""
.Iy "C"
.Ix "Callback structure, list" "" "7~7" ""
.Ix "Callback" "" "E~1" ""
.Ix "Callback" "add" "3~1" ""
.Ix "Callback" "add" "3~15" ""
.Ix "Callback" "adding" "3~6" ""
.Ix "Callback" "adding" "3~7" ""
.Ix "Callback" "list" "3~7" ""
.Ix "Callback" "list" "3~8" ""
.Ix "Callback" "resources" "3~8" ""
.Ix "Callback" "writing procedure" "3~7" ""
.Ix "CascadeButtonGadget" "" "2~18" ""
.Ix "Case sensitivity clause" "" "19~2" ""
.Ix "Categories of widgets" "" "2~2" ""
.Ix "changing window attributes" "" "12~6" ""
.Ix "changing window state" "" "12~6" ""
.Ix "Character set" "" "18~1" ""
.Ix "Character set" "" "8~1" ""
.Ix "Character set" "identifier" "8~2" ""
.Ix "Character set" "universal" "8~2" ""
.Ix "Character set" "user~defined" "18~13" ""
.Ix "CHARACTER_SET function" "" "18~13" ""
.Ix "Child widget" "" "E~2" ""
.Ix "CirculateWindow" "" "12~6" ""
.Ix "Class" "" "E~2" ""
.Ix "Class" "meta" "E~4" ""
.Ix "Class" "widget structure" "2~1" ""
.Ix "Class" "widget" "1~1" ""
.Ix "Class" "widget" "2~1" ""
.Ix "classification of resources" "" "13~2" ""
.Ix "cleanText resource" "" "13~11" ""
.Ix "cleanText resource" "" "16~3" ""
.Ix "Click~to~type focus" "" "9~1" ""
.Ix "click~to~type" "" "13~4" ""
.Ix "client frame windows" "" "11~5" ""
.Ix "client icon windows" "" "11~5" ""
.Ix "client icon" "windows" "11~5" ""
.Ix "client properties" "" "12~1" ""
.Ix "client responses to MWM actions" "" "12~6" ""
.Ix "client specific resources" "" "13~2" ""
.Ix "client windows" "" "11~4" ""
.Ix "client windows" "mattes" "13~11" ""
.Ix "clientAutoPlace resource" "" "13~16" ""
.Ix "clientAutoPlace resource" "" "16~6" ""
.Ix "clientDecoration resource" "" "11~4" ""
.Ix "clientDecoration resource" "" "13~13" ""
.Ix "clientDecoration resource" "" "16~4" ""
.Ix "clientDecoration resource" "and WM_HINTS" "12~7" ""
.Ix "clientDecoration resource" "syntax" "13~14" ""
.Ix "clientFunctions resource" "" "14~8" ""
.Ix "clientFunctions resource" "" "14~10" ""
.Ix "clientFunctions resource" "" "16~4" ""
.Ix "clientFunctions resource" "and WM_HINTS" "12~8" ""
.Ix "ClientMessage Events" "" "12~6" ""
.Ix "Clipboard" "" "8~13" ""
.Ix "close" "window menu selection" "11~13" ""
.Ix "closing a window" "" "11~13" ""
.Ix "closing a window" "window menu button" "11~13" ""
.Ix "Color Defaults" "" "3~13" ""
.Ix "Color values" "defining in UIL" "18~14" ""
.Ix "Color values" "defining in UIL" "18~15" ""
.Ix "Color" "" "3~12" ""
.Ix "COLOR_TABLE Function" "" "18~16" ""
.Ix "coloring icons" "resource table" "16~2" ""
.Ix "coloring mattes" "resource table" "16~2" ""
.Ix "coloring menus" "default values" "13~8" ""
.Ix "coloring windows" "resource table" "16~2" ""
.Ix "coloring" "frame elements" "13~7" ""
.Ix "coloring" "frame elements, default values for color display" "13~7" ""
.Ix "coloring" "frame elements, default values for monochrome display" "13~8" ""
.Ix "coloring" "icon frame elements" "15~6" ""
.Ix "coloring" "matte elements" "13~12" ""
.Ix "colormap focus policy" "" "11~4" ""
.Ix "colormap" "changing" "12~6" ""
.Ix "colormapFocusPolicy resource" "" "16~4" ""
.Ix "colormapFocusPolicy" "" "13~4" ""
.Ix "colormapFocusPolicy" "explicit value" "13~4" ""
.Ix "colormapFocusPolicy" "keyboard value" "13~4" ""
.Ix "colormapFocusPolicy" "pointer value" "13~4" ""
.Ix "ColormapNotify" "" "12~6" ""
.Ix "colormaps" "establishing" "12~6" ""
.Ix "colormaps" "multiple" "13~4" ""
.Ix "Command history region" "" "5~5" ""
.Ix "Command Line Option" "" "13~2" ""
.Ix "Command" "" "2~15" ""
.Ix "CommandWindow" "" "2~9" ""
.Ix "Compile~time expressions" "" "18~24" ""
.Ix "Compile~time expressions" "" "18~27" ""
.Ix "Compiling" "sample programs" "1~8" ""
.Ix "component appearance resources" "" "13~2" ""
.Ix "Composite manager widget" "" "E~2" ""
.Ix "Composite widget class" "" "E~2" ""
.Ix "Composite" "" "1~2" ""
.Ix "Composite" "" "2~8" ""
.Ix "Composite" "" "2~15" ""
.Ix "Composite" "widget" "2~13" ""
.Ix "Compound strings" "" "8~1" ""
.Ix "Compound strings" "character set identifier" "8~2" ""
.Ix "Compound strings" "character set" "8~1" ""
.Ix "Compound strings" "components" "8~2" ""
.Ix "Compound strings" "definition" "8~1" ""
.Ix "Compound strings" "direction" "8~2" ""
.Ix "Compound strings" "direction" "8~3" ""
.Ix "Compound strings" "functions" "8~3" ""
.Ix "Compound strings" "separator" "8~3" ""
.Ix "Compound strings" "tag~length~value" "8~2" ""
.Ix "Compound strings" "text" "8~2" ""
.Ix "Compound strings" "text" "8~3" ""
.Ix "Compound strings" "universal character set" "8~2" ""
.Ix "Concatentation operator" "" "18~8" ""
.Ix "configFile resource" "" "14~1" ""
.Ix "configFile resource" "" "16~5" ""
.Ix "configuration files" "" "10~1" ""
.Ix "configuration files" "" "11~2" ""
.Ix "configuration files" "$HOME/.mwmrc" "11~2" ""
.Ix "configuration files" "$HOME/.Xdefaults" "11~2" ""
.Ix "configuration files" "/usr/lib/X11/app~defaults/Mwm" "11~2" ""
.Ix "configuration files" "/usr/lib/X11/system.mwmrc" "11~2" ""
.Ix "configuration files" "/usr/lib/X11/system.mwmrc" "13~1" ""
.Ix "configuration files" "hierarchy of resource" "13~2" ""
.Ix "ConfigureNotify" "" "12~6" ""
.Ix "ConfigureWindow" "" "12~6" ""
.Ix "configuring window frame appearance and behavior" "" "13~6" ""
.Ix "configuring" "MWM" "13~2" ""
.Ix "configuring" "window" "12~6" ""
.Ix "Constraint" "" "1~2" ""
.Ix "Constraint" "" "2~8" ""
.Ix "Constraint" "" "2~13" ""
.Ix "Constraint" "" "E~2" ""
.Ix "Constraints" "" "5~9" ""
.Ix "Container widgets" "" "2~2" ""
.Ix "Container widgets" "" "2~8" ""
.Ix "contexts" "for key bindings" "14~17" ""
.Ix "contexts" "for key bindings" "14~20" ""
.Ix "contexts" "for mouse button bindings" "14~15" ""
.Ix "contexts" "for mouse button bindings" "14~18" ""
.Ix "controlling input focus" "" "12~6" ""
.Ix "Convenience dialogs" "" "2~14" ""
.Ix "Convenience dialogs" "" "2~15" ""
.Ix "Convenience dialogs" "" "5~2" ""
.Ix "Convenience function" "" "E~2" ""
.Ix "Convenience functions" "" "2~1" ""
.Ix "Convenience functions" "" "2~14" ""
.Ix "Convenience functions" "" "2~19" ""
.Ix "Convenience functions" "" "6~1" ""
.Ix "conventions" "" "10~1" ""
.Ix "conventions" "mouse buttons" "10~1" ""
.Ix "Conversions" "data type" "18~25" ""
.Ix "Converting between types" "" "8~30" ""
.Ix "Coordinated colors for 3~dimensional look" "" "3~13" ""
.Ix "Core" "" "1~2" ""
.Ix "Core" "" "2~4" ""
.Ix "Core" "" "2~8" ""
.Ix "Core" "" "E~2" ""
.Ix "corner brackets" "location" "11~7" ""
.Ix "Create" "defaults files" "3~1" ""
.Ix "Create" "widget" "2~1" ""
.Ix "Create" "widget" "2~19" ""
.Ix "Create" "widget" "3~1" ""
.Ix "Create" "widget" "3~9" ""
.Ix "Creating" "submenus" "6~16" ""
.Ix "Creation" "user interface" "22~19" ""
.Ix "cursor" "in icon box" "15~9" ""
.Ix "Cursor, for menus" "" "6~23" ""
.Ix "Cut and paste functions" "" "8~1" ""
.Ix "Cut and paste functions" "" "8~13" ""
.Ix "Cutting text" "" "7~17" ""
.Iy "D"
.Ix "Data type conversion" "" "18~26" ""
.Ix "Data type conversion" "" "18~27" ""
.Ix "Data type" "conversions" "18~25" ""
.Ix "Declaring objects in UIL" "using as template" "22~27" ""
.Ix "decoration" "icons" "15~5" ""
.Ix "decorations field" "WM_HINTS" "12~7" ""
.Ix "default behavior" "modifying" "11~2" ""
.Ix "default window menu" "configuration file" "14~2" ""
.Ix "default" "keyboard bindings" "14~16" ""
.Ix "default" "keyboard bindings" "14~19" ""
.Ix "default" "mouse button bindings" "14~12" ""
.Ix "Default, dynamic" "" "8~25" ""
.Ix "Defaulting, dynamic" "" "8~1" ""
.Ix "Defaults file" "example" "3~11" ""
.Ix "Defaults file" "XMdemos" "3~3" ""
.Ix "Defaults files" "" "3~10" ""
.Ix "Defaults files" ".Xdefaults" "3~10" ""
.Ix "Defaults files" "application" "3~11" ""
.Ix "Defaults files" "app~defaults" "3~10" ""
.Ix "Defaults files" "app~defaults" "3~11" ""
.Ix "Defaults files" "create" "3~1" ""
.Ix "Defaults files" "localization" "8~1" ""
.Ix "Defaults files" "localization" "8~25" ""
.Ix "Defaults files" "user" "3~11" ""
.Ix "Defaults files" "Xdefaults" "3~11" ""
.Ix "deiconifyKeyFocus resource" "" "13~5" ""
.Ix "deiconifyKeyFocus resource" "" "16~4" ""
.Ix "Diagnostic messages" "" "D~1" ""
.Ix "Dialog convenience functions" "" "5~2" ""
.Ix "Dialog convenience functions, using" "" "5~3" ""
.Ix "Dialog functions" "" "5~1" ""
.Ix "Dialog widgets" "" "1~6" ""
.Ix "Dialog widgets" "" "2~14" ""
.Ix "Dialog widgets" "" "5~1" ""
.Ix "dialog" "" "E~3" ""
.Ix "Dialog" "widgets" "2~2" ""
.Ix "Dialog, definition" "" "2~14" ""
.Ix "Dialogs, using" "" "5~3" ""
.Ix "DialogShell" "" "2~4" ""
.Ix "DialogShell" "" "4~1" ""
.Ix "Direction, compound string" "" "8~2" ""
.Ix "Direction, compound string" "" "8~3" ""
.Ix "display option" "" "13~1" ""
.Ix "Display widgets" "" "2~2" ""
.Ix "Display widgets" "" "2~4" ""
.Ix "Double click" "" "7~4" ""
.Ix "doubleClickTime resource" "" "14~16" ""
.Ix "doubleClickTime resource" "" "14~19" ""
.Ix "doubleClickTime resource" "" "16~5" ""
.Ix "DrawingArea" "" "2~9" ""
.Ix "DrawnButton" "" "2~5" ""
.Ix "Dynamic resource defaulting" "" "8~1" ""
.Ix "Dynamic resource defaulting" "" "8~25" ""
.Iy "E"
.Ix "Efficient operation" "" "3~10" ""
.Ix "enableWarp resource" "" "13~17" ""
.Ix "enforceKeyFocus resource" "" "13~5" ""
.Ix "enforceKeyFocus resource" "" "16~4" ""
.Ix "ErrorDialog" "" "2~16" ""
.Ix "ErrorDialog" "" "5~2" ""
.Ix "Escape sequences" "" "18~8" ""
.Ix "establishing colormaps" "" "12~6" ""
.Ix "Event handlers" "" "6~6" ""
.Ix "explicit value" "colormapFocusPolicy" "13~4" ""
.Ix "explicit value" "keyboardFocusPolicy" "13~4" ""
.Ix "explicit" "" "11~4" ""
.Ix "explicit~listener" "" "13~4" ""
.Ix "Exported resource" "" "22~5" ""
.Ix "EXPORTED" "" "19~3" ""
.Ix "Expressions" "" "18~24" ""
.Iy "F"
.Ix "f.circle_down function" "" "14~7" ""
.Ix "f.circle_up function" "" "14~7" ""
.Ix "f.circle_up function" "" "14~9" ""
.Ix "f.focus function" "" "14~7" ""
.Ix "f.focus function" "" "14~9" ""
.Ix "f.focus_key function" "" "14~7" ""
.Ix "f.focus_key function" "" "14~9" ""
.Ix "f.kill function" "" "14~7" ""
.Ix "f.kill function" "" "14~9" ""
.Ix "f.next_cmap function" "and multiple colormaps" "13~4" ""
.Ix "f.pack_icons function" "" "15~9" ""
.Ix "f.post_wmenu function" "and key bindings" "14~17" ""
.Ix "f.post_wmenu function" "and key bindings" "14~20" ""
.Ix "f.resize function" "and mouse button bindings" "14~13" ""
.Ix "f.send_msg function" "" "14~7" ""
.Ix "f.send_msg function" "" "14~10" ""
.Ix "f.send_msg function" "and _MOTIF WM MESSAGES" "12~9" ""
.Ix "f.send_msg function" "and _MOTIF_WM_MESSAGES" "12~5" ""
.Ix "f.set_behavior function" "" "14~7" ""
.Ix "f.set_behavior function" "" "14~10" ""
.Ix "fadeNormalIcon resource" "" "15~9" ""
.Ix "fadeNormalIcon resource" "" "16~7" ""
.Ix "feedback window" "" "11~6" ""
.Ix "Fetch" "deferring" "22~22" ""
.Ix "FileSelectionBox" "" "2~15" ""
.Ix "FileSelectionDialog" "" "2~16" ""
.Ix "FileSelectionDialog" "" "5~2" ""
.Ix "flags field" "_MOTIF_WM_HINTS" "12~7" ""
.Ix "flags field" "_MOTIF_WM_INFO" "12~10" ""
.Ix "flags" "WM_NORMAL_HINTS" "12~2" ""
.Ix "Floating~point values" "" "18~17" ""
.Ix "focus policies" "" "11~3" ""
.Ix "focus policies" "quick reference table" "16~4" ""
.Ix "focus policy resources" "" "13~4" ""
.Ix "focus policy resources" "syntax" "13~5" ""
.Ix "Focus" "" "9~1" ""
.Ix "Focus" "accepting" "9~1" ""
.Ix "Focus" "click~to~type" "9~1" ""
.Ix "Focus" "pointer~driven" "9~1" ""
.Ix "focusAutoRaise resource" "" "13~5" ""
.Ix "focusAutoRaise resource" "" "16~4" ""
.Ix "Font table value" "defining" "18~18" ""
.Ix "Font units, setting" "" "8~30" ""
.Ix "Font values" "" "18~17" ""
.Ix "fontList resource" "" "13~6" ""
.Ix "fontList resource" "" "16~5" ""
.Ix "foreground resource" "" "13~9" ""
.Ix "foreground" "resource" "16~2" ""
.Ix "Form" "" "2~15" ""
.Ix "FormDialog" "" "2~16" ""
.Ix "FormDialog" "" "5~2" ""
.Ix "frame elements" "illustration" "13~7" ""
.Ix "frame parts" "" "11~7" ""
.Ix "Frame" "" "2~9" ""
.Ix "frameBorderWidth resource" "" "13~15" ""
.Ix "frameBorderWidth resource" "" "16~6" ""
.Ix "frameless windows" "" "13~13" ""
.Ix "frames" "configuring the general appearance and behavior" "13~6" ""
.Ix "full application modal windows" "" "11~5" ""
.Ix "functions field" "_MOTIF_WM_HINTS" "12~8" ""
.Ix "functions" "" "14~4" ""
.Ix "Functions" "" "18~12" ""
.Ix "Functions" "any value" "18~23" ""
.Ix "Functions" "compound string" "8~3" ""
.Ix "Functions" "cut and paste" "8~1" ""
.Ix "Functions" "cut and paste" "8~13" ""
.Ix "Functions" "data type conversion" "18~26" ""
.Ix "Functions" "data type conversion" "18~27" ""
.Ix "Functions" "font table value" "18~18" ""
.Ix "Functions" "List widget" "7~1" ""
.Ix "Functions" "MrmFetchSetValues" "22~23" ""
.Ix "Functions" "pixmap caching" "8~27" ""
.Ix "functions" "quick reference table" "16~8" ""
.Ix "Functions" "reason value" "18~22" ""
.Ix "Functions" "RowColumn" "7~10" ""
.Ix "functions" "table of MWM valid" "14~5" ""
.Ix "Functions" "Text widget" "7~14" ""
.Ix "Functions" "translation table value" "18~22" ""
.Iy "G"
.Ix "Gadgets" "" "2~17" ""
.Ix "Gadgets" "specifying in an object declaration" "19~12" ""
.Ix "globally active input windows" "" "13~5" ""
.Ix "Glossary" "" "E~1" ""
.Ix "Grab" "" "E~3" ""
.Ix "Grabbing" "" "8~1" ""
.Iy "H"
.Ix "Header files" "" "3~1" ""
.Ix "Header files" "including" "3~4" ""
.Ix "Help button in Menubar" "" "6~11" ""
.Ix "Help widget" "" "22~27" ""
.Ix "hierarchy of resource configuration files" "" "13~2" ""
.Ix "Hierarchy" "" "3~17" ""
.Ix "Hierarchy, widget" "" "1~1" ""
.Ix "High~level programmatic access" "" "12~10" ""
.Ix "History region, Command" "" "5~5" ""
.Ix "home directory" "" "13~1" ""
.Ix "HOME environment variable" "" "13~3" ""
.Iy "I"
.Ix "ICCCM" "MWM information not covered by" "12~7" ""
.Ix "icon appearance resources" "syntax" "15~6" ""
.Ix "icon box" "" "11~15" ""
.Ix "icon box" "" "15~8" ""
.Ix "icon box" "configuring appearance and behavior" "15~8" ""
.Ix "icon box" "resources that configure, quick reference table" "16~7" ""
.Ix "icon box" "window menu" "15~8" ""
.Ix "icon box" "windows" "11~6" ""
.Ix "icon coloring resources" "syntax" "15~7" ""
.Ix "icon field" "WM_STATE" "12~5" ""
.Ix "icon frame windows" "" "11~5" ""
.Ix "icon image" "default image" "15~1" ""
.Ix "icon images" "and WM_HINTS" "15~1" ""
.Ix "icon label" "and WM_ICON_NAME" "15~2" ""
.Ix "icon placement resources" "" "15~5" ""
.Ix "icon placement resources" "syntax" "15~5" ""
.Ix "icon" "label" "15~2" ""
.Ix "Icon" "using as a label" "22~11" ""
.Ix "icon_mask" "" "12~4" ""
.Ix "icon_pixmap" "" "12~4" ""
.Ix "icon_window" "" "12~4" ""
.Ix "icon_x" "" "12~4" ""
.Ix "icon_y" "" "12~4" ""
.Ix "iconAutoPlace resource" "" "15~4" ""
.Ix "iconAutoPlace resource" "" "16~7" ""
.Ix "iconbox" "<\fITab\fR> key" "15~9" ""
.Ix "iconBoxGeometry resource" "" "15~8" ""
.Ix "iconBoxGeometry resource" "" "16~7" ""
.Ix "iconBoxName resource" "" "15~8" ""
.Ix "iconBoxName resource" "" "16~7" ""
.Ix "iconBoxTitle resource" "" "15~8" ""
.Ix "iconBoxTitle resource" "" "16~7" ""
.Ix "iconClick resource" "" "15~4" ""
.Ix "iconClick resource" "" "16~7" ""
.Ix "iconDecoration resource" "" "15~5" ""
.Ix "iconDecoration resource" "icon box" "15~9" ""
.Ix "iconDecoration resource" "table of values" "15~5" ""
.Ix "iconify" "minimizing a window" "11~10" ""
.Ix "iconImage resource" "" "15~1" ""
.Ix "iconImage resource" "" "15~2" ""
.Ix "iconImage resource" "" "16~7" ""
.Ix "iconImageBackground resource" "" "15~7" ""
.Ix "iconImageBackground" "resource" "16~2" ""
.Ix "iconImageBottomShadowColor resource" "" "15~7" ""
.Ix "iconImageBottomShadowColor" "resource" "16~2" ""
.Ix "iconImageBottomShadowPixmap resource" "" "15~7" ""
.Ix "iconImageBottomShadowPixmap resource" "" "16~3" ""
.Ix "iconImageForeground resource" "" "15~7" ""
.Ix "iconImageForeground" "resource" "16~2" ""
.Ix "iconImageMaximum resource" "" "15~5" ""
.Ix "iconImageMaximum resource" "" "16~7" ""
.Ix "iconImageMaximum" "and WM_ICON_SIZE" "12~5" ""
.Ix "iconImageMinimum resource" "" "15~5" ""
.Ix "iconImageMinimum resource" "" "16~7" ""
.Ix "iconImageMinimum" "and WM_ICON_SIZE" "12~5" ""
.Ix "iconImageTopShadowColor resource" "" "15~7" ""
.Ix "iconImageTopShadowColor" "resource" "16~2" ""
.Ix "iconImageTopShadowPixmap resource" "" "15~7" ""
.Ix "iconImageTopShadowPixmap resource" "" "16~3" ""
.Ix "iconPlacement resource" "" "15~4" ""
.Ix "iconPlacement resource" "" "16~7" ""
.Ix "iconPlacement resource" "table of values" "15~4" ""
.Ix "iconPlacementMargin resource" "" "15~5" ""
.Ix "iconPlacementMargin resource" "" "16~7" ""
.Ix "icons" "" "11~15" ""
.Ix "icons" "" "15~1" ""
.Ix "icons" "anatomy" "15~1" ""
.Ix "icons" "coloring frame elements" "15~6" ""
.Ix "icons" "configuring appearance and behavior" "15~5" ""
.Ix "icons" "image" "15~1" ""
.Ix "icons" "manipulating in icon box with a mouse" "15~9" ""
.Ix "icons" "manipulating in icon box with keyboard" "15~9" ""
.Ix "icons" "manipulating in icon box" "15~9" ""
.Ix "icons" "manipulating with a mouse" "15~2" ""
.Ix "icons" "manipulating with the keyboard" "15~3" ""
.Ix "icons" "placement on the workspace" "15~4" ""
.Ix "icons" "resources that configure, quick reference table" "16~7" ""
.Ix "icons" "sizing" "15~5" ""
.Ix "Identifier declaration" "UIL coding techniques" "22~13" ""
.Ix "Identifiers" "" "19~13" ""
.Ix "images" "icon" "15~1" ""
.Ix "Imported resource" "" "22~5" ""
.Ix "IMPORTED" "" "19~3" ""
.Ix "Include directive" "" "19~14" ""
.Ix "Including header files" "" "3~1" ""
.Ix "Including header files" "" "3~4" ""
.Ix "InformationDialog" "" "2~16" ""
.Ix "InformationDialog" "" "5~2" ""
.Ix "Initialization" "Motif Toolkit" "22~18" ""
.Ix "Initialization" "MRM" "22~18" ""
.Ix "Initialization" "user interface" "22~18" ""
.Ix "Initializing Xt Intrinsics" "" "3~4" ""
.Ix "input focus policy" "" "11~4" ""
.Ix "input focus policy" "explicit" "11~4" ""
.Ix "input focus policy" "track pointer" "11~4" ""
.Ix "input focus" "controlling" "12~6" ""
.Ix "input modes" "" "11~5" ""
.Ix "input" "WM_HINTS" "12~4" ""
.Ix "input_mode field" "WM_HINTS" "12~8" ""
.Ix "Instance" "" "2~1" ""
.Ix "Instance" "" "E~7" ""
.Ix "Instantiate" "" "E~3" ""
.Ix "Interacting with MWM" "" "8~1" ""
.Ix "interactive placement" "with keyboard" "11~14" ""
.Ix "interactive placement" "with mouse" "11~14" ""
.Ix "interactivePlacement resource" "" "13~16" ""
.Ix "interactivePlacement resource" "" "16~6" ""
.Ix "Intern" "" "E~3" ""
.Ix "Internal Application Defaults" "" "13~2" ""
.Ix "Internationalization" "using UIL" "22~28" ""
.Ix "Inter~Client Communications Conventions Manual" "" "12~1" ""
.Iy "K"
.Ix "key actions" "on frame components, defaults" "11~8" ""
.Ix "key bindings" "contexts" "14~17" ""
.Ix "key bindings" "contexts" "14~20" ""
.Ix "keyBindings resource" "" "14~20" ""
.Ix "keyBindings resource" "" "16~5" ""
.Ix "keyBindings resource" "syntax" "14~20" ""
.Ix "keyboard bindings" "default" "14~16" ""
.Ix "keyboard bindings" "default" "14~19" ""
.Ix "keyboard bindings" "definition" "14~16" ""
.Ix "keyboard bindings" "definition" "14~19" ""
.Ix "keyboard bindings" "making a new set" "14~20" ""
.Ix "keyboard bindings" "modifying, example" "14~17" ""
.Ix "keyboard bindings" "modifying, example" "14~20" ""
.Ix "keyboard bindings" "syntax" "14~16" ""
.Ix "keyboard bindings" "syntax" "14~19" ""
.Ix "Keyboard grabbing" "" "8~1" ""
.Ix "keyboard input focus" "" "11~3" ""
.Ix "keyboard input focus" "default methods for changing" "11~3" ""
.Ix "Keyboard interface" "" "9~1" ""
.Ix "Keyboard interface" "option menus" "6~21" ""
.Ix "Keyboard interface" "popup menus" "6~8" ""
.Ix "Keyboard interface" "pulldown menus" "6~13" ""
.Ix "keyboard value" "colormapFocusPolicy" "13~4" ""
.Ix "keyboard" "" "11~2" ""
.Ix "keyboard" "actions" "11~2" ""
.Ix "keyboardFocusPolicy resource" "" "16~4" ""
.Ix "keyboardFocusPolicy" "" "13~4" ""
.Ix "keyboardFocusPolicy" "explicit" "13~4" ""
.Ix "keyboardFocusPolicy" "pointer" "13~4" ""
.Ix "Keysyms" "defining in UIL" "18~13" ""
.Ix "Keywords" "" "18~3" ""
.Ix "Keywords" "EXPORTED" "19~3" ""
.Ix "Keywords" "IMPORTED" "19~3" ""
.Ix "Keywords" "PRIVATE" "19~3" ""
.Ix "killing a window" "" "11~13" ""
.Iy "L"
.Ix "Label string" "" "6~5" ""
.Ix "Label" "" "2~5" ""
.Ix "Label" "specifying as an icon" "22~11" ""
.Ix "Label, for option menus" "" "6~20" ""
.Ix "LabelGadget" "" "2~18" ""
.Ix "Libraries" "" "3~1" ""
.Ix "limitResize resource" "" "13~15" ""
.Ix "limitResize resource" "" "16~6" ""
.Ix "Linking libraries" "" "3~1" ""
.Ix "Linking libraries" "" "3~10" ""
.Ix "List section" "" "19~7" ""
.Ix "List types" "" "19~7" ""
.Ix "List types" "argument" "19~7" ""
.Ix "List types" "callback" "19~8" ""
.Ix "List types" "control" "19~9" ""
.Ix "List" "" "2~5" ""
.Ix "List" "" "7~1" ""
.Ix "List" "callback structure" "7~7" ""
.Ix "List" "functions" "7~1" ""
.Ix "List" "selection policies" "7~8" ""
.Ix "List" "using" "7~3" ""
.Ix "Literals" "getting from UID files" "22~22" ""
.Ix "Localization of defaults file" "" "8~1" ""
.Ix "Localization of defaults file" "" "8~25" ""
.Ix "lowerOnIconify resource" "" "15~4" ""
.Ix "lowerOnIconify resource" "" "16~7" ""
.Ix "Low~level programmatic access" "" "12~10" ""
.Iy "M"
.Ix "MainWindow" "" "2~9" ""
.Ix "MainWindow" "" "3~16" ""
.Ix "Manager" "" "1~5" ""
.Ix "Manager" "" "E~3" ""
.Ix "MapWindow" "" "12~6" ""
.Ix "matte Background" "resource" "16~2" ""
.Ix "matte elements" "coloring" "13~12" ""
.Ix "matteBackground resource" "" "13~12" ""
.Ix "matteBottomShadowColor resource" "" "13~12" ""
.Ix "matteBottomShadowColor" "resource" "16~2" ""
.Ix "matteBottomShadowPixmap resource" "" "13~12" ""
.Ix "matteBottomShadowPixmap resource" "" "16~3" ""
.Ix "matteForeground resource" "" "13~12" ""
.Ix "matteForeground" "resource" "16~2" ""
.Ix "mattes" "changing the pixmap" "13~12" ""
.Ix "mattes" "client windows" "13~11" ""
.Ix "mattes" "definition" "13~11" ""
.Ix "mattes" "syntax" "13~12" ""
.Ix "matteTopShadowColor resource" "" "13~12" ""
.Ix "matteTopShadowColor" "resource" "16~2" ""
.Ix "matteTopShadowPixmap resource" "" "13~12" ""
.Ix "matteWidth resource" "" "13~12" ""
.Ix "matteWidth" "resource" "16~2" ""
.Ix "max aspect.x, max aspect.y" "WM_NORMAL_HINTS" "12~3" ""
.Ix "max_width, max_height" "WM_ICON_SIZE" "12~5" ""
.Ix "max_width, max_height" "WM_NORMAL_HINTS" "12~2" ""
.Ix "maximize button" "" "11~10" ""
.Ix "maximize button" "location" "11~7" ""
.Ix "maximize" "window menu selection" "11~13" ""
.Ix "maximumClientSize resource" "" "12~2" ""
.Ix "maximumClientSize resource" "" "13~15" ""
.Ix "maximumClientSize resource" "" "16~6" ""
.Ix "maximumClientSize resource" "and limitResize resource" "13~15" ""
.Ix "maximumClientSize resource" "and WM_NORMAL_HINTS" "13~15" ""
.Ix "maximumMaximumSize resource" "" "12~2" ""
.Ix "maximumMaximumSize resource" "" "13~16" ""
.Ix "maximumMaximumSize resource" "" "16~6" ""
.Ix "menu button" "location" "11~7" ""
.Ix "menu colors" "default values" "13~8" ""
.Ix "Menu cursor" "" "6~23" ""
.Ix "Menu system" "" "6~1" ""
.Ix "Menu widgets" "" "2~2" ""
.Ix "Menu widgets" "" "2~17" ""
.Ix "menu window" "size" "14~8" ""
.Ix "menu window" "size" "14~11" ""
.Ix "menu" "binding to a mouse button or key" "14~9" ""
.Ix "menu" "binding to a mouse button or key" "14~11" ""
.Ix "menu" "default window menu, sample configuration file" "14~2" ""
.Ix "menu" "items" "14~3" ""
.Ix "menu" "titles" "14~3" ""
.Ix "menu" "window menu, changing" "14~9" ""
.Ix "menu" "window menu, changing" "14~11" ""
.Ix "menu" "workspace or root, sample configuration" "14~2" ""
.Ix "MenuBar" "" "2~9" ""
.Ix "MenuBar" "" "3~16" ""
.Ix "MenuBar" "" "6~4" ""
.Ix "MenuPanes" "" "6~1" ""
.Ix "Menus" "" "6~1" ""
.Ix "menus" "default" "14~2" ""
.Ix "menus" "making a new one, example" "14~3" ""
.Ix "menus" "making a new" "14~3" ""
.Ix "menus" "modifying" "14~2" ""
.Ix "menus" "modifying" "14~3" ""
.Ix "menus" "syntax for making or adding to" "14~2" ""
.Ix "MenuShell" "" "2~4" ""
.Ix "MenuShell" "" "4~1" ""
.Ix "MenuShell" "" "6~5" ""
.Ix "MenuShell" "creating" "6~25" ""
.Ix "MessageBox" "" "2~15" ""
.Ix "MessageBox" "" "3~17" ""
.Ix "MessageBox" "" "5~12" ""
.Ix "MessageBox" "examples" "5~12" ""
.Ix "MessageDialog" "" "2~16" ""
.Ix "MessageDialog" "" "3~17" ""
.Ix "Meta class" "" "E~4" ""
.Ix "Microsoft's Presentation Manager" "" "13~1" ""
.Ix "min_aspect.x, min_aspect.y" "WM_NORMAL_HINTS" "12~3" ""
.Ix "min_width, min_height" "WM_ICON_SIZE" "12~5" ""
.Ix "min_width, min_height" "WM_NORMAL_HINTS" "12~2" ""
.Ix "minimize button" "" "11~10" ""
.Ix "minimize button" "location" "11~7" ""
.Ix "minimize" "iconifying a window" "11~10" ""
.Ix "minimize" "window menu selection" "11~13" ""
.Ix "minimized windows" "" "11~5" ""
.Ix "Mnemonic" "" "6~8" ""
.Ix "Mnemonic" "" "6~13" ""
.Ix "Mnemonic" "" "6~21" ""
.Ix "Mnemonic" "" "7~17" ""
.Ix "mnemonics" "" "11~13" ""
.Ix "mnemonics" "" "14~4" ""
.Ix "Modal dialog widget" "" "5~1" ""
.Ix "Modeless dialog widget" "" "5~1" ""
.Ix "modeless windows" "" "11~5" ""
.Ix "Modifying arguments" "" "3~15" ""
.Ix "modifying" "default behavior" "11~2" ""
.Ix "modifying" "keyboard bindings" "14~16" ""
.Ix "modifying" "keyboard bindings" "14~19" ""
.Ix "Module declaration clauses" "in UIL" "22~2" ""
.Ix "Module declaration" "in UIL" "22~2" ""
.Ix "Module header" "objects clause" "19~11" ""
.Ix "monochrome display" "coloring frames" "13~8" ""
.Ix "monochrome display" "pixmap tiling" "13~10" ""
.Ix "Motif Window Manager" "" "8~31" ""
.Ix "Motif" "initialization" "22~18" ""
.Ix "Motif" "version number" "8~35" ""
.Ix "Motif" "version" "8~1" ""
.Ix "Motif" "window manager" "8~1" ""
.Ix "Motif" "window manager" "8~35" ""
.Ix "Motifburger" "" "22~20" ""
.Ix "mouse actions" "on frame components, defaults" "11~8" ""
.Ix "mouse button binding" "example" "14~15" ""
.Ix "mouse button binding" "example" "14~18" ""
.Ix "mouse button bindings" "" "14~12" ""
.Ix "mouse button bindings" "button actions" "14~14" ""
.Ix "mouse button bindings" "contexts" "14~15" ""
.Ix "mouse button bindings" "contexts" "14~18" ""
.Ix "mouse button bindings" "default" "14~12" ""
.Ix "mouse button bindings" "definition" "14~12" ""
.Ix "mouse button bindings" "making a new set" "14~15" ""
.Ix "mouse button bindings" "making a new set" "14~18" ""
.Ix "mouse button bindings" "making a new set, example" "14~15" ""
.Ix "mouse button bindings" "making a new set, example" "14~18" ""
.Ix "mouse button bindings" "modifier keys" "14~14" ""
.Ix "mouse button bindings" "modifying" "14~13" ""
.Ix "mouse button bindings" "syntax" "14~13" ""
.Ix "mouse button" "double~click timing" "14~16" ""
.Ix "mouse button" "double~click timing" "14~19" ""
.Ix "mouse buttons" "Button 4 and Button 5" "14~14" ""
.Ix "mouse" "" "11~1" ""
.Ix "mouse" "button locations" "10~1" ""
.Ix "move " "window menu selection" "11~13" ""
.Ix "moveThreshold resource" "" "13~16" ""
.Ix "moveThreshold resource" "" "16~6" ""
.Ix "moving a window" "" "11~9" ""
.Ix "MRM (Motif Resource Manager)" "MrmFetchSetValues function" "22~23" ""
.Ix "MRM function" "MrmCloseHierarchy" "21~3" ""
.Ix "MRM function" "MrmFetchColorLiteral" "21~9" ""
.Ix "MRM function" "MrmFetchIconLiteral" "21~10" ""
.Ix "MRM function" "MrmFetchLiteral" "21~11" ""
.Ix "MRM function" "MrmFetchSetValues" "21~6" ""
.Ix "MRM function" "MrmFetchWidget" "21~7" ""
.Ix "MRM function" "MrmFetchWidgetOverride" "21~8" ""
.Ix "MRM function" "MrmInitialize" "21~1" ""
.Ix "MRM function" "MrmOpenHierarchy" "21~1" ""
.Ix "MRM function" "MrmRegisterClass" "21~4" ""
.Ix "MRM function" "MrmRegisterNames" "21~5" ""
.Ix "MRM function" "MrmRegisterNamesInHierarchy" "21~5" ""
.Ix "MRM" "creating interface" "22~15" ""
.Ix "MRM" "deferred fetching" "22~22" ""
.Ix "MRM" "fetch" "22~19" ""
.Ix "MRM" "functions table" "22~17" ""
.Ix "MRM" "Getting literal values from UID files" "22~22" ""
.Ix "MRM" "initialization" "22~18" ""
.Ix "MRM" "MrmFetchSetValues function" "22~27" ""
.Ix "MRM" "MrmFetchWidgetOverride function" "22~27" ""
.Ix "MRM" "MrmInitialize function" "22~20" ""
.Ix "MRM" "MrmOpenHierarchy function" "22~21" ""
.Ix "MRM" "MrmRegisterNames function" "22~21" ""
.Ix "MRM" "overview" "17~1" ""
.Ix "MRM" "registering names" "22~21" ""
.Ix "MRM" "scope" "22~5" ""
.Ix "MrmCloseHierarchy" "definition" "21~3" ""
.Ix "MrmCloseHierarchy" "description" "21~3" ""
.Ix "MrmFAILURE" "" "21~3" ""
.Ix "MrmFAILURE" "" "21~4" ""
.Ix "MrmFAILURE" "" "21~5" ""
.Ix "MrmFAILURE" "" "21~6" ""
.Ix "MrmFAILURE" "" "21~7" ""
.Ix "MrmFAILURE" "" "21~8" ""
.Ix "MrmFAILURE" "" "21~9" ""
.Ix "MrmFAILURE" "" "21~10" ""
.Ix "MrmFAILURE" "" "21~11" ""
.Ix "MrmFetchColorLiteral" "definition" "21~9" ""
.Ix "MrmFetchColorLiteral" "description" "21~10" ""
.Ix "MrmFetchIconLiteral" "definition" "21~10" ""
.Ix "MrmFetchIconLiteral" "description" "21~10" ""
.Ix "MrmFetchLiteral" "" "22~27" ""
.Ix "MrmFetchLiteral" "definition" "21~11" ""
.Ix "MrmFetchLiteral" "description" "21~11" ""
.Ix "MrmFetchSetValues function" "" "22~23" ""
.Ix "MrmFetchSetValues function" "" "22~27" ""
.Ix "MrmFetchSetValues" "" "22~27" ""
.Ix "MrmFetchSetValues" "definition" "21~6" ""
.Ix "MrmFetchSetValues" "description" "21~6" ""
.Ix "MrmFetchWidget" "" "22~19" ""
.Ix "MrmFetchWidget" "" "22~22" ""
.Ix "MrmFetchWidget" "" "22~27" ""
.Ix "MrmFetchWidget" "definition" "21~7" ""
.Ix "MrmFetchWidget" "description" "21~8" ""
.Ix "MrmFetchWidgetOverride function" "" "22~27" ""
.Ix "MrmFetchWidgetOverride" "" "22~27" ""
.Ix "MrmFetchWidgetOverride" "definition" "21~8" ""
.Ix "MrmFetchWidgetOverride" "description" "21~9" ""
.Ix "MrmInitialize" "" "22~19" ""
.Ix "MrmInitialize" "" "22~20" ""
.Ix "MrmInitialize" "definition" "21~1" ""
.Ix "MrmInitialize" "description" "21~1" ""
.Ix "MrmNOT_FOUND" "" "21~3" ""
.Ix "MrmNOT_FOUND" "" "21~8" ""
.Ix "MrmNOT_FOUND" "" "21~9" ""
.Ix "MrmNOT_FOUND" "" "21~10" ""
.Ix "MrmNOT_FOUND" "" "21~11" ""
.Ix "MrmOpenHierarchy" "" "22~19" ""
.Ix "MrmOpenHierarchy" "definition" "21~1" ""
.Ix "MrmOpenHierarchy" "description" "21~2" ""
.Ix "MrmRegisterClass" "definition" "21~4" ""
.Ix "MrmRegisterClass" "description" "21~4" ""
.Ix "MrmRegisterNames" "" "22~11" ""
.Ix "MrmRegisterNames" "" "22~19" ""
.Ix "MrmRegisterNames" "" "22~21" ""
.Ix "MrmRegisterNames" "definition" "21~5" ""
.Ix "MrmRegisterNames" "description" "21~5" ""
.Ix "MrmRegisterNamesInHierarchy" "" "22~19" ""
.Ix "MrmRegisterNamesInHierarchy" "definition" "21~5" ""
.Ix "MrmRegisterNamesInHierarchy" "description" "21~6" ""
.Ix "MrmSUCCESS" "" "21~3" ""
.Ix "MrmSUCCESS" "" "21~4" ""
.Ix "MrmSUCCESS" "" "21~5" ""
.Ix "MrmSUCCESS" "" "21~6" ""
.Ix "MrmSUCCESS" "" "21~7" ""
.Ix "MrmSUCCESS" "" "21~8" ""
.Ix "MrmSUCCESS" "" "21~9" ""
.Ix "MrmSUCCESS" "" "21~10" ""
.Ix "MrmSUCCESS" "" "21~11" ""
.Ix "MrmWRONG_TYPE" "" "21~11" ""
.Ix "multiScreen resource" "" "13~4" ""
.Ix "MWM functions" "quick reference table" "16~8" ""
.Ix "MWM resource description file" "" "14~1" ""
.Ix "Mwm" "resource class" "13~3" ""
.Ix "mwm" "resource name" "13~3" ""
.Iy "N"
.Ix "Names" "" "18~2" ""
.Ix "Names" "in UIL" "22~13" ""
.Ix "No explicit programmatic access" "" "12~10" ""
.Iy "O"
.Ix "Object declaration" "" "19~11" ""
.Ix "Object declaration" "UIL coding techniques" "22~13" ""
.Ix "Object declaration" "using as a template" "22~27" ""
.Ix "Object section" "" "19~10" ""
.Ix "Object section" "declaring gadgets in" "19~12" ""
.Ix "Object type specification" "in object declaration" "19~12" ""
.Ix "Object type specification" "using objects clause" "19~11" ""
.Ix "Object" "" "1~2" ""
.Ix "Object" "" "2~17" ""
.Ix "Object" "" "2~18" ""
.Ix "Object" "defining in UIL" "19~10" ""
.Ix "Object" "modifying at run time" "22~23" ""
.Ix "Object" "scope of references" "19~3" ""
.Ix "Objects clause" "" "19~11" ""
.Ix "Option menu" "" "2~17" ""
.Ix "Option menu" "" "6~5" ""
.Ix "Option menu" "" "6~19" ""
.Ix "Option menu" "creating" "6~20" ""
.Ix "Option menu" "interacting with" "6~21" ""
.Ix "Option menu" "system" "6~19" ""
.Ix "order of precedence" "resource specifications" "13~3" ""
.Ix "OSF/Motif toolkit" "" "12~1" ""
.Ix "OSF/Motif widget library (Xm)" "" "13~8" ""
.Ix "OSF/Motif" "default behavior" "14~7" ""
.Ix "OSF/Motif" "default behavior" "14~10" ""
.Ix "OverrideShell" "" "2~3" ""
.Ix "OverrideShell" "" "4~1" ""
.Ix "override~redirect windows" "" "11~5" ""
.Iy "P"
.Ix "PanedWindow" "" "2~13" ""
.Ix "passButtons resource" "" "13~5" ""
.Ix "passButtons resource" "" "16~4" ""
.Ix "passSelectButton resource" "" "13~5" ""
.Ix "passSelectButton resource" "" "16~4" ""
.Ix "Persistence" "" "E~4" ""
.Ix "Pixmap caching functions" "" "8~27" ""
.Ix "Pixmap" "caching" "8~1" ""
.Ix "Pixmap" "caching" "8~27" ""
.Ix "pixmap" "mattes" "13~12" ""
.Ix "Pixmap" "naming" "8~1" ""
.Ix "Pixmap" "naming" "8~27" ""
.Ix "pixmap" "valid values for" "13~11" ""
.Ix "Pixmaps" "defining in UIL" "18~15" ""
.Ix "Pixmaps" "defining in UIL" "22~8" ""
.Ix "pixmaps" "definition" "13~10" ""
.Ix "Pixmaps" "illustration of values" "13~10" ""
.Ix "pixmaps" "quick reference table" "16~2" ""
.Ix "pixmaps" "window frames" "13~10" ""
.Ix "pointer cursor" "" "11~1" ""
.Ix "pointer value" "colormapFocusPolicy" "13~4" ""
.Ix "pointer value" "keyboardFocusPolicy" "13~4" ""
.Ix "pointer" "" "11~1" ""
.Ix "Pointer~driven focus" "" "9~1" ""
.Ix "Popup menu system" "" "6~3" ""
.Ix "Popup menu" "interacting with" "6~8" ""
.Ix "Popup menu" "system" "6~5" ""
.Ix "Popup MenuPane" "" "2~17" ""
.Ix "Popup MenuPane" "" "6~5" ""
.Ix "Popup MenuPane" "" "6~8" ""
.Ix "Popup MenuPane" "convenience function" "6~6" ""
.Ix "Popup window" "" "3~16" ""
.Ix "Pop~up" "" "E~5" ""
.Ix "positioning windows" "" "13~15" ""
.Ix "positioning" "resources, quick reference table" "16~6" ""
.Ix "positionIsFrame resource" "" "13~16" ""
.Ix "positionIsFrame resource" "" "16~6" ""
.Ix "positionIsFrame resource" "and WM_NORMAL_HINTS" "13~16" ""
.Ix "positionOnScreen resource" "" "13~16" ""
.Ix "positionOnScreen resource" "" "16~6" ""
.Ix "Post" "" "E~5" ""
.Ix "Presentation Manager, Microsoft" "" "13~1" ""
.Ix "primary application modal windows" "" "11~5" ""
.Ix "Primary selection" "" "7~17" ""
.Ix "Primary selection" "" "7~19" ""
.Ix "primary window" "" "11~4" ""
.Ix "Primitive" "" "1~2" ""
.Ix "Primitive" "" "2~4" ""
.Ix "Primitive" "" "2~7" ""
.Ix "Primitive" "" "E~5" ""
.Ix "Private resource" "" "22~5" ""
.Ix "Private Shell" "" "4~1" ""
.Ix "PRIVATE" "" "19~3" ""
.Ix "Procedure declaration" "" "19~5" ""
.Ix "Procedure declaration" "" "19~6" ""
.Ix "Procedure declaration" "" "22~3" ""
.Ix "Procedure declaration" "UIL coding techniques" "22~13" ""
.Ix "PROCEDURE section" "" "19~5" ""
.Ix "programmatic access" "high~level" "12~10" ""
.Ix "programmatic access" "low~level" "12~10" ""
.Ix "programmatic access" "no explicit" "12~10" ""
.Ix "Programmatic Interface Standards" "" "12~1" ""
.Ix "Programming, advanced" "" "3~13" ""
.Ix "PromptDialog" "" "2~16" ""
.Ix "PromptDialog" "" "5~2" ""
.Ix "properties" "client" "12~1" ""
.Ix "properties" "working with" "12~5" ""
.Ix "Property" "" "E~5" ""
.Ix "property" "_MOTIF_WM_HINTS" "11~5" ""
.Ix "property" "_MOTIF_WM_HINTS" "12~7" ""
.Ix "property" "_MOTIF_WM_INFO" "12~9" ""
.Ix "property" "_MOTIF_WM_MENU" "12~9" ""
.Ix "property" "_MOTIF_WM_MESSAGES" "12~9" ""
.Ix "property" "RESOURCE_MANAGER" "13~2" ""
.Ix "property" "WM_ NAME" "12~2" ""
.Ix "property" "WM_CLASS" "12~2" ""
.Ix "property" "WM_CLASS" "12~4" ""
.Ix "property" "WM_COLORMAP_WINDOWS" "12~5" ""
.Ix "property" "WM_HINTS" "12~3" ""
.Ix "property" "WM_ICON_NAME" "12~2" ""
.Ix "property" "WM_ICON_SIZE" "12~5" ""
.Ix "property" "WM_NORMAL_HINTS" "12~2" ""
.Ix "property" "WM_PROTOCOLS" "12~4" ""
.Ix "property" "WM_TRANSIENT_FOR" "11~5" ""
.Ix "property" "WM_TRANSIENT_FOR" "12~4" ""
.Ix "Protocol" "" "8~31" ""
.Ix "Protocol" "" "E~5" ""
.Ix "protocol" "_MOTIF_WM_MESSAGES" "12~5" ""
.Ix "Protocol" "management" "8~31" ""
.Ix "protocol" "WM_DELETE_WINDOW" "12~5" ""
.Ix "protocol" "WM_SAVE_YOURSELF" "12~5" ""
.Ix "protocol" "WM_TAKE_FOCUS" "12~5" ""
.Ix "Public shell" "" "4~1" ""
.Ix "Pulldown menu system" "" "6~4" ""
.Ix "Pulldown menu system" "" "6~10" ""
.Ix "Pulldown MenuPane" "" "2~17" ""
.Ix "Pulldown MenuPane" "convenience function" "6~11" ""
.Ix "Pulldown menus, interacting with" "" "6~13" ""
.Ix "Punctuation characters" "" "18~2" ""
.Ix "PushButton" "" "2~6" ""
.Ix "PushButtonGadget" "" "2~18" ""
.Ix "PushButtonGadget" "" "3~16" ""
.Iy "Q"
.Ix "QuestionDialog" "" "2~16" ""
.Ix "QuestionDialog" "" "5~3" ""
.Ix "quick reference table" "coloring" "16~2" ""
.Ix "quick reference table" "configuring icons" "16~7" ""
.Ix "quick reference table" "configuring the icon box" "16~7" ""
.Ix "quick reference table" "controlling window size and position" "16~6" ""
.Ix "quick reference table" "controlling windows" "16~4" ""
.Ix "quick reference table" "focus policies" "16~4" ""
.Ix "quick reference table" "MWM functions" "16~8" ""
.Ix "quick reference table" "shading (pixmaps)" "16~2" ""
.Ix "quick reference table" "window decorations" "16~3" ""
.Ix "quitTimeout resource" "" "12~5" ""
.Ix "quitTimeout resource" "" "13~6" ""
.Ix "quitTimeout resource" "" "16~5" ""
.Iy "R"
.Ix "RadioBox" "" "2~17" ""
.Ix "Realization" "user interface" "22~19" ""
.Ix "Realize widget" "" "3~1" ""
.Ix "real~estate driven" "" "13~4" ""
.Ix "Reason value" "" "18~22" ""
.Ix "Rect" "" "2~17" ""
.Ix "RectObj" "" "1~2" ""
.Ix "RectObj" "" "2~18" ""
.Ix "reduced~element windows" "" "13~13" ""
.Ix "res_class" "" "12~4" ""
.Ix "res_name" "" "12~4" ""
.Ix "resize border" "location" "11~7" ""
.Ix "resize border" "See also resize frame handles." "11~7" ""
.Ix "resize frame handles" "" "11~8" ""
.Ix "resize frame handles" "cursor shapes" "11~8" ""
.Ix "resize frame handles" "location" "11~7" ""
.Ix "resizeBorderWidth resource" "" "13~16" ""
.Ix "resizeBorderWidth resource" "" "16~6" ""
.Ix "resizeCursors resource" "" "13~16" ""
.Ix "resizeCursors resource" "" "16~6" ""
.Ix "Resolution independence" "" "8~1" ""
.Ix "Resolution independence" "" "8~29" ""
.Ix "resource class" "Mwm" "13~3" ""
.Ix "resource description file" "" "14~1" ""
.Ix "resource files" "" "11~2" ""
.Ix "resource name" "mwm" "13~3" ""
.Ix "resource tables" "" "16~1" ""
.Ix "resource" "activeBackground" "13~9" ""
.Ix "resource" "activeBackgroundPixmap" "13~10" ""
.Ix "resource" "activeBottomshadowColor" "13~9" ""
.Ix "resource" "activeBottomShadowPixmap" "13~10" ""
.Ix "resource" "activeForeground" "13~9" ""
.Ix "resource" "activeTopShadowColor" "13~9" ""
.Ix "resource" "activeTopShadowPixmap" "13~10" ""
.Ix "resource" "autoKeyFocus" "13~5" ""
.Ix "resource" "autoRaiseDelay" "13~5" ""
.Ix "resource" "background" "13~9" ""
.Ix "resource" "backgroundPixmap" "13~10" ""
.Ix "resource" "bitmapDirectory" "14~2" ""
.Ix "resource" "bitmapDirectory" "15~2" ""
.Ix "resource" "bottomShadowColor" "13~9" ""
.Ix "resource" "bottomShadowPixmap" "13~10" ""
.Ix "resource" "buttonBindings" "14~15" ""
.Ix "resource" "buttonBindings" "14~18" ""
.Ix "resource" "cleanText" "13~11" ""
.Ix "resource" "clientAutoPlace" "13~16" ""
.Ix "resource" "clientDecoration" "11~4" ""
.Ix "resource" "clientDecoration" "13~13" ""
.Ix "resource" "clientFunctions" "14~8" ""
.Ix "resource" "clientFunctions" "14~10" ""
.Ix "resource" "colormapFocusPolicy" "13~4" ""
.Ix "resource" "configFile" "14~1" ""
.Ix "resource" "deiconifyKeyFocus" "13~5" ""
.Ix "resource" "doubleClickTime" "14~16" ""
.Ix "resource" "doubleClickTime" "14~19" ""
.Ix "resource" "enableWarp" "13~17" ""
.Ix "resource" "enforceKeyFocus" "13~5" ""
.Ix "resource" "fadeNormalIcon" "15~9" ""
.Ix "resource" "focusAutoRaise" "13~5" ""
.Ix "resource" "fontList" "13~6" ""
.Ix "resource" "foreground" "13~9" ""
.Ix "resource" "frameBorderWidth" "13~15" ""
.Ix "resource" "iconAutoPlace" "15~4" ""
.Ix "resource" "iconBoxGeometry" "15~8" ""
.Ix "resource" "iconBoxName" "15~8" ""
.Ix "resource" "iconBoxTitle" "15~8" ""
.Ix "resource" "iconClick" "15~4" ""
.Ix "resource" "iconDecoration" "15~5" ""
.Ix "resource" "iconImage" "15~2" ""
.Ix "resource" "iconImageBackground" "15~7" ""
.Ix "resource" "iconImageBottomShadowColor" "15~7" ""
.Ix "resource" "iconImageBottomShadowPixmap" "15~7" ""
.Ix "resource" "iconImageForeground" "15~7" ""
.Ix "resource" "iconImageMaximum" "15~5" ""
.Ix "resource" "iconImageMinimum" "15~5" ""
.Ix "resource" "iconImageTopShadowColor" "15~7" ""
.Ix "resource" "iconImageTopShadowPixmap" "15~7" ""
.Ix "resource" "iconPlacement" "15~4" ""
.Ix "resource" "iconPlacementMargin" "15~5" ""
.Ix "resource" "interactivePlacement" "13~16" ""
.Ix "resource" "keyBindings" "14~20" ""
.Ix "resource" "keyboardFocusPolicy" "13~4" ""
.Ix "resource" "limitResize" "13~15" ""
.Ix "resource" "lowerOnIconify" "15~4" ""
.Ix "resource" "matteBackground" "13~12" ""
.Ix "resource" "matteBottomShadowColor" "13~12" ""
.Ix "resource" "matteBottomShadowPixmap" "13~12" ""
.Ix "resource" "matteForeground" "13~12" ""
.Ix "resource" "matteTopShadowColor" "13~12" ""
.Ix "resource" "matteTopShadowPixmap" "13~12" ""
.Ix "resource" "matteWidth" "13~12" ""
.Ix "resource" "maximumClientSize" "13~15" ""
.Ix "resource" "maximumMaximumSize" "13~16" ""
.Ix "resource" "moveThreshold" "13~16" ""
.Ix "resource" "multiScreen" "13~4" ""
.Ix "resource" "passButtons" "13~5" ""
.Ix "resource" "passSelectButton" "13~5" ""
.Ix "resource" "positionIsFrame" "13~16" ""
.Ix "resource" "positionOnScreen" "13~16" ""
.Ix "resource" "quitTimeout" "12~5" ""
.Ix "resource" "quitTimeout" "13~6" ""
.Ix "resource" "resizeBorderWidth" "13~16" ""
.Ix "resource" "resizeCursors" "13~16" ""
.Ix "resource" "saveUnder" "13~6" ""
.Ix "resource" "showFeedback" "13~16" ""
.Ix "resource" "startupKeyFocus" "13~5" ""
.Ix "resource" "topShadowColor" "13~9" ""
.Ix "resource" "topShadowPixmap" "13~10" ""
.Ix "resource" "transientDecoration" "11~5" ""
.Ix "resource" "transientDecoration" "13~13" ""
.Ix "resource" "transientFunctions" "14~8" ""
.Ix "resource" "transientFunctions" "14~11" ""
.Ix "resource" "useClientIcon" "15~2" ""
.Ix "resource" "useIconBox" "15~8" ""
.Ix "resource" "windowMenu" "14~9" ""
.Ix "resource" "windowMenu" "14~11" ""
.Ix "resource" "wMenuButtonClick" "14~12" ""
.Ix "resource" "wMenuButtonClick2" "14~12" ""
.Ix "resource, definition" "" "13~2" ""
.Ix "RESOURCE_MANAGER" "" "13~2" ""
.Ix "Resources" "callback" "3~8" ""
.Ix "resources" "client specific" "13~2" ""
.Ix "resources" "component appearance" "13~2" ""
.Ix "resources" "for pixmaps, quick reference" "16~2" ""
.Ix "Resources" "specifying" "3~10" ""
.Ix "resources" "syntax" "13~3" ""
.Ix "resources" "syntax, quick reference" "16~1" ""
.Ix "restore" "window menu selection" "11~13" ""
.Ix "Retrieving arguments" "" "3~15" ""
.Ix "root menu" "sample configuration" "14~2" ""
.Ix "root" "window" "11~4" ""
.Ix "RowColumn" "" "2~9" ""
.Ix "RowColumn" "" "2~17" ""
.Ix "RowColumn" "" "3~16" ""
.Ix "RowColumn" "" "7~1" ""
.Ix "RowColumn" "" "7~10" ""
.Ix "RowColumn" "functions" "7~10" ""
.Ix "RowColumn" "layout" "7~11" ""
.Ix "RowColumn" "margin spacing" "7~14" ""
.Ix "RowColumn" "orientation" "7~11" ""
.Ix "RowColumn" "packing" "7~11" ""
.Ix "RowColumn" "packing" "7~12" ""
.Ix "RowColumn" "sizing" "7~11" ""
.Ix "RowColumn" "spacing between children" "2~5" ""
.Ix "RowColumn" "spacing" "7~11" ""
.Ix "RowColumn" "spacing" "7~14" ""
.Ix "RowColumn" "types" "7~10" ""
.Iy "S"
.Ix "Sample program" "font selection" "3~15" ""
.Ix "Sample program" "simple" "3~2" ""
.Ix "saveUnder resource" "" "12~6" ""
.Ix "saveUnder resource" "" "13~6" ""
.Ix "saveUnder resource" "" "16~5" ""
.Ix "Scale" "r" "2~10" ""
.Ix "ScrollBar" "" "2~6" ""
.Ix "ScrollBar" "" "2~9" ""
.Ix "ScrolledWindow" "" "2~9" ""
.Ix "ScrolledWindow" "" "2~11" ""
.Ix "secondary window" "" "11~4" ""
.Ix "Selection area" "" "6~5" ""
.Ix "Selection area, for option menus" "" "6~19" ""
.Ix "Selection policies, List" "" "7~8" ""
.Ix "Selection" "primary" "7~17" ""
.Ix "Selection" "primary" "7~19" ""
.Ix "SelectionBox" "" "2~15" ""
.Ix "SelectionBox" "" "5~14" ""
.Ix "SelectionDialog" "" "2~16" ""
.Ix "SelectionDialog" "" "5~3" ""
.Ix "Separator" "" "2~7" ""
.Ix "Separator, compound string" "" "8~3" ""
.Ix "SeparatorGadget" "" "2~18" ""
.Ix "Setting argument values" "" "3~13" ""
.Ix "Setting font units" "" "8~30" ""
.Ix "Shadows" "" "3~12" ""
.Ix "Shell widgets" "" "2~3" ""
.Ix "Shell" "" "1~2" ""
.Ix "Shell" "" "1~4" ""
.Ix "Shell" "" "3~4" ""
.Ix "Shell" "" "4~1" ""
.Ix "Shell" "appearance" "4~2" ""
.Ix "Shell" "class" "4~1" ""
.Ix "Shell" "private" "4~1" ""
.Ix "Shell" "public" "4~1" ""
.Ix "Shell" "widgets" "2~2" ""
.Ix "Shell" "widgets" "4~1" ""
.Ix "showFeedback resource" "" "13~16" ""
.Ix "showFeedback resource" "" "16~6" ""
.Ix "size" "of menu window" "14~8" ""
.Ix "size" "of menu window" "14~11" ""
.Ix "size" "window menu selection" "11~13" ""
.Ix "sizing" "icons" "15~5" ""
.Ix "sizing" "resources, quick reference table" "16~6" ""
.Ix "sizing" "windows" "13~15" ""
.Ix "Source code, xmfonts.c" "" "3~19" ""
.Ix "Specialized widgets" "" "7~1" ""
.Ix "specific appearance and behavior resources" "" "13~2" ""
.Ix "stacking windows" "" "11~15" ""
.Ix "standard X events" "" "12~10" ""
.Ix "startupKeyFocus resource" "" "13~5" ""
.Ix "startupKeyFocus resource" "" "16~4" ""
.Ix "state field" "WM_STATE" "12~5" ""
.Ix "Style Guide" "" "11~1" ""
.Ix "Subclass" "" "E~6" ""
.Ix "Submenus" "" "6~3" ""
.Ix "Submenus" "creating" "6~16" ""
.Ix "syntax for declaring resources" "" "13~3" ""
.Ix "syntax" "accelerators" "14~4" ""
.Ix "syntax" "adding or removing frame elements" "13~14" ""
.Ix "syntax" "clientDecoration" "13~14" ""
.Ix "syntax" "focus policy resources" "13~5" ""
.Ix "syntax" "for resources controlling the appearance of frame elements" "13~9" ""
.Ix "syntax" "for resources, quick reference" "16~1" ""
.Ix "syntax" "for size and position refinement resources" "13~17" ""
.Ix "syntax" "icon appearance resources" "15~6" ""
.Ix "syntax" "icon coloring resources" "15~7" ""
.Ix "syntax" "icon placement resources" "15~5" ""
.Ix "syntax" "mattes" "13~12" ""
.Ix "syntax" "mnemonics" "14~4" ""
.Ix "syntax" "transientDecoration" "13~14" ""
.Ix "synthetic events" "" "12~10" ""
.Ix "system modal windows" "" "11~5" ""
.Iy "T"
.Ix "Tab groups" "" "9~1" ""
.Ix "Tab groups, traversal" "" "9~2" ""
.Ix "Tag~length~value" "" "8~2" ""
.Ix "Text" "" "2~7" ""
.Ix "Text" "" "7~1" ""
.Ix "Text" "compound string" "8~3" ""
.Ix "Text" "functions" "7~14" ""
.Ix "Text" "primary selection" "7~17" ""
.Ix "Text" "widget" "7~14" ""
.Ix "TextField" "" "2~8" ""
.Ix "Three~dimensional appearance" "" "3~13" ""
.Ix "tiles" "definition" "13~10" ""
.Ix "title area" "" "11~9" ""
.Ix "title area" "location" "11~7" ""
.Ix "title bar" "" "11~9" ""
.Ix "title bar" "location" "11~7" ""
.Ix "titles" "menus" "14~3" ""
.Ix "ToggleButton" "" "2~8" ""
.Ix "ToggleButtonGadget" "" "2~19" ""
.Ix "toolkit" "OSF/Motif" "12~1" ""
.Ix "TopLevelShell" "" "2~3" ""
.Ix "TopLevelShell" "" "4~1" ""
.Ix "topShadowColor resource" "" "13~9" ""
.Ix "topShadowColor" "resource" "16~2" ""
.Ix "topShadowPixmap resource" "" "13~10" ""
.Ix "topShadowPixmap resource" "" "16~3" ""
.Ix "top~level window" "" "11~4" ""
.Ix "top~level window" "creating" "12~1" ""
.Ix "track pointer" "" "11~4" ""
.Ix "track pointer" "" "13~4" ""
.Ix "tracked~listener" "" "13~4" ""
.Ix "transientDecoration resource" "" "11~5" ""
.Ix "transientDecoration resource" "" "13~13" ""
.Ix "transientDecoration resource" "" "16~4" ""
.Ix "transientDecoration resource" "syntax" "13~14" ""
.Ix "transientFunctions resource" "" "14~8" ""
.Ix "transientFunctions resource" "" "14~11" ""
.Ix "transientFunctions resource" "" "16~4" ""
.Ix "transientFunctions" "" "14~8" ""
.Ix "transientFunctions" "" "14~11" ""
.Ix "TransientShell" "" "2~3" ""
.Ix "Translation table value" "" "18~22" ""
.Ix "Translation" "" "E~6" ""
.Ix "Traversal" "" "6~21" ""
.Ix "Traversal" "" "9~1" ""
.Ix "Traversal" "between tab groups" "9~2" ""
.Ix "Traversal" "with popup menus" "6~8" ""
.Ix "Traversal" "with pulldown menus" "6~13" ""
.Ix "Traversal" "within tab groups" "9~2" ""
.Ix "Tree, widget" "" "3~18" ""
.Iy "U"
.Ix "UIL (User Interface Language)" "modifying objects at run time" "22~23" ""
.Ix "UIL Functions" "" "18~12" ""
.Ix "UIL Functions" "ARGUMENT" "18~20" ""
.Ix "UIL Functions" "CHARACTER_SET" "18~13" ""
.Ix "UIL Functions" "COLOR" "18~14" ""
.Ix "UIL Functions" "COLOR_TABLE" "18~15" ""
.Ix "UIL functions" "COLOR_TABLE" "22~8" ""
.Ix "UIL Functions" "data type conversion" "18~26" ""
.Ix "UIL Functions" "data type conversion" "18~27" ""
.Ix "UIL Functions" "FLOAT" "18~17" ""
.Ix "UIL Functions" "FONT" "18~17" ""
.Ix "UIL Functions" "FONT_TABLE" "18~18" ""
.Ix "UIL Functions" "ICON" "18~15" ""
.Ix "UIL functions" "ICON" "22~8" ""
.Ix "UIL Functions" "KEYSYM" "18~13" ""
.Ix "UIL Functions" "reason value" "18~22" ""
.Ix "UIL Functions" "RGB" "18~15" ""
.Ix "UIL Functions" "SINGLE_FLOAT" "18~17" ""
.Ix "UIL module" "any value" "18~23" ""
.Ix "UIL module" "argument values" "18~20" ""
.Ix "UIL module" "Boolean literals" "18~12" ""
.Ix "UIL module" "case sensitivity clause" "19~2" ""
.Ix "UIL module" "coding techniques" "22~13" ""
.Ix "UIL module" "color values" "18~14" ""
.Ix "UIL module" "color values" "18~15" ""
.Ix "UIL module" "data type conversion functions in" "18~26" ""
.Ix "UIL module" "defining gadgets in" "19~12" ""
.Ix "UIL module" "floating~point literals" "18~12" ""
.Ix "UIL module" "floating~point values" "18~17" ""
.Ix "UIL module" "font table value" "18~18" ""
.Ix "UIL module" "font values" "18~17" ""
.Ix "UIL module" "functions" "18~12" ""
.Ix "UIL module" "identifier declaration" "22~13" ""
.Ix "UIL module" "include directive" "19~14" ""
.Ix "UIL module" "integer literals" "18~11" ""
.Ix "UIL module" "keysyms" "18~13" ""
.Ix "UIL module" "keywords" "18~3" ""
.Ix "UIL module" "list section" "19~7" ""
.Ix "UIL module" "list types" "19~7" ""
.Ix "UIL module" "literals" "18~6" ""
.Ix "UIL module" "module declaration clauses" "22~2" ""
.Ix "UIL module" "module declaration" "22~2" ""
.Ix "UIL module" "names" "18~2" ""
.Ix "UIL module" "names" "22~13" ""
.Ix "UIL module" "object declaration" "19~11" ""
.Ix "UIL module" "object declaration" "22~13" ""
.Ix "UIL module" "object section" "19~10" ""
.Ix "UIL module" "pixmap value" "18~15" ""
.Ix "UIL module" "pixmap value" "22~8" ""
.Ix "UIL module" "procedure declaration" "19~5" ""
.Ix "UIL module" "procedure declaration" "19~6" ""
.Ix "UIL module" "procedure declaration" "22~3" ""
.Ix "UIL module" "procedure declaration" "22~13" ""
.Ix "UIL module" "procedure section" "19~5" ""
.Ix "UIL module" "punctuation characters" "18~2" ""
.Ix "UIL module" "reason value" "18~22" ""
.Ix "UIL module" "string literals" "18~6" ""
.Ix "UIL module" "structure of" "19~1" ""
.Ix "UIL module" "structure of" "22~1" ""
.Ix "UIL module" "translation table value" "18~22" ""
.Ix "UIL module" "user~defined character set" "18~13" ""
.Ix "UIL module" "using an icon as a label" "22~11" ""
.Ix "UIL module" "using compile~time expressions in" "18~27" ""
.Ix "UIL module" "value declaration" "19~4" ""
.Ix "UIL module" "value declaration" "22~5" ""
.Ix "UIL module" "value declaration" "22~13" ""
.Ix "UIL module" "value section" "19~4" ""
.Ix "UIL module" "value types list" "22~5" ""
.Ix "UIL module" "value types" "19~4" ""
.Ix "UIL module" "version clause" "19~2" ""
.Ix "UIL module" "widget declaration" "22~9" ""
.Ix "UIL module" "widget declaration" "22~13" ""
.Ix "UIL names" "" "22~13" ""
.Ix "UIL procedure" "declaring" "19~6" ""
.Ix "UIL specification file" "any value" "18~23" ""
.Ix "UIL specification file" "argument values" "18~20" ""
.Ix "UIL specification file" "Boolean literals" "18~12" ""
.Ix "UIL specification file" "case sensitivity clause" "19~2" ""
.Ix "UIL specification file" "coding techniques" "22~13" ""
.Ix "UIL specification file" "color values" "18~14" ""
.Ix "UIL specification file" "color values" "18~15" ""
.Ix "UIL specification file" "floating~point literals" "18~12" ""
.Ix "UIL specification file" "floating~point values" "18~17" ""
.Ix "UIL specification file" "font table value" "18~18" ""
.Ix "UIL specification file" "font values" "18~17" ""
.Ix "UIL specification file" "functions" "18~12" ""
.Ix "UIL specification file" "identifier declaration" "22~13" ""
.Ix "UIL specification file" "include directive" "19~14" ""
.Ix "UIL specification file" "integer literals" "18~11" ""
.Ix "UIL specification file" "keysyms" "18~13" ""
.Ix "UIL specification file" "keywords" "18~3" ""
.Ix "UIL specification file" "list section" "19~7" ""
.Ix "UIL specification file" "list types" "19~7" ""
.Ix "UIL specification file" "literals" "18~6" ""
.Ix "UIL specification file" "module declaration clauses" "22~2" ""
.Ix "UIL specification file" "module declaration" "22~2" ""
.Ix "UIL specification file" "names" "18~2" ""
.Ix "UIL specification file" "names" "22~13" ""
.Ix "UIL specification file" "object declaration" "19~11" ""
.Ix "UIL specification file" "object declaration" "22~13" ""
.Ix "UIL specification file" "object section" "19~10" ""
.Ix "UIL specification file" "pixmap value" "18~15" ""
.Ix "UIL specification file" "pixmap value" "22~8" ""
.Ix "UIL specification file" "procedure declaration" "19~5" ""
.Ix "UIL specification file" "procedure declaration" "19~6" ""
.Ix "UIL specification file" "procedure declaration" "22~3" ""
.Ix "UIL specification file" "procedure declaration" "22~13" ""
.Ix "UIL specification file" "procedure section" "19~5" ""
.Ix "UIL specification file" "punctuation characters" "18~2" ""
.Ix "UIL specification file" "reason value" "18~22" ""
.Ix "UIL specification file" "string literals" "18~6" ""
.Ix "UIL specification file" "structure of" "19~1" ""
.Ix "UIL specification file" "structure of" "22~1" ""
.Ix "UIL specification file" "translation table value" "18~22" ""
.Ix "UIL specification file" "user~defined character set" "18~13" ""
.Ix "UIL specification file" "using an icon as a label" "22~11" ""
.Ix "UIL specification file" "value declaration" "19~4" ""
.Ix "UIL specification file" "value declaration" "22~5" ""
.Ix "UIL specification file" "value declaration" "22~13" ""
.Ix "UIL specification file" "value section" "19~4" ""
.Ix "UIL specification file" "value types list" "22~5" ""
.Ix "UIL specification file" "value types" "19~4" ""
.Ix "UIL specification file" "version clause" "19~2" ""
.Ix "UIL specification file" "widget declaration" "22~9" ""
.Ix "UIL specification file" "widget declaration" "22~13" ""
.Ix "UIL value" "getting from UID files" "22~22" ""
.Ix "UIL" "any value" "18~23" ""
.Ix "UIL" "argument values" "18~20" ""
.Ix "UIL" "arguments list" "19~7" ""
.Ix "UIL" "Boolean literals" "18~12" ""
.Ix "UIL" "callbacks list" "19~8" ""
.Ix "UIL" "case sensitivity clause" "19~2" ""
.Ix "UIL" "character set" "18~1" ""
.Ix "UIL" "clauses on module declaration" "22~2" ""
.Ix "UIL" "coding techniques" "22~13" ""
.Ix "UIL" "color values" "18~14" ""
.Ix "UIL" "color values" "18~15" ""
.Ix "UIL" "command qualifiers" "20~1" ""
.Ix "UIL" "compiler diagnostics" "20~6" ""
.Ix "UIL" "compiler include files" "20~6" ""
.Ix "UIL" "compiler listing" "20~6" ""
.Ix "UIL" "compiler machine listing" "20~6" ""
.Ix "UIL" "compiler warnings" "20~6" ""
.Ix "UIL" "compiler" "20~1" ""
.Ix "UIL" "compile~time expressions" "18~24" ""
.Ix "UIL" "compile~time expressions" "18~27" ""
.Ix "UIL" "controls list" "19~9" ""
.Ix "UIL" "coupled arguments" "19~8" ""
.Ix "UIL" "data type conversion" "18~26" ""
.Ix "UIL" "data type conversions" "18~25" ""
.Ix "UIL" "default character set" "20~5" ""
.Ix "UIL" "escape sequences" "18~8" ""
.Ix "UIL" "floating~point literals" "18~12" ""
.Ix "UIL" "floating~point values" "18~17" ""
.Ix "UIL" "font table value" "18~18" ""
.Ix "UIL" "font values" "18~17" ""
.Ix "UIL" "identifiers" "19~13" ""
.Ix "UIL" "include directive" "19~14" ""
.Ix "UIL" "integer literals" "18~11" ""
.Ix "UIL" "keysyms" "18~13" ""
.Ix "UIL" "keywords" "18~3" ""
.Ix "UIL" "list section" "19~7" ""
.Ix "UIL" "list types" "19~7" ""
.Ix "UIL" "literals" "18~6" ""
.Ix "UIL" "module declaration" "22~2" ""
.Ix "UIL" "names" "18~2" ""
.Ix "UIL" "names" "22~13" ""
.Ix "UIL" "object declaration" "19~11" ""
.Ix "UIL" "object section" "19~10" ""
.Ix "UIL" "operators" "18~27" ""
.Ix "UIL" "overview" "17~1" ""
.Ix "UIL" "pixmap value" "18~15" ""
.Ix "UIL" "pixmap value" "22~8" ""
.Ix "UIL" "procedure declaration" "19~5" ""
.Ix "UIL" "procedure declaration" "19~6" ""
.Ix "UIL" "procedure declaration" "22~3" ""
.Ix "UIL" "procedure section" "19~5" ""
.Ix "UIL" "punctuation characters" "18~2" ""
.Ix "UIL" "reason value" "18~22" ""
.Ix "UIL" "scope of references" "19~3" ""
.Ix "UIL" "scope" "22~5" ""
.Ix "UIL" "setting up for deferred fetching" "22~22" ""
.Ix "UIL" "specification file structure" "19~1" ""
.Ix "UIL" "specifying an interface for international markets" "22~28" ""
.Ix "UIL" "string literals" "18~6" ""
.Ix "UIL" "structure of module" "22~1" ""
.Ix "UIL" "translation table value" "18~22" ""
.Ix "UIL" "user~defined character set" "18~13" ""
.Ix "UIL" "using Help widget" "22~27" ""
.Ix "UIL" "using object declaration as a template" "22~27" ""
.Ix "UIL" "value declaration" "19~4" ""
.Ix "UIL" "value declaration" "22~5" ""
.Ix "UIL" "value section" "19~4" ""
.Ix "UIL" "value types" "19~4" ""
.Ix "UIL" "value types" "22~5" ""
.Ix "UIL" "version clause" "19~2" ""
.Ix "UIL" "widget declaration" "22~9" ""
.Ix "Universal character set" "" "8~2" ""
.Ix "Unmanaged widget" "" "2~19" ""
.Ix "useClientIcon resource" "" "15~2" ""
.Ix "useClientIcon resource" "" "16~7" ""
.Ix "useIconBox resource" "" "15~8" ""
.Ix "useIconBox resource" "" "16~7" ""
.Ix "User interface object specification" "in object declaration" "19~12" ""
.Ix "user interface" "" "11~1" ""
.Ix "User interface" "creation" "22~19" ""
.Ix "user interface" "default behavior" "11~1" ""
.Ix "User interface" "initialization" "22~18" ""
.Ix "User interface" "realization" "22~19" ""
.Ix "User interface" "specifying using UIL" "22~20" ""
.Ix "User~defined character set" "" "18~13" ""
.Ix "Using dialog convenience functions" "" "5~3" ""
.Ix "Using dialogs" "" "5~3" ""
.Ix "Using Text widget" "" "7~15" ""
.Ix "Using the List widget" "" "7~3" ""
.Ix "Using Widgets" "" "3~1" ""
.Iy "V"
.Ix "Value declaration" "" "19~4" ""
.Ix "Value declaration" "" "22~5" ""
.Ix "Value declaration" "scope of" "22~5" ""
.Ix "Value declaration" "UIL coding techniques" "22~13" ""
.Ix "Value section" "" "19~4" ""
.Ix "Value types list" "" "22~5" ""
.Ix "Value types" "" "19~4" ""
.Ix "Value" "scope of references" "19~3" ""
.Ix "Values" "Boolean literals" "18~12" ""
.Ix "Values" "floating~point literals" "18~12" ""
.Ix "Values" "integer literals" "18~11" ""
.Ix "Values" "literals" "18~6" ""
.Ix "Values" "string literals" "18~6" ""
.Ix "VendorShell" "" "12~4" ""
.Ix "VendorShell" "" "12~7" ""
.Ix "VendorShell" "" "2~3" ""
.Ix "VendorShell" "" "2~4" ""
.Ix "VendorShell" "" "4~1" ""
.Ix "Version clause" "" "19~2" ""
.Ix "Version number, motif" "" "8~35" ""
.Ix "Visual attributes" "" "3~12" ""
.Iy "W"
.Ix "WarningDialog" "" "2~16" ""
.Ix "WarningDialog" "" "5~3" ""
.Ix "Widget declaration" "" "22~9" ""
.Ix "Widget declaration" "UIL coding techniques" "22~13" ""
.Ix "Widget" "" "1~1" ""
.Ix "Widget" "" "2~1" ""
.Ix "Widget" "" "E~7" ""
.Ix "Widget" "child" "E~2" ""
.Ix "Widget" "class structure" "2~1" ""
.Ix "Widget" "classes" "1~1" ""
.Ix "Widget" "classes" "2~1" ""
.Ix "Widget" "composite manager" "E~2" ""
.Ix "Widget" "composite" "2~13" ""
.Ix "Widget" "composite" "E~2" ""
.Ix "Widget" "constraint" "2~13" ""
.Ix "Widget" "container" "2~8" ""
.Ix "Widget" "create" "2~1" ""
.Ix "Widget" "create" "2~19" ""
.Ix "Widget" "create" "3~1" ""
.Ix "Widget" "create" "3~9" ""
.Ix "Widget" "definition" "2~1" ""
.Ix "Widget" "dialog" "2~14" ""
.Ix "Widget" "display" "2~4" ""
.Ix "Widget" "drawing areas" "3~12" ""
.Ix "Widget" "hierarchy" "1~1" ""
.Ix "Widget" "hierarchy" "3~17" ""
.Ix "Widget" "hierarchy" "4~1" ""
.Ix "Widget" "instance" "2~1" ""
.Ix "Widget" "instance" "E~7" ""
.Ix "Widget" "making visible" "3~9" ""
.Ix "Widget" "manager" "E~3" ""
.Ix "Widget" "primitive" "2~7" ""
.Ix "Widget" "primitive" "E~5" ""
.Ix "Widget" "realize" "3~1" ""
.Ix "Widget" "RowColumn" "7~10" ""
.Ix "Widget" "shell" "2~3" ""
.Ix "Widget" "simple program" "3~2" ""
.Ix "Widget" "specialized" "7~1" ""
.Ix "Widget" "Text" "7~14" ""
.Ix "Widget" "tree" "3~2" ""
.Ix "Widget" "tree" "3~9" ""
.Ix "Widget" "tree" "3~18" ""
.Ix "Widget" "tree" "E~7" ""
.Ix "Widget" "unmanaged" "2~19" ""
.Ix "Widget" "using List" "7~3" ""
.Ix "Widget" "using Text" "7~15" ""
.Ix "widgets" "" "10~1" ""
.Ix "Widgets" "argument lists" "3~6" ""
.Ix "Widgets" "categories" "2~2" ""
.Ix "widgets" "menu" "13~8" ""
.Ix "Widgets" "shell" "4~1" ""
.Ix "Widgets" "using" "3~1" ""
.Ix "Widgets, dialog" "" "5~1" ""
.Ix "Widgets, dialog" "and menus" "5~1" ""
.Ix "Widgets, dialog" "multiple~reply" "5~1" ""
.Ix "Widgets, dialog" "Single~reply" "5~1" ""
.Ix "width_inc, height_inc" "WM_ICON_SIZE" "12~5" ""
.Ix "width_inc, height_inc" "WM_NORMAL_HINTS" "12~2" ""
.Ix "win_gravity" "WM_NORMAL_HINTS" "12~3" ""
.Ix "window decorations" "quick reference table" "16~3" ""
.Ix "window elements" "adding or reducing" "13~13" ""
.Ix "window frame parts" "" "11~7" ""
.Ix "window frame parts" "corner brackets" "11~7" ""
.Ix "window frame parts" "manipulating with a keyboard" "11~11" ""
.Ix "window frame parts" "manipulating with a mouse" "11~11" ""
.Ix "window frame parts" "maximize button" "11~7" ""
.Ix "window frame parts" "minimize button" "11~7" ""
.Ix "window frame parts" "resize border" "11~7" ""
.Ix "window frame parts" "resize frame handles" "11~7" ""
.Ix "window frame parts" "title area" "11~7" ""
.Ix "window frame parts" "title bar" "11~7" ""
.Ix "window frame parts" "window menu button" "11~7" ""
.Ix "window frame" "coloring" "13~7" ""
.Ix "window frame" "elements" "11~6" ""
.Ix "window frame" "maximize button" "11~10" ""
.Ix "window frame" "minimize button" "11~10" ""
.Ix "window frame" "title area" "11~9" ""
.Ix "window frames" "behavior of components (summary table)" "11~7" ""
.Ix "window frames" "changing the pixmap" "13~10" ""
.Ix "window frames" "configuring the general appearance and behavior" "13~6" ""
.Ix "Window Management Calls" "" "12~10" ""
.Ix "Window manager presence" "" "8~35" ""
.Ix "window menu button" "" "11~9" ""
.Ix "window menu button" "location" "11~7" ""
.Ix "window menu file configuration" "" "14~2" ""
.Ix "window menu selections" "" "11~13" ""
.Ix "window menu" "adding to with MOTIF_WM_MENU" "12~9" ""
.Ix "window menu" "changing" "14~9" ""
.Ix "window menu" "changing" "14~11" ""
.Ix "window menu" "icon box" "15~8" ""
.Ix "window menu" "selecting from" "11~12" ""
.Ix "window menu" "selecting items with keyboard" "11~13" ""
.Ix "window menu" "selecting items with mouse" "11~13" ""
.Ix "window position" "interactivePlacement" "11~14" ""
.Ix "window resizing" "" "11~8" ""
.Ix "window size" "interactivePlacement" "11~14" ""
.Ix "window sizing" "constraints on minimum" "11~9" ""
.Ix "window states" "normal, withdrawn, iconic" "12~1" ""
.Ix "window" "active" "11~3" ""
.Ix "window" "changing state" "12~6" ""
.Ix "window" "configuring" "12~6" ""
.Ix "window" "creating" "12~1" ""
.Ix "window" "positioning" "11~9" ""
.Ix "window" "root" "11~4" ""
.Ix "window" "top level" "12~1" ""
.Ix "window" "top~level" "11~4" ""
.Ix "window_group" "" "12~4" ""
.Ix "windowMenu resource" "" "14~9" ""
.Ix "windowMenu resource" "" "14~11" ""
.Ix "windowMenu resource" "" "16~5" ""
.Ix "windowMenu resource" "syntax" "14~9" ""
.Ix "windowMenu resource" "syntax" "14~11" ""
.Ix "windows" "client frame" "11~5" ""
.Ix "windows" "client icon windows" "11~5" ""
.Ix "windows" "client icon" "11~5" ""
.Ix "windows" "closing" "11~13" ""
.Ix "windows" "feedback" "11~6" ""
.Ix "windows" "frameless and reduced~element" "13~13" ""
.Ix "windows" "full application modal" "11~5" ""
.Ix "windows" "icon box" "11~6" ""
.Ix "windows" "icon frame" "11~5" ""
.Ix "windows" "mattes" "13~11" ""
.Ix "windows" "maximizing the size" "11~10" ""
.Ix "windows" "minimized" "11~5" ""
.Ix "windows" "modal" "11~5" ""
.Ix "windows" "modeless" "11~5" ""
.Ix "windows" "override~redirect" "11~5" ""
.Ix "windows" "position" "11~6" ""
.Ix "windows" "positioning" "11~13" ""
.Ix "windows" "positioning" "13~15" ""
.Ix "windows" "primary application modal" "11~5" ""
.Ix "windows" "resizing" "11~13" ""
.Ix "windows" "resources that control, quick reference table" "16~4" ""
.Ix "windows" "size" "11~6" ""
.Ix "windows" "sizing" "13~15" ""
.Ix "windows" "stacking" "11~15" ""
.Ix "windows" "system modal" "11~5" ""
.Ix "windows" "transient" "11~4" ""
.Ix "Wm Widgets" "" "12~6" ""
.Ix "WM_ NAME" "" "12~2" ""
.Ix "WM_CLASS" "" "12~2" ""
.Ix "WM_CLASS" "" "12~4" ""
.Ix "WM_CLASS" "res_class" "12~4" ""
.Ix "WM_CLASS" "res_name" "12~4" ""
.Ix "WM_COLORMAP_WINDOWS" "" "12~5" ""
.Ix "WM_COLORMAP_WINDOWS" "" "12~6" ""
.Ix "WM_COLORMAP_WINDOWS" "and multiple colormaps" "13~4" ""
.Ix "WM_DELETE_WINDOW" "" "12~5" ""
.Ix "WM_DELETE_WINDOW" "and f.kill function" "14~7" ""
.Ix "WM_DELETE_WINDOW" "and f.kill function" "14~9" ""
.Ix "WM_HINTS" "" "12~3" ""
.Ix "WM_HINTS" "and clientDecoration resource" "12~7" ""
.Ix "WM_HINTS" "and clientFunctions resource" "12~8" ""
.Ix "WM_HINTS" "and icon images" "15~1" ""
.Ix "WM_HINTS" "and WM_STATE" "12~5" ""
.Ix "WM_HINTS" "decorations field" "12~7" ""
.Ix "WM_HINTS" "icon_mask" "12~4" ""
.Ix "WM_HINTS" "icon_pixmap" "12~4" ""
.Ix "WM_HINTS" "icon_window" "12~4" ""
.Ix "WM_HINTS" "icon_x" "12~4" ""
.Ix "WM_HINTS" "icon_y" "12~4" ""
.Ix "WM_HINTS" "input" "12~4" ""
.Ix "WM_HINTS" "input_mode field" "12~8" ""
.Ix "WM_HINTS" "window_group" "12~4" ""
.Ix "WM_ICON_NAME" "" "12~2" ""
.Ix "WM_ICON_NAME" "and icon label" "15~2" ""
.Ix "WM_ICON_SIZE" "" "12~5" ""
.Ix "WM_ICON_SIZE" "and iconImageMaximum" "12~5" ""
.Ix "WM_ICON_SIZE" "and iconImageMinimum" "12~5" ""
.Ix "WM_ICON_SIZE" "max_width, max_height" "12~5" ""
.Ix "WM_ICON_SIZE" "min_width, min_height" "12~5" ""
.Ix "WM_ICON_SIZE" "width_inc, height_inc" "12~5" ""
.Ix "WM_NORMAL_HINTS" "" "12~2" ""
.Ix "WM_NORMAL_HINTS" "and limitResize resource" "13~15" ""
.Ix "WM_NORMAL_HINTS" "and maximumClientSize resource" "13~15" ""
.Ix "WM_NORMAL_HINTS" "and positionIsFrame resource" "13~16" ""
.Ix "WM_NORMAL_HINTS" "base_width, base_height" "12~3" ""
.Ix "WM_NORMAL_HINTS" "flags" "12~2" ""
.Ix "WM_NORMAL_HINTS" "max aspect.x, max aspect.y" "12~3" ""
.Ix "WM_NORMAL_HINTS" "max_width, max_height" "12~2" ""
.Ix "WM_NORMAL_HINTS" "min_aspect.x, min_aspect.y" "12~3" ""
.Ix "WM_NORMAL_HINTS" "min_width, min_height" "12~2" ""
.Ix "WM_NORMAL_HINTS" "width_inc, height_inc" "12~2" ""
.Ix "WM_NORMAL_HINTS" "win_gravity" "12~3" ""
.Ix "WM_PROTOCOLS" "" "12~4" ""
.Ix "WM_PROTOCOLS" "and _MOTIF_WM_MESSAGES" "12~9" ""
.Ix "WM_PROTOCOLS" "and f.send_msg function" "14~7" ""
.Ix "WM_PROTOCOLS" "and f.send_msg function" "14~10" ""
.Ix "WM_SAVE_YOURSELF" "" "12~5" ""
.Ix "WM_SAVE_YOURSELF" "and f.kill function" "14~7" ""
.Ix "WM_SAVE_YOURSELF" "and f.kill function" "14~9" ""
.Ix "WM_SAVE_YOURSELF" "and quitTimeout" "12~5" ""
.Ix "WM_STATE" "" "12~5" ""
.Ix "WM_STATE" "and WM_HINTS" "12~5" ""
.Ix "WM_STATE" "icon field" "12~5" ""
.Ix "WM_STATE" "state field" "12~5" ""
.Ix "WM_TAKE_FOCUS" "" "12~5" ""
.Ix "WM_TAKE_FOCUS" "" "12~6" ""
.Ix "WM_TAKE_FOCUS" "and WM_HINTS" "12~4" ""
.Ix "WM_TAKE_FOCUS" "ClientMessage" "12~6" ""
.Ix "WM_TRANSIENT_FOR" "" "11~5" ""
.Ix "WM_TRANSIENT_FOR" "" "12~4" ""
.Ix "wMenuButtonClick resource" "" "14~12" ""
.Ix "wMenuButtonClick resource" "" "16~5" ""
.Ix "wMenuButtonClick2 resource" "" "14~12" ""
.Ix "wMenuButtonClick2 resource" "" "16~5" ""
.Ix "WmShell" "" "12~1" ""
.Ix "WMShell" "" "2~3" ""
.Ix "WMShell" "" "4~1" ""
.Ix "wmWindow field" "_MOTIF_WM_INFO" "12~10" ""
.Ix "Work region" "" "2~9" ""
.Ix "WorkingDialog" "" "2~16" ""
.Ix "WorkingDialog" "" "5~3" ""
.Ix "workspace menu" "sample configuration" "14~2" ""
.Iy "X"
.Ix "X Widgets" "" "10~1" ""
.Ix "X11 client" "" "13~1" ""
.Ix "XChangeProperty" "" "12~9" ""
.Ix "XENVIRONMENT" "" "13~2" ""
.Ix "XGetIconSizes" "" "12~10" ""
.Ix "XGetRGBColormap" "" "12~10" ""
.Ix "Xlib routines" "" "12~10" ""
.Ix "Xlib routines" "C Language X Interface" "12~10" ""
.Ix "Xm OSF/Motif toolkit" "" "12~10" ""
.Ix "XmAddProtocols" "" "12~4" ""
.Ix "XmAddTabGroup" "" "9~2" ""
.Ix "XmArrowButton" "" "2~4" ""
.Ix "XmArrowButton" "arrow direction" "2~5" ""
.Ix "XmArrowButtonGadget" "" "2~18" ""
.Ix "XmBulletinBoard" "" "12~7" ""
.Ix "XmBulletinBoard" "" "2~15" ""
.Ix "XmBulletinBoard" "" "5~1" ""
.Ix "XmBulletinBoard" "" "5~4" ""
.Ix "XmCascadeButton" "" "2~17" ""
.Ix "XmCascadeButtonGadget" "" "2~18" ""
.Ix "XmClipboardCancelCopy" "" "8~13" ""
.Ix "XmClipboardCancelCopy" "" "8~17" ""
.Ix "XmClipboardCopy" "" "8~13" ""
.Ix "XmClipboardCopy" "" "8~15" ""
.Ix "XmClipboardCopyByName" "" "8~13" ""
.Ix "XmClipboardCopyByName" "" "8~16" ""
.Ix "XmClipboardEndCopy" "" "8~13" ""
.Ix "XmClipboardEndCopy" "" "8~18" ""
.Ix "XmClipboardEndRetrieve" "" "8~13" ""
.Ix "XmClipboardEndRetrieve" "" "8~23" ""
.Ix "XmClipboardInquireCount" "" "8~13" ""
.Ix "XmClipboardInquireCount" "" "8~18" ""
.Ix "XmClipboardInquireFormat" "" "8~13" ""
.Ix "XmClipboardInquireFormat" "" "8~19" ""
.Ix "XmClipboardInquireLength" "" "8~13" ""
.Ix "XmClipboardInquireLength" "" "8~20" ""
.Ix "XmClipboardInquirePendingItems" "" "8~13" ""
.Ix "XmClipboardInquirePendingItems" "" "8~20" ""
.Ix "XmClipboardLock" "" "8~13" ""
.Ix "XmClipboardLock" "" "8~23" ""
.Ix "XmClipboardRegisterFormat" "" "8~13" ""
.Ix "XmClipboardRegisterFormat" "" "8~24" ""
.Ix "XmClipboardRetrieve" "" "8~13" ""
.Ix "XmClipboardRetrieve" "" "8~22" ""
.Ix "XmClipboardStartCopy" "" "8~13" ""
.Ix "XmClipboardStartCopy" "" "8~14" ""
.Ix "XmClipboardStartRetrieve" "" "8~13" ""
.Ix "XmClipboardStartRetrieve" "" "8~21" ""
.Ix "XmClipboardUndoCopy" "" "8~13" ""
.Ix "XmClipboardUndoCopy" "" "8~17" ""
.Ix "XmClipboardUnlock" "" "8~13" ""
.Ix "XmClipboardUnlock" "" "8~24" ""
.Ix "XmClipboardWithdrawFormat" "" "8~13" ""
.Ix "XmClipboardWithdrawFormat" "" "8~25" ""
.Ix "XmCommand" "" "2~15" ""
.Ix "XmCommand" "" "5~1" ""
.Ix "XmCommand" "" "5~5" ""
.Ix "XmCommandAppendValue" "" "5~7" ""
.Ix "XmCommandError" "" "5~7" ""
.Ix "XmCommandGetChild" "" "5~7" ""
.Ix "XmCommandSetValue" "" "5~7" ""
.Ix "XmConvertUnits" "" "8~30" ""
.Ix "XmCreateBulletinBoard" "" "5~4" ""
.Ix "XmCreateBulletinBoardDialog" "" "5~2" ""
.Ix "XmCreateCommand" "" "5~6" ""
.Ix "XmCreateDialogShell" "" "5~3" ""
.Ix "XmCreateErrorDialog" "" "2~14" ""
.Ix "XmCreateErrorDialog" "" "4~1" ""
.Ix "XmCreateErrorDialog" "" "5~2" ""
.Ix "XmCreateErrorDialog" "" "5~13" ""
.Ix "XmCreateFileSelectionBox" "" "5~8" ""
.Ix "XmCreateFileSelectionDialog" "" "5~2" ""
.Ix "XmCreateForm" "" "5~10" ""
.Ix "XmCreateFormDialog" "" "5~2" ""
.Ix "XmCreateInformationDialog" "" "2~14" ""
.Ix "XmCreateInformationDialog" "" "5~2" ""
.Ix "XmCreateInformationDialog" "" "5~13" ""
.Ix "XmCreateLabel" "" "2~19" ""
.Ix "XmCreateList" "" "7~2" ""
.Ix "XmCreateMenuBar" "" "6~2" ""
.Ix "XmCreateMenuBar" "" "6~10" ""
.Ix "XmCreateMessageBox" "" "5~12" ""
.Ix "XmCreateMessageDialog" "" "2~14" ""
.Ix "XmCreateMessageDialog" "" "5~13" ""
.Ix "XmCreateOptionMenu" "" "6~2" ""
.Ix "XmCreateOptionMenu" "" "6~19" ""
.Ix "XmCreateOptionMenu" "" "6~20" ""
.Ix "XmCreatePopupMenu" "" "6~2" ""
.Ix "XmCreatePopupMenu" "" "6~6" ""
.Ix "XmCreatePromptDialog" "" "5~2" ""
.Ix "XmCreatePulldownMenu" "" "6~2" ""
.Ix "XmCreatePulldownMenu" "" "6~11" ""
.Ix "XmCreatePulldownMenu" "" "6~16" ""
.Ix "XmCreatePushButton" "" "8~12" ""
.Ix "XmCreateQuestionDialog" "" "2~14" ""
.Ix "XmCreateQuestionDialog" "" "5~3" ""
.Ix "XmCreateQuestionDialog" "" "5~13" ""
.Ix "XmCreateRadioBox" "" "6~2" ""
.Ix "XmCreateRowColumn" "" "7~11" ""
.Ix "XmCreateScrolledList" "" "7~2" ""
.Ix "XmCreateScrolledText" "" "7~15" ""
.Ix "XmCreateSelectionBox" "" "5~14" ""
.Ix "XmCreateSelectionBoxDialog" "" "5~15" ""
.Ix "XmCreateSelectionDialog" "" "5~3" ""
.Ix "XmCreateSimpleCheckBox" "" "6~2" ""
.Ix "XmCreateSimpleMenuBar" "" "6~2" ""
.Ix "XmCreateSimpleOptionMenu" "" "6~2" ""
.Ix "XmCreateSimplePopupMenu" "" "6~2" ""
.Ix "XmCreateSimplePulldownMenu" "" "6~2" ""
.Ix "XmCreateSimpleRadioBox" "" "6~2" ""
.Ix "XmCreateText" "" "7~15" ""
.Ix "XmCreateWarningDialog" "" "2~14" ""
.Ix "XmCreateWarningDialog" "" "5~3" ""
.Ix "XmCreateWarningDialog" "" "5~13" ""
.Ix "XmCreateWorkArea" "" "6~2" ""
.Ix "XmCreateWorkingDialog" "" "2~14" ""
.Ix "XmCreateWorkingDialog" "" "5~3" ""
.Ix "XmCreateWorkingDialog" "" "5~13" ""
.Ix "XmDestroyPixmap" "" "8~28" ""
.Ix "XmDialogShell" "" "2~4" ""
.Ix "XmDialogShell" "" "5~1" ""
.Ix "XmDialogShell" "" "5~3" ""
.Ix "XmDialogShell" "" "5~4" ""
.Ix "XmDrawingArea" "" "2~9" ""
.Ix "XmDrawnButton" "" "2~5" ""
.Ix "XmFileSelectionBox" "" "2~15" ""
.Ix "XmFileSelectionBox" "" "5~1" ""
.Ix "XmFileSelectionBox" "" "5~8" ""
.Ix "XmFontListAdd" "" "8~4" ""
.Ix "XmFontListAdd" "" "8~5" ""
.Ix "XmFontListCreate" "" "8~4" ""
.Ix "XmFontListCreate" "" "8~5" ""
.Ix "XmFontListFree" "" "8~4" ""
.Ix "XmFontListFree" "" "8~6" ""
.Ix "XmFontListFreeFontContext" "" "8~4" ""
.Ix "XmFontListGetNextFont" "" "8~4" ""
.Ix "XmFontListInitFontContext" "" "8~4" ""
.Ix "xmfonts" "" "3~15" ""
.Ix "XmForm" "" "2~15" ""
.Ix "XmForm" "" "5~1" ""
.Ix "XmForm" "" "5~9" ""
.Ix "XmFormCreateDialog" "" "5~10" ""
.Ix "XmFrame" "" "2~9" ""
.Ix "XmGadget" "" "2~17" ""
.Ix "XmGadget" "" "2~18" ""
.Ix "XmGetMenuCursor" "" "6~24" ""
.Ix "XmGetPixmap" "" "8~28" ""
.Ix "XmInstallImage" "" "8~27" ""
.Ix "XmInstallImage(3X)" "" "13~8" ""
.Ix "XmIsMotifWMRunning" "" "8~35" ""
.Ix "XmLabel" "" "2~5" ""
.Ix "XmLabelGadget" "" "2~18" ""
.Ix "XmList" "" "2~5" ""
.Ix "XmListAddItem" "" "7~2" ""
.Ix "XmListAddItem" "" "7~7" ""
.Ix "XmListAddItems" "" "7~2" ""
.Ix "XmListAddItemUnselected" "" "7~2" ""
.Ix "XmListDeleteAllItems" "" "7~2" ""
.Ix "XmListDeleteItem" "" "7~2" ""
.Ix "XmListDeleteItems" "" "7~2" ""
.Ix "XmListDeleteItemsPos" "" "7~2" ""
.Ix "XmListDeletePos" "" "7~2" ""
.Ix "XmListDeselectAllItems" "" "7~2" ""
.Ix "XmListDeselectItem" "" "7~2" ""
.Ix "XmListDeselectPos" "" "7~2" ""
.Ix "XmListGetMatchPos" "" "7~2" ""
.Ix "XmListGetSelectedPos" "" "7~2" ""
.Ix "XmListItemExists" "" "7~2" ""
.Ix "XmListItemPos" "" "7~2" ""
.Ix "XmListReplaceItems" "" "7~2" ""
.Ix "XmListReplaceItemsPos" "" "7~2" ""
.Ix "XmListSelectItem" "" "7~2" ""
.Ix "XmListSelectPos" "" "7~2" ""
.Ix "XmListSetAddMode" "" "7~2" ""
.Ix "XmListSetBottomItem" "" "7~2" ""
.Ix "XmListSetBottomPos" "" "7~2" ""
.Ix "XmListSetHorizPos" "" "7~2" ""
.Ix "XmListSetItem" "" "7~2" ""
.Ix "XmListSetPos" "" "7~2" ""
.Ix "XmMainWindow" "" "2~9" ""
.Ix "XmMainWindowSetAreas" "" "2~9" ""
.Ix "XmManager" "" "2~8" ""
.Ix "XmManager" "" "2~9" ""
.Ix "XmMenuShell" "" "2~4" ""
.Ix "XmMenuShell" "" "2~17" ""
.Ix "XmMenuShell" "" "6~3" ""
.Ix "XmMessageBox" "" "2~15" ""
.Ix "XmMessageBox" "" "5~1" ""
.Ix "XmMessageBox" "" "5~12" ""
.Ix "XmNmenuAccelerator" "" "6~8" ""
.Ix "XmNmenuCursor" "" "6~24" ""
.Ix "XmNmenuHelpWidget" "" "6~11" ""
.Ix "XmNmenuHistory" "" "6~19" ""
.Ix "XmNmenuPost" "" "6~8" ""
.Ix "XmNmenuPost" "" "6~13" ""
.Ix "XmNmenuPost" "" "6~21" ""
.Ix "XmNrowColumnType" "" "6~6" ""
.Ix "XmNrowColumnType" "" "6~10" ""
.Ix "XmNrowColumnType" "" "6~11" ""
.Ix "XmNSeparator" "" "2~7" ""
.Ix "XmNsubMenuId" "" "6~11" ""
.Ix "XmNsubMenuId" "" "6~16" ""
.Ix "XmOptionButtonWidget" "" "6~20" ""
.Ix "XmOptionLabelWidget" "" "6~20" ""
.Ix "XmPanedWindow" "" "2~13" ""
.Ix "XmPrimitive" "" "2~4" ""
.Ix "XmPushButton" "" "2~6" ""
.Ix "XmPushButton" "" "2~17" ""
.Ix "XmPushButtonGadget" "" "2~18" ""
.Ix "XmRemoveTabGroup" "" "9~2" ""
.Ix "XmRowColumn" "" "2~9" ""
.Ix "XmRowColumn" "" "6~3" ""
.Ix "XmScale" "" "2~10" ""
.Ix "XmScrollBar" "" "2~6" ""
.Ix "XmScrolledWindow" "" "2~11" ""
.Ix "XmSelectionBox" "" "2~15" ""
.Ix "XmSelectionBox" "" "5~1" ""
.Ix "XmSelectionBox" "" "5~5" ""
.Ix "XmSelectionBox" "" "5~14" ""
.Ix "XmSeparator" "" "2~17" ""
.Ix "XmSeparatorGadget" "" "2~18" ""
.Ix "XmSetMenuCursor" "" "6~24" ""
.Ix "XmStringBaseline" "" "8~4" ""
.Ix "XmStringBaseline" "" "8~6" ""
.Ix "XmStringByteCompare" "" "8~4" ""
.Ix "XmStringByteCompare" "" "8~6" ""
.Ix "XmStringCompare" "" "8~4" ""
.Ix "XmStringCompare" "" "8~6" ""
.Ix "XmStringConcat" "" "8~4" ""
.Ix "XmStringConcat" "" "8~6" ""
.Ix "XmStringCopy" "" "8~4" ""
.Ix "XmStringCopy" "" "8~7" ""
.Ix "XmStringCreate" "" "8~4" ""
.Ix "XmStringCreate" "" "8~7" ""
.Ix "XmStringCreateLtoR" "" "5~7" ""
.Ix "XmStringCreateLtoR" "" "5~13" ""
.Ix "XmStringCreateLtoR" "" "8~4" ""
.Ix "XmStringCreateLtoR" "" "8~7" ""
.Ix "XmStringCreateSimple" "" "8~4" ""
.Ix "XmStringDirectionCreate" "" "8~4" ""
.Ix "XmStringDirectionCreate" "" "8~7" ""
.Ix "XmStringDraw" "" "8~4" ""
.Ix "XmStringDraw" "" "8~7" ""
.Ix "XmStringDrawImage" "" "8~4" ""
.Ix "XmStringDrawImage" "" "8~8" ""
.Ix "XmStringDrawUnderline" "" "8~4" ""
.Ix "XmStringDrawUnderline" "" "8~8" ""
.Ix "XmStringEmpty" "" "8~4" ""
.Ix "XmStringEmpty" "" "8~8" ""
.Ix "XmStringExtent" "" "8~4" ""
.Ix "XmStringExtent" "" "8~9" ""
.Ix "XmStringFree" "" "8~4" ""
.Ix "XmStringFree" "" "8~9" ""
.Ix "XmStringFreeContext" "" "8~4" ""
.Ix "XmStringFreeContext" "" "8~9" ""
.Ix "XmStringGetLtoR" "" "8~4" ""
.Ix "XmStringGetLtoR" "" "8~9" ""
.Ix "XmStringGetNextComponent" "" "8~4" ""
.Ix "XmStringGetNextComponent" "" "8~9" ""
.Ix "XmStringGetNextSegment" "" "8~4" ""
.Ix "XmStringGetNextSegment" "" "8~10" ""
.Ix "XmStringHasSubstring" "" "8~4" ""
.Ix "XmStringHeight" "" "8~4" ""
.Ix "XmStringHeight" "" "8~10" ""
.Ix "XmStringInitContext" "" "8~4" ""
.Ix "XmStringInitContext" "" "8~10" ""
.Ix "XmStringLength" "" "8~4" ""
.Ix "XmStringLength" "" "8~10" ""
.Ix "XmStringLineCount" "" "8~4" ""
.Ix "XmStringLineCount" "" "8~10" ""
.Ix "XmStringNConcat" "" "8~4" ""
.Ix "XmStringNConcat" "" "8~11" ""
.Ix "XmStringNCopy" "" "8~4" ""
.Ix "XmStringNCopy" "" "8~11" ""
.Ix "XmStringPeekNextComponent" "" "8~4" ""
.Ix "XmStringPeekNextComponent" "" "8~11" ""
.Ix "XmStringSegmentCreate" "" "8~4" ""
.Ix "XmStringSegmentCreate" "" "8~11" ""
.Ix "XmStringSegmentCreate" "" "8~12" ""
.Ix "XmStringSeparatorCreate" "" "8~4" ""
.Ix "XmStringSeparatorCreate" "" "8~12" ""
.Ix "XmStringWidth" "" "8~4" ""
.Ix "XmStringWidth" "" "8~12" ""
.Ix "XmText" "" "2~7" ""
.Ix "XmTextClearSelection" "" "7~15" ""
.Ix "XmTextCopy" "" "7~15" ""
.Ix "XmTextCut" "" "7~15" ""
.Ix "XmTextField" "" "2~8" ""
.Ix "XmTextGetBaseline" "" "7~15" ""
.Ix "XmTextGetEditable" "" "7~15" ""
.Ix "XmTextGetInsertionPosition" "" "7~15" ""
.Ix "XmTextGetLastPosition" "" "7~15" ""
.Ix "XmTextGetMaxLength" "" "7~15" ""
.Ix "XmTextGetSelection" "" "7~15" ""
.Ix "XmTextGetSelectionPosition" "" "7~15" ""
.Ix "XmTextGetSource" "" "7~15" ""
.Ix "XmTextGetString" "" "7~15" ""
.Ix "XmTextGetTopCharacter" "" "7~15" ""
.Ix "XmTextInsert" "" "7~15" ""
.Ix "XmTextPaste" "" "7~15" ""
.Ix "XmTextPosToXY" "" "7~15" ""
.Ix "XmTextRemove" "" "7~15" ""
.Ix "XmTextReplace" "" "7~15" ""
.Ix "XmTextScroll" "" "7~15" ""
.Ix "XmTextSetAddMode" "" "7~15" ""
.Ix "XmTextSetEditable" "" "7~15" ""
.Ix "XmTextSetHighlight" "" "7~15" ""
.Ix "XmTextSetInsertionPosition" "" "7~15" ""
.Ix "XmTextSetMaxLength" "" "7~15" ""
.Ix "XmTextSetSelection" "" "7~15" ""
.Ix "XmTextSetSource" "" "7~15" ""
.Ix "XmTextSetString" "" "7~15" ""
.Ix "XmTextSetTopCharacter" "" "7~15" ""
.Ix "XmTextShowPosition" "" "7~15" ""
.Ix "XmTextXYToPos" "" "7~15" ""
.Ix "XmToggleButton" "" "2~8" ""
.Ix "XmToggleButton" "" "2~17" ""
.Ix "XmToggleButtonGadget" "" "2~19" ""
.Ix "XmUninstallImage" "" "8~28" ""
.Ix "XmVaCreateSimpleCheckBox" "" "6~2" ""
.Ix "XmVaCreateSimpleMenuBar" "" "6~2" ""
.Ix "XmVaCreateSimpleOptionMenu" "" "6~2" ""
.Ix "XmVaCreateSimplePopupMenu" "" "6~2" ""
.Ix "XmVaCreateSimplePulldownMenu" "" "6~2" ""
.Ix "XmVaCreateSimpleRadioBox" "" "6~2" ""
.Ix "XmVersion" "" "8~35" ""
.Ix "xrm" "" "13~1" ""
.Ix "XSendEvent" "" "12~10" ""
.Ix "XSetClassHint" "" "12~10" ""
.Ix "XSetCommand" "" "12~10" ""
.Ix "XSetInputFocus" "" "12~6" ""
.Ix "XSetTransientForHint" "" "12~10" ""
.Ix "XSetWMHints" "" "12~10" ""
.Ix "XSetWMIconName" "" "12~10" ""
.Ix "XSetWMNormalHints" "" "12~10" ""
.Ix "XStoreName" "" "12~10" ""
.Ix "Xt Intrinsics" "" "12~10" ""
.Ix "Xt Intrinsics" "" "1~1" ""
.Ix "Xt Intrinsics" "initializing" "3~1" ""
.Ix "Xt Intrinsics" "initializing" "3~4" ""
.Ix "XtAddCallback" "" "3~7" ""
.Ix "XtAddCallback" "" "3~15" ""
.Ix "XtAddCallback" "" "7~5" ""
.Ix "XtAddCallback" "Defined" "3~8" ""
.Ix "XtAddCallbacks" "" "3~8" ""
.Ix "XtAddCallbacks" "Defined" "3~8" ""
.Ix "XtAddEventHandler" "" "6~6" ""
.Ix "XtAppCreateShell" "" "12~1" ""
.Ix "XtAppCreateShell" "" "3~5" ""
.Ix "XtAppCreateShell" "" "3~17" ""
.Ix "XtAppCreateShell" "" "4~1" ""
.Ix "XtAppInitialize" "" "22~19" ""
.Ix "XtAppInitialize" "" "22~20" ""
.Ix "XtAppInitialize" "" "22~22" ""
.Ix "XtAppInitialize" "" "3~4" ""
.Ix "XtAppInitialize" "" "3~5" ""
.Ix "XtAppInitialize" "" "3~9" ""
.Ix "XtAppInitialize" "" "3~17" ""
.Ix "XtAppInitialize" "" "4~1" ""
.Ix "XtAppInitialize" "" "8~12" ""
.Ix "XtAppInitialize" "Defined" "3~5" ""
.Ix "XtAppMainLoop" "" "3~9" ""
.Ix "XtAppMainLoop" "" "8~12" ""
.Ix "XtArgVal" "" "3~14" ""
.Ix "XtCallbackProc" "" "3~7" ""
.Ix "XtCreateManagedWidget" "" "3~9" ""
.Ix "XtCreateManagedWidget" "" "3~15" ""
.Ix "XtCreateManagedWidget" "" "5~4" ""
.Ix "XtCreateManagedWidget" "" "5~11" ""
.Ix "XtCreatePopupShell" "" "5~3" ""
.Ix "XtCreateWidget" "" "3~15" ""
.Ix "XtCreateWidget" "" "5~4" ""
.Ix "XtCreateWidget" "" "5~6" ""
.Ix "XtCreateWidget" "" "5~8" ""
.Ix "XtCreateWidget" "" "5~10" ""
.Ix "XtCreateWidget" "" "5~12" ""
.Ix "XtCreateWidget" "" "5~14" ""
.Ix "XtCreateWidget" "" "7~2" ""
.Ix "XtCreateWidget" "" "7~10" ""
.Ix "XtCreateWidget" "" "7~15" ""
.Ix "XtGetValues" "" "3~15" ""
.Ix "XtManageChild" "" "22~19" ""
.Ix "XtManageChild" "" "3~9" ""
.Ix "XtManageChild" "" "5~4" ""
.Ix "XtManageChild" "" "8~12" ""
.Ix "XtManageChildren" "" "3~15" ""
.Ix "XtNumber" "" "3~9" ""
.Ix "XtNumber" "" "3~14" ""
.Ix "XtOpenDisplay" "" "3~5" ""
.Ix "XtOpenDisplay" "" "3~17" ""
.Ix "XTranslateCoordinates" "" "12~6" ""
.Ix "XtRealizeWidget" "" "22~19" ""
.Ix "XtRealizeWidget" "" "3~9" ""
.Ix "XtRealizeWidget" "" "8~12" ""
.Ix "XtRealizeWidget" "Defined" "3~10" ""
.Ix "XtSetArg" "" "3~6" ""
.Ix "XtSetArg" "" "5~11" ""
.Ix "XtSetArg" "" "8~12" ""
.Ix "XtSetValues" "" "3~15" ""
.Ix "XtToolkitInitialize" "" "3~5" ""
.Ix "XtToolkitInitialize" "" "3~17" ""
.Iy
.Ix "~/" "" "13~3" ""
...\"	index formatting macros
...\"
...\"     this simply restores one column text
.1C
