all: protocol library encoding

protocol: tbl protocol.mm | troff -mm -R150 -r08P -rW32P > protocol.lpt

library: tbl library.mm  | troff -mm -R150 -r08P -rW32P > library.lpt

encoding: tbl encoding.mm | troff -mm -R150 -r08P -rW32P > encoding.lpt
