.\"
.\" $Id: atoh.3,v 1.3 89/12/26 11:14:59 bww Exp $
.\"
.\" HISTORY
.\" $Log:	atoh.3,v $
.\" Revision 1.3  89/12/26  11:14:59  bww
.\" 	Revised for 2.6 MSD release.
.\" 	[89/12/25            bww]
.\" 
.\" 13-Nov-86  Andi Swimmer (andi) at Carnegie-Mellon University
.\"	Revised for 4.3.
.\"
.\" 05-Dec-79  Steven Shafer (sas) at Carnegie-Mellon University
.\"	Created.
.\"
.TH ATOH 3 12/5/79
.CM 1
.SH "NAME"
atoh, atoo \- convert ASCII to hexadecimal or octal
.SH "SYNOPSIS"
.B
unsigned int atoh (ap)
.br
.B
char *ap;
.sp
.B
unsigned int atoo (ap)
.br
.B
char *ap;
.SH "DESCRIPTION"
.I
Atoh
converts the string pointed to by
.I
ap,
representing an hexadecimal number, to an unsigned integer.
The string may contain leading blanks and tabs, and a string of
hexadecimal digits.
Conversion stops at the first character which is
not a valid hexadecimal digit.
The digits themselves include the characters "0" through "9",
"a" through "f", and "A" through "F".
.sp
.I
Atoo
converts the string pointed to by
.I
ap,
representing an octal number, to an unsigned integer.
The string may contain leading blanks and tabs, and a string of
octal digits.
Conversion stops at the first character which is
not a valid octal digit.
.SH "SEE ALSO"
.IR atof (3), 
.IR atoi (3), 
.IR atol (3), 
.SH "BUGS"
There is no provision for overflow.
Unary + is not accepted.
(Unary
- is not accepted, due to the interpretation of the numbers as unsigned.)
