# /usr/src/man/man3/Makefile

MDIR=	/usr/man/man3
SRCS=	abort.3 abs.3 abspath.3 alarm.3 asinh.3 assert.3 atof.3 atoh.3 \
	atot.3 bindresvport.3 boolarg.3 bstring.3 byteorder.3 chrarg.3 \
	ci.3 compat-sys5.3 concat.3 convert_ts_to_tv.3 crypt.3 ctime.3 \
	ctype.3 curses.3 dbm.3 del.3 directory.3 doublearg.3 ecvt.3 \
	editor.3 end.3 env_conn.3 env_copy_conn.3 env_del_port.3 \
	env_del_string.3 env_disconnect.3 env_get_port.3 env_get_string.3 \
	env_list.3 env_list_ports.3 env_list_strings.3 env_new_conn.3 \
	env_port.3 env_restrict_conn.3 env_set_port.3 env_set_ptlist.3 \
	env_set_stlist.3 env_set_string.3 env_string.3 erf.3 execl.3 exit.3 \
	exp.3 expand.3 fbufsize.3 fclose.3 fdate.3 ferror.3 fgetpass.3 \
	filecopy.3 floor.3 fmap.3 fold.3 fopen.3 fread.3 fremap.3 frexp.3 \
	fseek.3 getacent.3 getbool.3 getc.3 getchr.3 getdiskbyname.3 \
	getdouble.3 getenv.3 getfsent.3 getgrent.3 gethostbyname.3 getint.3 \
	getlogin.3 getmntent.3 getname.3 getnetent.3 getoct.3 getopt.3 \
	getpass.3 getprotoent.3 getpw.3 getpwent.3 getpwwho.3 getrpcent.3 \
	getrpcport.3 gets.3 getservent.3 getstr.3 getttyent.3 getusershell.3 \
	getwd.3 gtime.3 hardcrypt.3 hypot.3 ieee.3 inet.3 infnan.3 \
	initgroups.3 insque.3 intarg.3 intro.3 ipcx.3 j0.3 lgamma.3 \
	lib2648.3 mach_error.3 mach_error_string.3 mach_error_type.3 \
	mach_exception.3 mach_init.3 makepath.3 malloc.3 math.3 mktemp.3 \
	monitor.3 movefile.3 mp.3 ndbm.3 netname.3 netname_check_in.3 \
	netname_check_out.3 netname_look_up.3 netname_version.3 nice.3 \
	nlist.3 ns.3 nxtarg.3 octarg.3 oklogin.3 okpassword.3 openp.3 \
	parsedate.3 path.3 pathof.3 pause.3 perror.3 plot.3 popen.3 printf.3 \
	prstab.3 psignal.3 putc.3 puts.3 qsort.3 quit.3 rand.3 random.3 \
	rcmd.3 regex.3 regexp.3 resolver.3 rexec.3 run.3 salloc.3 scandir.3 \
	scanf.3 searchp.3 service_checkin.3 setbuf.3 setjmp.3 setuid.3 \
	siginterrupt.3 signal.3 sin.3 sindex.3 sinh.3 skipto.3 sleep.3 \
	slot_name.3 sqrt.3 srchscore.3 stablk.3 stabsearch.3 stdio.3 \
	stlmatch.3 strarg.3 strdup.3 string.3 stty.3 swab.3 syslog.3 \
	system.3 termcap.3 threads.3 time.3 times.3 ttyname.3 ualarm.3 \
	ungetc.3 usleep.3 utime.3 valloc.3 varargs.3 vlimit.3 vtimes.3 \
	wantread.3 wantwrite.3 warnlogin.3 

LINKS=X	edata.3 etext.3 j1.3 jn.3 y0.3 y1.3 yn.3 ns_addr.3 \
	ns_ntoa.3 acos.3 asin.3 atan.3 atan2.3 atoi.3 atol.3 \
	cos.3 dbm_clearerr.3 dbm_close.3 dbm_delete.3 dbm_error.3 \
	dbm_fetch.3 dbm_firstkey.3 dbm_nextkey.3 dbm_open.3 \
	dbm_store.3 dbminit.3 delete.3 erfc.3 expm1.3 fcvt.3 \
	fetch.3 firstkey.3 gcvt.3 log.3 log10.3 log1p.3 \
	nextkey.3 pow.3 rresvport.3 ruserok.3 store.3 tan.3 \
	exec.3 addr.3 arc.3 asctime.3 cbrt.3 circle.3 cont.3 \
	copysign.3 cosh.3 drem.3 encrypt.3 erase.3 execle.3 \
	execlp.3 exect.3 execv.3 execve.3 execvp.3 fgetc.3 \
	fgets.3 finite.3 fputc.3 fputs.3 ftime.3 getchar.3 \
	getw.3 gmtime.3 gtty.3 inet_addr.3 inet_lnaof.3 \
	inet_makeaddr.3 inet_netof.3 inet_network.3 inet_ntoa.3 \
	isalnum.3 isalpha.3 isascii.3 iscntrl.3 isdigit.3 \
	islower.3 isprint.3 ispunct.3 isspace.3 isupper.3 \
	isxdigit.3 label.3 ldexp.3 line.3 linemod.3 localtime.3 \
	logb.3 modf.3 move.3 network.3 ntoa.3 openpl.3 \
	pclose.3 point.3 putchar.3 putw.3 re_comp.3 re_exec.3 \
	regcomp.3 regexec.3 regsub.3 regerror.3 scalb.3 setkey.3 \
	space.3 srand.3 tanh.3 timezone.3 tzset.3 toascii.3 \
	tolower.3 toupper.3 _longjmp.3 _setjmp.3 acosh.3 alloca.3 \
	atanh.3 cabs.3 calloc.3 ceil.3 closelog.3 errlist.3 \
	fabs.3 fdopen.3 free.3 freopen.3 fscanf.3 ftell.3 \
	fwrite.3 index.3 initstate.3 longjmp.3 openlog.3 realloc.3 \
	remque.3 rewind.3 rindex.3 setegid.3 seteuid.3 setgid.3 \
	setlogmask.3 setrgid.3 setruid.3 setstate.3 srandom.3 \
	sscanf.3 strcat.3 strcmp.3 strcpy.3 strlen.3 strncat.3 \
	strncmp.3 strcasecmp.3 strncasecmp.3 strncpy.3 sys.3 \
	sys_errlist.3 sys_nerr.3 mkstemp.3 rint.3 setenv.3 \
	putenv.3 unsetenv.3 alphasort.3 bcmp.3 bcopy.3 bzero.3 \
	clearerr.3 feof.3 fflush.3 ffs.3 fileno.3 fprintf.3 isatty.3 \
	moncontrol.3 monstartup.3 setbuffer.3 setlinebuf.3 \
	sprintf.3 sys_siglist.3 ttyslot.3 gamma.3 endfsent.3 \
	endgrent.3 endpwent.3 getfsfile.3 getfsspec.3 getfstype.3 \
	getgrgid.3 getgrnam.3 getpwnam.3 getpwuid.3 setfsent.3 \
	setgrent.3 setgrfile.3 setpwent.3 setpwfile.3 tgetent.3 \
	tgetflag.3 tgetnum.3 tgetstr.3 tgoto.3 tputs.3 closedir.3 \
	dirfd.3 endttyent.3 getttynam.3 opendir.3 readdir.3 \
	rewinddir.3 seekdir.3 setttyent.3 telldir.3 endnetent.3 \
	getnetbyaddr.3 getnetbyname.3 htonl.3 htons.3 ntohl.3 \
	ntohs.3 setnetent.3 endservent.3 getservbyname.3 \
	getservbyport.3 setservent.3 endprotoent.3 endusershell.3 \
	getprotobyname.3 getprotobynumber.3 setprotoent.3 \
	setusershell.3 endhostent.3 gethostbyaddr.3 sethostent.3 \
	sethostfile.3 gethostent.3 memccpy.3 memchr.3 memcmp.3 \
	memcpy.3 memset.3 strchr.3 strcspn.3 strrchr.3 strspn.3 \
	strtok.3 tmpnam.3 tmpfile.3 tempnam.3

all:	FRC

clean:	FRC

install: FRC
	-[ -d ${DESTDIR}${MDIR} ] || mkdir ${DESTDIR}${MDIR}
	-chmod 755 ${DESTDIR}${MDIR}
	-chown root.bin ${DESTDIR}${MDIR}
	cd ${DESTDIR}${MDIR}; rm -f ${SRCS} ${LINKS}
	install -c -o bin -g bin -m 444 ${SRCS} ${DESTDIR}${MDIR}
	ln -s end.3 ${DESTDIR}${MDIR}/edata.3
	ln -s end.3 ${DESTDIR}${MDIR}/etext.3
	ln -s j0.3 ${DESTDIR}${MDIR}/j1.3
	ln -s j0.3 ${DESTDIR}${MDIR}/jn.3
	ln -s j0.3 ${DESTDIR}${MDIR}/y0.3
	ln -s j0.3 ${DESTDIR}${MDIR}/y1.3
	ln -s j0.3 ${DESTDIR}${MDIR}/yn.3
	ln -s ns.3 ${DESTDIR}${MDIR}/ns_addr.3
	ln -s ns.3 ${DESTDIR}${MDIR}/ns_ntoa.3
	ln -s sin.3 ${DESTDIR}${MDIR}/acos.3
	ln -s sin.3 ${DESTDIR}${MDIR}/asin.3
	ln -s sin.3 ${DESTDIR}${MDIR}/atan.3
	ln -s sin.3 ${DESTDIR}${MDIR}/atan2.3
	ln -s atof.3 ${DESTDIR}${MDIR}/atoi.3
	ln -s atof.3 ${DESTDIR}${MDIR}/atol.3
	ln -s sin.3 ${DESTDIR}${MDIR}/cos.3
	ln -s ndbm.3 ${DESTDIR}${MDIR}/dbm_clearerr.3
	ln -s ndbm.3 ${DESTDIR}${MDIR}/dbm_close.3
	ln -s ndbm.3 ${DESTDIR}${MDIR}/dbm_delete.3
	ln -s ndbm.3 ${DESTDIR}${MDIR}/dbm_error.3
	ln -s ndbm.3 ${DESTDIR}${MDIR}/dbm_fetch.3
	ln -s ndbm.3 ${DESTDIR}${MDIR}/dbm_firstkey.3
	ln -s ndbm.3 ${DESTDIR}${MDIR}/dbm_nextkey.3
	ln -s ndbm.3 ${DESTDIR}${MDIR}/dbm_open.3
	ln -s ndbm.3 ${DESTDIR}${MDIR}/dbm_store.3
	ln -s dbm.3 ${DESTDIR}${MDIR}/dbminit.3
	ln -s dbm.3 ${DESTDIR}${MDIR}/delete.3
	ln -s erf.3 ${DESTDIR}${MDIR}/erfc.3
	ln -s exp.3 ${DESTDIR}${MDIR}/expm1.3
	ln -s ecvt.3 ${DESTDIR}${MDIR}/fcvt.3
	ln -s dbm.3 ${DESTDIR}${MDIR}/fetch.3
	ln -s dbm.3 ${DESTDIR}${MDIR}/firstkey.3
	ln -s ecvt.3 ${DESTDIR}${MDIR}/gcvt.3
	ln -s exp.3 ${DESTDIR}${MDIR}/log.3
	ln -s exp.3 ${DESTDIR}${MDIR}/log10.3
	ln -s exp.3 ${DESTDIR}${MDIR}/log1p.3
	ln -s dbm.3 ${DESTDIR}${MDIR}/nextkey.3
	ln -s exp.3 ${DESTDIR}${MDIR}/pow.3
	ln -s rcmd.3 ${DESTDIR}${MDIR}/rresvport.3
	ln -s rcmd.3 ${DESTDIR}${MDIR}/ruserok.3
	ln -s dbm.3 ${DESTDIR}${MDIR}/store.3
	ln -s sin.3 ${DESTDIR}${MDIR}/tan.3
	ln -s execl.3 ${DESTDIR}${MDIR}/exec.3
	ln -s inet.3 ${DESTDIR}${MDIR}/addr.3
	ln -s plot.3 ${DESTDIR}${MDIR}/arc.3
	ln -s ctime.3 ${DESTDIR}${MDIR}/asctime.3
	ln -s sqrt.3 ${DESTDIR}${MDIR}/cbrt.3
	ln -s plot.3 ${DESTDIR}${MDIR}/circle.3
	ln -s plot.3 ${DESTDIR}${MDIR}/cont.3
	ln -s ieee.3 ${DESTDIR}${MDIR}/copysign.3
	ln -s sinh.3 ${DESTDIR}${MDIR}/cosh.3
	ln -s ieee.3 ${DESTDIR}${MDIR}/drem.3
	ln -s crypt.3 ${DESTDIR}${MDIR}/encrypt.3
	ln -s plot.3 ${DESTDIR}${MDIR}/erase.3
	ln -s execl.3 ${DESTDIR}${MDIR}/execle.3
	ln -s execl.3 ${DESTDIR}${MDIR}/execlp.3
	ln -s execl.3 ${DESTDIR}${MDIR}/exect.3
	ln -s execl.3 ${DESTDIR}${MDIR}/execv.3
	ln -s execl.3 ${DESTDIR}${MDIR}/execve.3
	ln -s execl.3 ${DESTDIR}${MDIR}/execvp.3
	ln -s getc.3 ${DESTDIR}${MDIR}/fgetc.3
	ln -s gets.3 ${DESTDIR}${MDIR}/fgets.3
	ln -s ieee.3 ${DESTDIR}${MDIR}/finite.3
	ln -s putc.3 ${DESTDIR}${MDIR}/fputc.3
	ln -s puts.3 ${DESTDIR}${MDIR}/fputs.3
	ln -s time.3 ${DESTDIR}${MDIR}/ftime.3
	ln -s getc.3 ${DESTDIR}${MDIR}/getchar.3
	ln -s getc.3 ${DESTDIR}${MDIR}/getw.3
	ln -s ctime.3 ${DESTDIR}${MDIR}/gmtime.3
	ln -s stty.3 ${DESTDIR}${MDIR}/gtty.3
	ln -s inet.3 ${DESTDIR}${MDIR}/inet_addr.3
	ln -s inet.3 ${DESTDIR}${MDIR}/inet_lnaof.3
	ln -s inet.3 ${DESTDIR}${MDIR}/inet_makeaddr.3
	ln -s inet.3 ${DESTDIR}${MDIR}/inet_netof.3
	ln -s inet.3 ${DESTDIR}${MDIR}/inet_network.3
	ln -s inet.3 ${DESTDIR}${MDIR}/inet_ntoa.3
	ln -s ctype.3 ${DESTDIR}${MDIR}/isalnum.3
	ln -s ctype.3 ${DESTDIR}${MDIR}/isalpha.3
	ln -s ctype.3 ${DESTDIR}${MDIR}/isascii.3
	ln -s ctype.3 ${DESTDIR}${MDIR}/iscntrl.3
	ln -s ctype.3 ${DESTDIR}${MDIR}/isdigit.3
	ln -s ctype.3 ${DESTDIR}${MDIR}/islower.3
	ln -s ctype.3 ${DESTDIR}${MDIR}/isprint.3
	ln -s ctype.3 ${DESTDIR}${MDIR}/ispunct.3
	ln -s ctype.3 ${DESTDIR}${MDIR}/isspace.3
	ln -s ctype.3 ${DESTDIR}${MDIR}/isupper.3
	ln -s ctype.3 ${DESTDIR}${MDIR}/isxdigit.3
	ln -s plot.3 ${DESTDIR}${MDIR}/label.3
	ln -s frexp.3 ${DESTDIR}${MDIR}/ldexp.3
	ln -s plot.3 ${DESTDIR}${MDIR}/line.3
	ln -s plot.3 ${DESTDIR}${MDIR}/linemod.3
	ln -s ctime.3 ${DESTDIR}${MDIR}/localtime.3
	ln -s ieee.3 ${DESTDIR}${MDIR}/logb.3
	ln -s frexp.3 ${DESTDIR}${MDIR}/modf.3
	ln -s plot.3 ${DESTDIR}${MDIR}/move.3
	ln -s inet.3 ${DESTDIR}${MDIR}/network.3
	ln -s inet.3 ${DESTDIR}${MDIR}/ntoa.3
	ln -s plot.3 ${DESTDIR}${MDIR}/openpl.3
	ln -s popen.3 ${DESTDIR}${MDIR}/pclose.3
	ln -s plot.3 ${DESTDIR}${MDIR}/point.3
	ln -s putc.3 ${DESTDIR}${MDIR}/putchar.3
	ln -s putc.3 ${DESTDIR}${MDIR}/putw.3
	ln -s regex.3 ${DESTDIR}${MDIR}/re_comp.3
	ln -s regex.3 ${DESTDIR}${MDIR}/re_exec.3
	ln -s regexp.3 ${DESTDIR}${MDIR}/regcomp.3
	ln -s regexp.3 ${DESTDIR}${MDIR}/regexec.3
	ln -s regexp.3 ${DESTDIR}${MDIR}/regsub.3
	ln -s regexp.3 ${DESTDIR}${MDIR}/regerror.3
	ln -s ieee.3 ${DESTDIR}${MDIR}/scalb.3
	ln -s crypt.3 ${DESTDIR}${MDIR}/setkey.3
	ln -s plot.3 ${DESTDIR}${MDIR}/space.3
	ln -s rand.3 ${DESTDIR}${MDIR}/srand.3
	ln -s sinh.3 ${DESTDIR}${MDIR}/tanh.3
	ln -s ctime.3 ${DESTDIR}${MDIR}/timezone.3
	ln -s ctime.3 ${DESTDIR}${MDIR}/tzset.3
	ln -s ctype.3 ${DESTDIR}${MDIR}/toascii.3
	ln -s ctype.3 ${DESTDIR}${MDIR}/tolower.3
	ln -s ctype.3 ${DESTDIR}${MDIR}/toupper.3
	ln -s setjmp.3 ${DESTDIR}${MDIR}/_longjmp.3
	ln -s setjmp.3 ${DESTDIR}${MDIR}/_setjmp.3
	ln -s asinh.3 ${DESTDIR}${MDIR}/acosh.3
	ln -s malloc.3 ${DESTDIR}${MDIR}/alloca.3
	ln -s asinh.3 ${DESTDIR}${MDIR}/atanh.3
	ln -s hypot.3 ${DESTDIR}${MDIR}/cabs.3
	ln -s malloc.3 ${DESTDIR}${MDIR}/calloc.3
	ln -s floor.3 ${DESTDIR}${MDIR}/ceil.3
	ln -s syslog.3 ${DESTDIR}${MDIR}/closelog.3
	ln -s perror.3 ${DESTDIR}${MDIR}/errlist.3
	ln -s floor.3 ${DESTDIR}${MDIR}/fabs.3
	ln -s fopen.3 ${DESTDIR}${MDIR}/fdopen.3
	ln -s malloc.3 ${DESTDIR}${MDIR}/free.3
	ln -s fopen.3 ${DESTDIR}${MDIR}/freopen.3
	ln -s scanf.3 ${DESTDIR}${MDIR}/fscanf.3
	ln -s fseek.3 ${DESTDIR}${MDIR}/ftell.3
	ln -s fread.3 ${DESTDIR}${MDIR}/fwrite.3
	ln -s string.3 ${DESTDIR}${MDIR}/index.3
	ln -s random.3 ${DESTDIR}${MDIR}/initstate.3
	ln -s setjmp.3 ${DESTDIR}${MDIR}/longjmp.3
	ln -s syslog.3 ${DESTDIR}${MDIR}/openlog.3
	ln -s malloc.3 ${DESTDIR}${MDIR}/realloc.3
	ln -s insque.3 ${DESTDIR}${MDIR}/remque.3
	ln -s fseek.3 ${DESTDIR}${MDIR}/rewind.3
	ln -s string.3 ${DESTDIR}${MDIR}/rindex.3
	ln -s setuid.3 ${DESTDIR}${MDIR}/setegid.3
	ln -s setuid.3 ${DESTDIR}${MDIR}/seteuid.3
	ln -s setuid.3 ${DESTDIR}${MDIR}/setgid.3
	ln -s syslog.3 ${DESTDIR}${MDIR}/setlogmask.3
	ln -s setuid.3 ${DESTDIR}${MDIR}/setrgid.3
	ln -s setuid.3 ${DESTDIR}${MDIR}/setruid.3
	ln -s random.3 ${DESTDIR}${MDIR}/setstate.3
	ln -s random.3 ${DESTDIR}${MDIR}/srandom.3
	ln -s scanf.3 ${DESTDIR}${MDIR}/sscanf.3
	ln -s string.3 ${DESTDIR}${MDIR}/strcat.3
	ln -s string.3 ${DESTDIR}${MDIR}/strcmp.3
	ln -s string.3 ${DESTDIR}${MDIR}/strcpy.3
	ln -s string.3 ${DESTDIR}${MDIR}/strlen.3
	ln -s string.3 ${DESTDIR}${MDIR}/strncat.3
	ln -s string.3 ${DESTDIR}${MDIR}/strncmp.3
	ln -s string.3 ${DESTDIR}${MDIR}/strcasecmp.3
	ln -s string.3 ${DESTDIR}${MDIR}/strncasecmp.3
	ln -s string.3 ${DESTDIR}${MDIR}/strncpy.3
	ln -s perror.3 ${DESTDIR}${MDIR}/sys.3
	ln -s perror.3 ${DESTDIR}${MDIR}/sys_errlist.3
	ln -s perror.3 ${DESTDIR}${MDIR}/sys_nerr.3
	ln -s mktemp.3 ${DESTDIR}${MDIR}/mkstemp.3
	ln -s floor.3 ${DESTDIR}${MDIR}/rint.3
	ln -s getenv.3 ${DESTDIR}${MDIR}/setenv.3
	ln -s getenv.3 ${DESTDIR}${MDIR}/putenv.3
	ln -s getenv.3 ${DESTDIR}${MDIR}/unsetenv.3
	ln -s scandir.3 ${DESTDIR}${MDIR}/alphasort.3
	ln -s bstring.3 ${DESTDIR}${MDIR}/bcmp.3
	ln -s bstring.3 ${DESTDIR}${MDIR}/bcopy.3
	ln -s bstring.3 ${DESTDIR}${MDIR}/bzero.3
	ln -s ferror.3 ${DESTDIR}${MDIR}/clearerr.3
	ln -s ferror.3 ${DESTDIR}${MDIR}/feof.3
	ln -s fclose.3 ${DESTDIR}${MDIR}/fflush.3
	ln -s bstring.3 ${DESTDIR}${MDIR}/ffs.3
	ln -s ferror.3 ${DESTDIR}${MDIR}/fileno.3
	ln -s printf.3 ${DESTDIR}${MDIR}/fprintf.3
	ln -s ttyname.3 ${DESTDIR}${MDIR}/isatty.3
	ln -s monitor.3 ${DESTDIR}${MDIR}/moncontrol.3
	ln -s monitor.3 ${DESTDIR}${MDIR}/monstartup.3
	ln -s setbuf.3 ${DESTDIR}${MDIR}/setbuffer.3
	ln -s setbuf.3 ${DESTDIR}${MDIR}/setlinebuf.3
	ln -s printf.3 ${DESTDIR}${MDIR}/sprintf.3
	ln -s psignal.3 ${DESTDIR}${MDIR}/sys_siglist.3
	ln -s ttyname.3 ${DESTDIR}${MDIR}/ttyslot.3
	ln -s lgamma.3 ${DESTDIR}${MDIR}/gamma.3
	ln -s getfsent.3 ${DESTDIR}${MDIR}/endfsent.3
	ln -s getgrent.3 ${DESTDIR}${MDIR}/endgrent.3
	ln -s getpwent.3 ${DESTDIR}${MDIR}/endpwent.3
	ln -s getfsent.3 ${DESTDIR}${MDIR}/getfsfile.3
	ln -s getfsent.3 ${DESTDIR}${MDIR}/getfsspec.3
	ln -s getfsent.3 ${DESTDIR}${MDIR}/getfstype.3
	ln -s getgrent.3 ${DESTDIR}${MDIR}/getgrgid.3
	ln -s getgrent.3 ${DESTDIR}${MDIR}/getgrnam.3
	ln -s getpwent.3 ${DESTDIR}${MDIR}/getpwnam.3
	ln -s getpwent.3 ${DESTDIR}${MDIR}/getpwuid.3
	ln -s getfsent.3 ${DESTDIR}${MDIR}/setfsent.3
	ln -s getgrent.3 ${DESTDIR}${MDIR}/setgrent.3
	ln -s getgrent.3 ${DESTDIR}${MDIR}/setgrfile.3
	ln -s getpwent.3 ${DESTDIR}${MDIR}/setpwent.3
	ln -s getpwent.3 ${DESTDIR}${MDIR}/setpwfile.3
	ln -s termcap.3 ${DESTDIR}${MDIR}/tgetent.3
	ln -s termcap.3 ${DESTDIR}${MDIR}/tgetflag.3
	ln -s termcap.3 ${DESTDIR}${MDIR}/tgetnum.3
	ln -s termcap.3 ${DESTDIR}${MDIR}/tgetstr.3
	ln -s termcap.3 ${DESTDIR}${MDIR}/tgoto.3
	ln -s termcap.3 ${DESTDIR}${MDIR}/tputs.3
	ln -s directory.3 ${DESTDIR}${MDIR}/closedir.3
	ln -s directory.3 ${DESTDIR}${MDIR}/dirfd.3
	ln -s getttyent.3 ${DESTDIR}${MDIR}/endttyent.3
	ln -s getttyent.3 ${DESTDIR}${MDIR}/getttynam.3
	ln -s directory.3 ${DESTDIR}${MDIR}/opendir.3
	ln -s directory.3 ${DESTDIR}${MDIR}/readdir.3
	ln -s directory.3 ${DESTDIR}${MDIR}/rewinddir.3
	ln -s directory.3 ${DESTDIR}${MDIR}/seekdir.3
	ln -s getttyent.3 ${DESTDIR}${MDIR}/setttyent.3
	ln -s directory.3 ${DESTDIR}${MDIR}/telldir.3
	ln -s getnetent.3 ${DESTDIR}${MDIR}/endnetent.3
	ln -s getnetent.3 ${DESTDIR}${MDIR}/getnetbyaddr.3
	ln -s getnetent.3 ${DESTDIR}${MDIR}/getnetbyname.3
	ln -s byteorder.3 ${DESTDIR}${MDIR}/htonl.3
	ln -s byteorder.3 ${DESTDIR}${MDIR}/htons.3
	ln -s byteorder.3 ${DESTDIR}${MDIR}/ntohl.3
	ln -s byteorder.3 ${DESTDIR}${MDIR}/ntohs.3
	ln -s getnetent.3 ${DESTDIR}${MDIR}/setnetent.3
	ln -s getservent.3 ${DESTDIR}${MDIR}/endservent.3
	ln -s getservent.3 ${DESTDIR}${MDIR}/getservbyname.3
	ln -s getservent.3 ${DESTDIR}${MDIR}/getservbyport.3
	ln -s getservent.3 ${DESTDIR}${MDIR}/setservent.3
	ln -s getprotoent.3 ${DESTDIR}${MDIR}/endprotoent.3
	ln -s getusershell.3 ${DESTDIR}${MDIR}/endusershell.3
	ln -s getprotoent.3 ${DESTDIR}${MDIR}/getprotobyname.3
	ln -s getprotoent.3 ${DESTDIR}${MDIR}/getprotobynumber.3
	ln -s getprotoent.3 ${DESTDIR}${MDIR}/setprotoent.3
	ln -s getusershell.3 ${DESTDIR}${MDIR}/setusershell.3
	ln -s gethostbyname.3 ${DESTDIR}${MDIR}/endhostent.3
	ln -s gethostbyname.3 ${DESTDIR}${MDIR}/gethostbyaddr.3
	ln -s gethostbyname.3 ${DESTDIR}${MDIR}/sethostent.3
	ln -s gethostbyname.3 ${DESTDIR}${MDIR}/sethostfile.3
	ln -s gethostbyname.3 ${DESTDIR}${MDIR}/gethostent.3
	ln -s compat-sys5.3 ${DESTDIR}${MDIR}/memccpy.3
	ln -s compat-sys5.3 ${DESTDIR}${MDIR}/memchr.3
	ln -s compat-sys5.3 ${DESTDIR}${MDIR}/memcmp.3
	ln -s compat-sys5.3 ${DESTDIR}${MDIR}/memcpy.3
	ln -s compat-sys5.3 ${DESTDIR}${MDIR}/memset.3
	ln -s compat-sys5.3 ${DESTDIR}${MDIR}/strchr.3
	ln -s compat-sys5.3 ${DESTDIR}${MDIR}/strcspn.3
	ln -s compat-sys5.3 ${DESTDIR}${MDIR}/strrchr.3
	ln -s compat-sys5.3 ${DESTDIR}${MDIR}/strspn.3
	ln -s compat-sys5.3 ${DESTDIR}${MDIR}/strtok.3
	ln -s compat-sys5.3 ${DESTDIR}${MDIR}/tmpnam.3
	ln -s compat-sys5.3 ${DESTDIR}${MDIR}/tmpfile.3
	ln -s compat-sys5.3 ${DESTDIR}${MDIR}/tempnam.3

FRC:
