.\"
.\" $Id: salloc.3,v 1.3 89/12/26 11:21:39 bww Exp $
.\"
.\" HISTORY
.\" $Log:	salloc.3,v $
.\" Revision 1.3  89/12/26  11:21:39  bww
.\" 	Revised for 2.6 MSD release.
.\" 	[89/12/25            bww]
.\" 
.\" 13-Nov-86  Andi Swimmer (andi) at Carnegie-Mellon University
.\"	Revised for 4.3.
.\"
.\" 08-Apr-86  Steven Shafer (sas) at Carnegie-Mellon University
.\"	Created.
.\"
.TH SALLOC 3 4/8/86
.CM 4
.SH "NAME"
salloc \- allocate and copy string
.SH "SYNOPSIS"
.B
char *salloc (original)
.br
.B
char *original;
.SH "DESCRIPTION"
.I Salloc
will create a copy of a string by allocating a new block of storage,
copying the argument into the new block, and returning a pointer
to the new string.
.SH "SEE ALSO"
malloc(3), string(3)
.SH "DIAGNOSTICS"
Returns 0 if the
.I malloc
fails (not enough storage available).
.SH "BUGS"
