# /usr/src/usr.lib/sendmail/lib/Makefile for MacMach

ALL=	sendmail.hf
SRCS=	sendmail.hf

all:	FRC

install: FRC
	install -c -o bin -g bin -m 444 sendmail.hf ${DESTDIR}/usr/lib/sendmail.hf

clean:	FRC

FRC:
