/*
**	This file is automatically generated.  Do not edit it by hand.
**/

/*
 * Bit vectors for each reason. The entries in the vector correspond
 * to each class.
 */

/* sym_k_MrmNcreateCallback_reason */
static unsigned char reason_class_vec1[] =
  {
  _BIT_MASK(sym_k_XmArrowButton_object) |
  _BIT_MASK(sym_k_XmArrowButtonGadget_object) |
  _BIT_MASK(sym_k_XmBulletinBoard_object) |
  _BIT_MASK(sym_k_XmBulletinBoardDialog_object) |
  _BIT_MASK(sym_k_XmCascadeButton_object) |
  _BIT_MASK(sym_k_XmCascadeButtonGadget_object) |
  _BIT_MASK(sym_k_XmCommand_object) |
  0, _BIT_MASK(sym_k_XmDrawingArea_object) |
  _BIT_MASK(sym_k_XmDrawnButton_object) |
  _BIT_MASK(sym_k_XmErrorDialog_object) |
  _BIT_MASK(sym_k_XmFileSelectionBox_object) |
  _BIT_MASK(sym_k_XmFileSelectionDialog_object) |
  _BIT_MASK(sym_k_XmForm_object) |
  _BIT_MASK(sym_k_XmFormDialog_object) |
  _BIT_MASK(sym_k_XmFrame_object) |
  0, _BIT_MASK(sym_k_XmInformationDialog_object) |
  _BIT_MASK(sym_k_XmLabel_object) |
  _BIT_MASK(sym_k_XmLabelGadget_object) |
  _BIT_MASK(sym_k_XmList_object) |
  _BIT_MASK(sym_k_XmMainWindow_object) |
  _BIT_MASK(sym_k_XmMenuBar_object) |
  _BIT_MASK(sym_k_XmMessageBox_object) |
  _BIT_MASK(sym_k_XmMessageDialog_object) |
  0, _BIT_MASK(sym_k_XmOptionMenu_object) |
  _BIT_MASK(sym_k_XmPanedWindow_object) |
  _BIT_MASK(sym_k_XmPopupMenu_object) |
  _BIT_MASK(sym_k_XmPromptDialog_object) |
  _BIT_MASK(sym_k_XmPulldownMenu_object) |
  _BIT_MASK(sym_k_XmPushButton_object) |
  _BIT_MASK(sym_k_XmPushButtonGadget_object) |
  _BIT_MASK(sym_k_XmQuestionDialog_object) |
  0, _BIT_MASK(sym_k_XmRadioBox_object) |
  _BIT_MASK(sym_k_XmRowColumn_object) |
  _BIT_MASK(sym_k_XmScale_object) |
  _BIT_MASK(sym_k_XmScrollBar_object) |
  _BIT_MASK(sym_k_XmScrolledList_object) |
  _BIT_MASK(sym_k_XmScrolledText_object) |
  _BIT_MASK(sym_k_XmScrolledWindow_object) |
  _BIT_MASK(sym_k_XmSelectionBox_object) |
  0, _BIT_MASK(sym_k_XmSelectionDialog_object) |
  _BIT_MASK(sym_k_XmSeparator_object) |
  _BIT_MASK(sym_k_XmSeparatorGadget_object) |
  _BIT_MASK(sym_k_XmText_object) |
  _BIT_MASK(sym_k_XmTextField_object) |
  _BIT_MASK(sym_k_XmToggleButton_object) |
  _BIT_MASK(sym_k_XmToggleButtonGadget_object) |
  _BIT_MASK(sym_k_XmWarningDialog_object) |
  0, _BIT_MASK(sym_k_XmWorkArea_object) |
  _BIT_MASK(sym_k_XmWorkingDialog_object) |
  0};

/* sym_k_XmNactivateCallback_reason */
static unsigned char reason_class_vec2[] =
  {
  _BIT_MASK(sym_k_XmArrowButton_object) |
  _BIT_MASK(sym_k_XmArrowButtonGadget_object) |
  _BIT_MASK(sym_k_XmCascadeButton_object) |
  _BIT_MASK(sym_k_XmCascadeButtonGadget_object) |
  0, _BIT_MASK(sym_k_XmDrawnButton_object) |
  0, 0, _BIT_MASK(sym_k_XmPushButton_object) |
  _BIT_MASK(sym_k_XmPushButtonGadget_object) |
  0, _BIT_MASK(sym_k_XmScrolledText_object) |
  0, _BIT_MASK(sym_k_XmText_object) |
  _BIT_MASK(sym_k_XmTextField_object) |
  0, 0};

/* sym_k_XmNapplyCallback_reason */
static unsigned char reason_class_vec3[] =
  {
  0, _BIT_MASK(sym_k_XmFileSelectionBox_object) |
  _BIT_MASK(sym_k_XmFileSelectionDialog_object) |
  0, 0, _BIT_MASK(sym_k_XmPromptDialog_object) |
  0, _BIT_MASK(sym_k_XmSelectionBox_object) |
  0, _BIT_MASK(sym_k_XmSelectionDialog_object) |
  0, 0};

/* sym_k_XmNarmCallback_reason */
static unsigned char reason_class_vec4[] =
  {
  _BIT_MASK(sym_k_XmArrowButton_object) |
  _BIT_MASK(sym_k_XmArrowButtonGadget_object) |
  0, _BIT_MASK(sym_k_XmDrawnButton_object) |
  0, 0, _BIT_MASK(sym_k_XmPushButton_object) |
  _BIT_MASK(sym_k_XmPushButtonGadget_object) |
  0, 0, _BIT_MASK(sym_k_XmToggleButton_object) |
  _BIT_MASK(sym_k_XmToggleButtonGadget_object) |
  0, 0};

/* sym_k_XmNbrowseSelectionCallback_reason */
static unsigned char reason_class_vec5[] =
  {
  0, 0, _BIT_MASK(sym_k_XmList_object) |
  0, 0, _BIT_MASK(sym_k_XmScrolledList_object) |
  0, 0, 0};

/* sym_k_XmNcancelCallback_reason */
static unsigned char reason_class_vec6[] =
  {
  0, _BIT_MASK(sym_k_XmErrorDialog_object) |
  _BIT_MASK(sym_k_XmFileSelectionBox_object) |
  _BIT_MASK(sym_k_XmFileSelectionDialog_object) |
  0, _BIT_MASK(sym_k_XmInformationDialog_object) |
  _BIT_MASK(sym_k_XmMessageBox_object) |
  _BIT_MASK(sym_k_XmMessageDialog_object) |
  0, _BIT_MASK(sym_k_XmPromptDialog_object) |
  _BIT_MASK(sym_k_XmQuestionDialog_object) |
  0, _BIT_MASK(sym_k_XmSelectionBox_object) |
  0, _BIT_MASK(sym_k_XmSelectionDialog_object) |
  _BIT_MASK(sym_k_XmWarningDialog_object) |
  0, _BIT_MASK(sym_k_XmWorkingDialog_object) |
  0};

/* sym_k_XmNcascadingCallback_reason */
static unsigned char reason_class_vec7[] =
  {
  _BIT_MASK(sym_k_XmCascadeButton_object) |
  _BIT_MASK(sym_k_XmCascadeButtonGadget_object) |
  0, 0, 0, 0, 0, 0, 0};

/* sym_k_XmNcommandChangedCallback_reason */
static unsigned char reason_class_vec8[] =
  {
  _BIT_MASK(sym_k_XmCommand_object) |
  0, 0, 0, 0, 0, 0, 0};

/* sym_k_XmNcommandEnteredCallback_reason */
static unsigned char reason_class_vec9[] =
  {
  _BIT_MASK(sym_k_XmCommand_object) |
  0, 0, 0, 0, 0, 0, 0};

/* sym_k_XmNdecrementCallback_reason */
static unsigned char reason_class_vec10[] =
  {
  0, 0, 0, 0, _BIT_MASK(sym_k_XmScrollBar_object) |
  0, 0, 0};

/* sym_k_XmNdefaultActionCallback_reason */
static unsigned char reason_class_vec11[] =
  {
  0, 0, _BIT_MASK(sym_k_XmList_object) |
  0, 0, _BIT_MASK(sym_k_XmScrolledList_object) |
  0, 0, 0};

/* sym_k_XmNdestroyCallback_reason */
static unsigned char reason_class_vec12[] =
  {
  _BIT_MASK(sym_k_XmArrowButton_object) |
  _BIT_MASK(sym_k_XmArrowButtonGadget_object) |
  _BIT_MASK(sym_k_XmBulletinBoard_object) |
  _BIT_MASK(sym_k_XmBulletinBoardDialog_object) |
  _BIT_MASK(sym_k_XmCascadeButton_object) |
  _BIT_MASK(sym_k_XmCascadeButtonGadget_object) |
  _BIT_MASK(sym_k_XmCommand_object) |
  0, _BIT_MASK(sym_k_XmDrawingArea_object) |
  _BIT_MASK(sym_k_XmDrawnButton_object) |
  _BIT_MASK(sym_k_XmErrorDialog_object) |
  _BIT_MASK(sym_k_XmFileSelectionBox_object) |
  _BIT_MASK(sym_k_XmFileSelectionDialog_object) |
  _BIT_MASK(sym_k_XmForm_object) |
  _BIT_MASK(sym_k_XmFormDialog_object) |
  _BIT_MASK(sym_k_XmFrame_object) |
  0, _BIT_MASK(sym_k_XmInformationDialog_object) |
  _BIT_MASK(sym_k_XmLabel_object) |
  _BIT_MASK(sym_k_XmLabelGadget_object) |
  _BIT_MASK(sym_k_XmList_object) |
  _BIT_MASK(sym_k_XmMainWindow_object) |
  _BIT_MASK(sym_k_XmMenuBar_object) |
  _BIT_MASK(sym_k_XmMessageBox_object) |
  _BIT_MASK(sym_k_XmMessageDialog_object) |
  0, _BIT_MASK(sym_k_XmOptionMenu_object) |
  _BIT_MASK(sym_k_XmPanedWindow_object) |
  _BIT_MASK(sym_k_XmPopupMenu_object) |
  _BIT_MASK(sym_k_XmPromptDialog_object) |
  _BIT_MASK(sym_k_XmPulldownMenu_object) |
  _BIT_MASK(sym_k_XmPushButton_object) |
  _BIT_MASK(sym_k_XmPushButtonGadget_object) |
  _BIT_MASK(sym_k_XmQuestionDialog_object) |
  0, _BIT_MASK(sym_k_XmRadioBox_object) |
  _BIT_MASK(sym_k_XmRowColumn_object) |
  _BIT_MASK(sym_k_XmScale_object) |
  _BIT_MASK(sym_k_XmScrollBar_object) |
  _BIT_MASK(sym_k_XmScrolledList_object) |
  _BIT_MASK(sym_k_XmScrolledText_object) |
  _BIT_MASK(sym_k_XmScrolledWindow_object) |
  _BIT_MASK(sym_k_XmSelectionBox_object) |
  0, _BIT_MASK(sym_k_XmSelectionDialog_object) |
  _BIT_MASK(sym_k_XmSeparator_object) |
  _BIT_MASK(sym_k_XmSeparatorGadget_object) |
  _BIT_MASK(sym_k_XmText_object) |
  _BIT_MASK(sym_k_XmTextField_object) |
  _BIT_MASK(sym_k_XmToggleButton_object) |
  _BIT_MASK(sym_k_XmToggleButtonGadget_object) |
  _BIT_MASK(sym_k_XmWarningDialog_object) |
  0, _BIT_MASK(sym_k_XmWorkArea_object) |
  _BIT_MASK(sym_k_XmWorkingDialog_object) |
  0};

/* sym_k_XmNdisarmCallback_reason */
static unsigned char reason_class_vec13[] =
  {
  _BIT_MASK(sym_k_XmArrowButton_object) |
  _BIT_MASK(sym_k_XmArrowButtonGadget_object) |
  0, _BIT_MASK(sym_k_XmDrawnButton_object) |
  0, 0, _BIT_MASK(sym_k_XmPushButton_object) |
  _BIT_MASK(sym_k_XmPushButtonGadget_object) |
  0, 0, _BIT_MASK(sym_k_XmToggleButton_object) |
  _BIT_MASK(sym_k_XmToggleButtonGadget_object) |
  0, 0};

/* sym_k_XmNdragCallback_reason */
static unsigned char reason_class_vec14[] =
  {
  0, 0, 0, 0, _BIT_MASK(sym_k_XmScale_object) |
  _BIT_MASK(sym_k_XmScrollBar_object) |
  0, 0, 0};

/* sym_k_XmNentryCallback_reason */
static unsigned char reason_class_vec15[] =
  {
  0, 0, _BIT_MASK(sym_k_XmMenuBar_object) |
  0, _BIT_MASK(sym_k_XmOptionMenu_object) |
  _BIT_MASK(sym_k_XmPopupMenu_object) |
  _BIT_MASK(sym_k_XmPulldownMenu_object) |
  0, _BIT_MASK(sym_k_XmRadioBox_object) |
  _BIT_MASK(sym_k_XmRowColumn_object) |
  0, 0, _BIT_MASK(sym_k_XmWorkArea_object) |
  0};

/* sym_k_XmNexposeCallback_reason */
static unsigned char reason_class_vec16[] =
  {
  0, _BIT_MASK(sym_k_XmDrawingArea_object) |
  _BIT_MASK(sym_k_XmDrawnButton_object) |
  0, 0, 0, 0, 0, 0};

/* sym_k_XmNextendedSelectionCallback_reason */
static unsigned char reason_class_vec17[] =
  {
  0, 0, _BIT_MASK(sym_k_XmList_object) |
  0, 0, _BIT_MASK(sym_k_XmScrolledList_object) |
  0, 0, 0};

/* sym_k_XmNfocusCallback_reason */
static unsigned char reason_class_vec18[] =
  {
  _BIT_MASK(sym_k_XmBulletinBoard_object) |
  _BIT_MASK(sym_k_XmBulletinBoardDialog_object) |
  _BIT_MASK(sym_k_XmCommand_object) |
  0, _BIT_MASK(sym_k_XmErrorDialog_object) |
  _BIT_MASK(sym_k_XmFileSelectionBox_object) |
  _BIT_MASK(sym_k_XmFileSelectionDialog_object) |
  _BIT_MASK(sym_k_XmForm_object) |
  _BIT_MASK(sym_k_XmFormDialog_object) |
  0, _BIT_MASK(sym_k_XmInformationDialog_object) |
  _BIT_MASK(sym_k_XmMessageBox_object) |
  _BIT_MASK(sym_k_XmMessageDialog_object) |
  0, _BIT_MASK(sym_k_XmPromptDialog_object) |
  _BIT_MASK(sym_k_XmQuestionDialog_object) |
  0, _BIT_MASK(sym_k_XmScrolledText_object) |
  _BIT_MASK(sym_k_XmSelectionBox_object) |
  0, _BIT_MASK(sym_k_XmSelectionDialog_object) |
  _BIT_MASK(sym_k_XmText_object) |
  _BIT_MASK(sym_k_XmWarningDialog_object) |
  0, _BIT_MASK(sym_k_XmWorkingDialog_object) |
  0};

/* sym_k_XmNgainPrimaryCallback_reason */
static unsigned char reason_class_vec19[] =
  {
  0, 0, 0, 0, _BIT_MASK(sym_k_XmScrolledText_object) |
  0, _BIT_MASK(sym_k_XmText_object) |
  _BIT_MASK(sym_k_XmTextField_object) |
  0, 0};

/* sym_k_XmNhelpCallback_reason */
static unsigned char reason_class_vec20[] =
  {
  _BIT_MASK(sym_k_XmArrowButton_object) |
  _BIT_MASK(sym_k_XmArrowButtonGadget_object) |
  _BIT_MASK(sym_k_XmBulletinBoard_object) |
  _BIT_MASK(sym_k_XmBulletinBoardDialog_object) |
  _BIT_MASK(sym_k_XmCascadeButton_object) |
  _BIT_MASK(sym_k_XmCascadeButtonGadget_object) |
  _BIT_MASK(sym_k_XmCommand_object) |
  0, _BIT_MASK(sym_k_XmDrawingArea_object) |
  _BIT_MASK(sym_k_XmDrawnButton_object) |
  _BIT_MASK(sym_k_XmErrorDialog_object) |
  _BIT_MASK(sym_k_XmFileSelectionBox_object) |
  _BIT_MASK(sym_k_XmFileSelectionDialog_object) |
  _BIT_MASK(sym_k_XmForm_object) |
  _BIT_MASK(sym_k_XmFormDialog_object) |
  _BIT_MASK(sym_k_XmFrame_object) |
  0, _BIT_MASK(sym_k_XmInformationDialog_object) |
  _BIT_MASK(sym_k_XmLabel_object) |
  _BIT_MASK(sym_k_XmLabelGadget_object) |
  _BIT_MASK(sym_k_XmList_object) |
  _BIT_MASK(sym_k_XmMainWindow_object) |
  _BIT_MASK(sym_k_XmMenuBar_object) |
  _BIT_MASK(sym_k_XmMessageBox_object) |
  _BIT_MASK(sym_k_XmMessageDialog_object) |
  0, _BIT_MASK(sym_k_XmOptionMenu_object) |
  _BIT_MASK(sym_k_XmPanedWindow_object) |
  _BIT_MASK(sym_k_XmPopupMenu_object) |
  _BIT_MASK(sym_k_XmPromptDialog_object) |
  _BIT_MASK(sym_k_XmPulldownMenu_object) |
  _BIT_MASK(sym_k_XmPushButton_object) |
  _BIT_MASK(sym_k_XmPushButtonGadget_object) |
  _BIT_MASK(sym_k_XmQuestionDialog_object) |
  0, _BIT_MASK(sym_k_XmRadioBox_object) |
  _BIT_MASK(sym_k_XmRowColumn_object) |
  _BIT_MASK(sym_k_XmScale_object) |
  _BIT_MASK(sym_k_XmScrollBar_object) |
  _BIT_MASK(sym_k_XmScrolledList_object) |
  _BIT_MASK(sym_k_XmScrolledText_object) |
  _BIT_MASK(sym_k_XmScrolledWindow_object) |
  _BIT_MASK(sym_k_XmSelectionBox_object) |
  0, _BIT_MASK(sym_k_XmSelectionDialog_object) |
  _BIT_MASK(sym_k_XmSeparator_object) |
  _BIT_MASK(sym_k_XmSeparatorGadget_object) |
  _BIT_MASK(sym_k_XmText_object) |
  _BIT_MASK(sym_k_XmTextField_object) |
  _BIT_MASK(sym_k_XmToggleButton_object) |
  _BIT_MASK(sym_k_XmToggleButtonGadget_object) |
  _BIT_MASK(sym_k_XmWarningDialog_object) |
  0, _BIT_MASK(sym_k_XmWorkArea_object) |
  _BIT_MASK(sym_k_XmWorkingDialog_object) |
  0};

/* sym_k_XmNincrementCallback_reason */
static unsigned char reason_class_vec21[] =
  {
  0, 0, 0, 0, _BIT_MASK(sym_k_XmScrollBar_object) |
  0, 0, 0};

/* sym_k_XmNinputCallback_reason */
static unsigned char reason_class_vec22[] =
  {
  0, _BIT_MASK(sym_k_XmDrawingArea_object) |
  0, 0, 0, 0, 0, 0};

/* sym_k_XmNlosePrimaryCallback_reason */
static unsigned char reason_class_vec23[] =
  {
  0, 0, 0, 0, _BIT_MASK(sym_k_XmScrolledText_object) |
  0, _BIT_MASK(sym_k_XmText_object) |
  _BIT_MASK(sym_k_XmTextField_object) |
  0, 0};

/* sym_k_XmNlosingFocusCallback_reason */
static unsigned char reason_class_vec24[] =
  {
  0, 0, 0, 0, _BIT_MASK(sym_k_XmScrolledText_object) |
  0, _BIT_MASK(sym_k_XmText_object) |
  _BIT_MASK(sym_k_XmTextField_object) |
  0, 0};

/* sym_k_XmNmapCallback_reason */
static unsigned char reason_class_vec25[] =
  {
  _BIT_MASK(sym_k_XmBulletinBoard_object) |
  _BIT_MASK(sym_k_XmBulletinBoardDialog_object) |
  _BIT_MASK(sym_k_XmCommand_object) |
  0, _BIT_MASK(sym_k_XmErrorDialog_object) |
  _BIT_MASK(sym_k_XmFileSelectionBox_object) |
  _BIT_MASK(sym_k_XmFileSelectionDialog_object) |
  _BIT_MASK(sym_k_XmForm_object) |
  _BIT_MASK(sym_k_XmFormDialog_object) |
  0, _BIT_MASK(sym_k_XmInformationDialog_object) |
  _BIT_MASK(sym_k_XmMenuBar_object) |
  _BIT_MASK(sym_k_XmMessageBox_object) |
  _BIT_MASK(sym_k_XmMessageDialog_object) |
  0, _BIT_MASK(sym_k_XmOptionMenu_object) |
  _BIT_MASK(sym_k_XmPopupMenu_object) |
  _BIT_MASK(sym_k_XmPromptDialog_object) |
  _BIT_MASK(sym_k_XmPulldownMenu_object) |
  _BIT_MASK(sym_k_XmQuestionDialog_object) |
  0, _BIT_MASK(sym_k_XmRadioBox_object) |
  _BIT_MASK(sym_k_XmRowColumn_object) |
  _BIT_MASK(sym_k_XmSelectionBox_object) |
  0, _BIT_MASK(sym_k_XmSelectionDialog_object) |
  _BIT_MASK(sym_k_XmWarningDialog_object) |
  0, _BIT_MASK(sym_k_XmWorkArea_object) |
  _BIT_MASK(sym_k_XmWorkingDialog_object) |
  0};

/* sym_k_XmNmodifyVerifyCallback_reason */
static unsigned char reason_class_vec26[] =
  {
  0, 0, 0, 0, _BIT_MASK(sym_k_XmScrolledText_object) |
  0, _BIT_MASK(sym_k_XmText_object) |
  _BIT_MASK(sym_k_XmTextField_object) |
  0, 0};

/* sym_k_XmNmotionVerifyCallback_reason */
static unsigned char reason_class_vec27[] =
  {
  0, 0, 0, 0, _BIT_MASK(sym_k_XmScrolledText_object) |
  0, _BIT_MASK(sym_k_XmText_object) |
  _BIT_MASK(sym_k_XmTextField_object) |
  0, 0};

/* sym_k_XmNmultipleSelectionCallback_reason */
static unsigned char reason_class_vec28[] =
  {
  0, 0, _BIT_MASK(sym_k_XmList_object) |
  0, 0, _BIT_MASK(sym_k_XmScrolledList_object) |
  0, 0, 0};

/* sym_k_XmNnoMatchCallback_reason */
static unsigned char reason_class_vec29[] =
  {
  0, _BIT_MASK(sym_k_XmFileSelectionBox_object) |
  _BIT_MASK(sym_k_XmFileSelectionDialog_object) |
  0, 0, _BIT_MASK(sym_k_XmPromptDialog_object) |
  0, _BIT_MASK(sym_k_XmSelectionBox_object) |
  0, _BIT_MASK(sym_k_XmSelectionDialog_object) |
  0, 0};

/* sym_k_XmNokCallback_reason */
static unsigned char reason_class_vec30[] =
  {
  0, _BIT_MASK(sym_k_XmErrorDialog_object) |
  _BIT_MASK(sym_k_XmFileSelectionBox_object) |
  _BIT_MASK(sym_k_XmFileSelectionDialog_object) |
  0, _BIT_MASK(sym_k_XmInformationDialog_object) |
  _BIT_MASK(sym_k_XmMessageBox_object) |
  _BIT_MASK(sym_k_XmMessageDialog_object) |
  0, _BIT_MASK(sym_k_XmPromptDialog_object) |
  _BIT_MASK(sym_k_XmQuestionDialog_object) |
  0, _BIT_MASK(sym_k_XmSelectionBox_object) |
  0, _BIT_MASK(sym_k_XmSelectionDialog_object) |
  _BIT_MASK(sym_k_XmWarningDialog_object) |
  0, _BIT_MASK(sym_k_XmWorkingDialog_object) |
  0};

/* sym_k_XmNpageDecrementCallback_reason */
static unsigned char reason_class_vec31[] =
  {
  0, 0, 0, 0, _BIT_MASK(sym_k_XmScrollBar_object) |
  0, 0, 0};

/* sym_k_XmNpageIncrementCallback_reason */
static unsigned char reason_class_vec32[] =
  {
  0, 0, 0, 0, _BIT_MASK(sym_k_XmScrollBar_object) |
  0, 0, 0};

/* sym_k_XmNresizeCallback_reason */
static unsigned char reason_class_vec33[] =
  {
  0, _BIT_MASK(sym_k_XmDrawingArea_object) |
  _BIT_MASK(sym_k_XmDrawnButton_object) |
  0, 0, 0, 0, 0, 0};

/* sym_k_XmNsingleSelectionCallback_reason */
static unsigned char reason_class_vec34[] =
  {
  0, 0, _BIT_MASK(sym_k_XmList_object) |
  0, 0, _BIT_MASK(sym_k_XmScrolledList_object) |
  0, 0, 0};

/* sym_k_XmNtoBottomCallback_reason */
static unsigned char reason_class_vec35[] =
  {
  0, 0, 0, 0, _BIT_MASK(sym_k_XmScrollBar_object) |
  0, 0, 0};

/* sym_k_XmNtoTopCallback_reason */
static unsigned char reason_class_vec36[] =
  {
  0, 0, 0, 0, _BIT_MASK(sym_k_XmScrollBar_object) |
  0, 0, 0};

/* sym_k_XmNunmapCallback_reason */
static unsigned char reason_class_vec37[] =
  {
  _BIT_MASK(sym_k_XmBulletinBoard_object) |
  _BIT_MASK(sym_k_XmBulletinBoardDialog_object) |
  _BIT_MASK(sym_k_XmCommand_object) |
  0, _BIT_MASK(sym_k_XmErrorDialog_object) |
  _BIT_MASK(sym_k_XmFileSelectionBox_object) |
  _BIT_MASK(sym_k_XmFileSelectionDialog_object) |
  _BIT_MASK(sym_k_XmForm_object) |
  _BIT_MASK(sym_k_XmFormDialog_object) |
  0, _BIT_MASK(sym_k_XmInformationDialog_object) |
  _BIT_MASK(sym_k_XmMenuBar_object) |
  _BIT_MASK(sym_k_XmMessageBox_object) |
  _BIT_MASK(sym_k_XmMessageDialog_object) |
  0, _BIT_MASK(sym_k_XmOptionMenu_object) |
  _BIT_MASK(sym_k_XmPopupMenu_object) |
  _BIT_MASK(sym_k_XmPromptDialog_object) |
  _BIT_MASK(sym_k_XmPulldownMenu_object) |
  _BIT_MASK(sym_k_XmQuestionDialog_object) |
  0, _BIT_MASK(sym_k_XmRadioBox_object) |
  _BIT_MASK(sym_k_XmRowColumn_object) |
  _BIT_MASK(sym_k_XmSelectionBox_object) |
  0, _BIT_MASK(sym_k_XmSelectionDialog_object) |
  _BIT_MASK(sym_k_XmWarningDialog_object) |
  0, _BIT_MASK(sym_k_XmWorkArea_object) |
  _BIT_MASK(sym_k_XmWorkingDialog_object) |
  0};

/* sym_k_XmNvalueChangedCallback_reason */
static unsigned char reason_class_vec38[] =
  {
  0, 0, 0, 0, _BIT_MASK(sym_k_XmScale_object) |
  _BIT_MASK(sym_k_XmScrollBar_object) |
  _BIT_MASK(sym_k_XmScrolledText_object) |
  0, _BIT_MASK(sym_k_XmText_object) |
  _BIT_MASK(sym_k_XmTextField_object) |
  _BIT_MASK(sym_k_XmToggleButton_object) |
  _BIT_MASK(sym_k_XmToggleButtonGadget_object) |
  0, 0};

/*
 * Table of bit vectors accessed by sym_k_..._reason
 */
static unsigned char *allowed_reason_table_vec[] =
  {
  NULL,	/* UNUSED */
  reason_class_vec1,
  reason_class_vec2,
  reason_class_vec3,
  reason_class_vec4,
  reason_class_vec5,
  reason_class_vec6,
  reason_class_vec7,
  reason_class_vec8,
  reason_class_vec9,
  reason_class_vec10,
  reason_class_vec11,
  reason_class_vec12,
  reason_class_vec13,
  reason_class_vec14,
  reason_class_vec15,
  reason_class_vec16,
  reason_class_vec17,
  reason_class_vec18,
  reason_class_vec19,
  reason_class_vec20,
  reason_class_vec21,
  reason_class_vec22,
  reason_class_vec23,
  reason_class_vec24,
  reason_class_vec25,
  reason_class_vec26,
  reason_class_vec27,
  reason_class_vec28,
  reason_class_vec29,
  reason_class_vec30,
  reason_class_vec31,
  reason_class_vec32,
  reason_class_vec33,
  reason_class_vec34,
  reason_class_vec35,
  reason_class_vec36,
  reason_class_vec37,
  reason_class_vec38,
  };
externaldef(uil_sym_glbl) unsigned char **allowed_reason_table =
		allowed_reason_table_vec;
