/*
**	This file is automatically generated.  Do not edit it by hand.
**/

/*
 * Enumeration value vectors for each enumeration set
 */


static unsigned short int enum_value_vec1[] =
  {
    6,
    7,
    5,
  };

static unsigned short int enum_value_vec2[] =
  {
    12,
    9,
    10,
    11,
  };

static unsigned short int enum_value_vec3[] =
  {
    15,
    14,
    16,
    20,
    17,
    18,
    19,
  };

static unsigned short int enum_value_vec4[] =
  {
    25,
    26,
  };

static unsigned short int enum_value_vec5[] =
  {
    29,
    30,
    34,
    37,
    39,
    44,
    45,
  };

static unsigned short int enum_value_vec6[] =
  {
    46,
    40,
    38,
    49,
    33,
    28,
  };

static unsigned short int enum_value_vec7[] =
  {
    41,
    43,
    49,
    32,
    31,
    35,
    36,
    42,
    47,
    48,
  };

static unsigned short int enum_value_vec8[] =
  {
    90,
    68,
  };

static unsigned short int enum_value_vec9[] =
  {
    55,
    54,
  };

static unsigned short int enum_value_vec10[] =
  {
    74,
    73,
  };

static unsigned short int enum_value_vec11[] =
  {
    94,
    79,
  };

static unsigned short int enum_value_vec12[] =
  {
    27,
    100,
    82,
  };

static unsigned short int enum_value_vec13[] =
  {
    65,
    66,
  };

static unsigned short int enum_value_vec14[] =
  {
    69,
    97,
    93,
    52,
  };

static unsigned short int enum_value_vec15[] =
  {
    71,
    101,
    56,
  };

static unsigned short int enum_value_vec16[] =
  {
    72,
    77,
    75,
    76,
  };

static unsigned short int enum_value_vec17[] =
  {
    60,
    57,
    58,
    59,
  };

static unsigned short int enum_value_vec18[] =
  {
    83,
    80,
    81,
  };

static unsigned short int enum_value_vec19[] =
  {
    102,
    61,
    64,
    63,
    62,
  };

static unsigned short int enum_value_vec20[] =
  {
    13,
    21,
    92,
    8,
  };

static unsigned short int enum_value_vec21[] =
  {
    98,
    22,
    99,
    23,
  };

static unsigned short int enum_value_vec22[] =
  {
    21,
    27,
    8,
  };

static unsigned short int enum_value_vec23[] =
  {
    91,
    67,
    53,
    24,
  };

static unsigned short int enum_value_vec24[] =
  {
    89,
    51,
    88,
    50,
    70,
    84,
    85,
  };

static unsigned short int enum_value_vec25[] =
  {
    86,
    87,
    84,
    85,
  };

static unsigned short int enum_value_vec26[] =
  {
    95,
    96,
  };

static unsigned short int enum_value_vec27[] =
  {
    78,
    3,
    1,
    4,
    2,
  };

static unsigned short int enum_value_vec28[] =
  {
    100,
    92,
    27,
  };

/*
 * Enumeration set descriptor table
 */
static UilEnumSetDescDef enum_set_table_vec[] =
  {
    {0,NULL},
    {3,enum_value_vec1},
    {4,enum_value_vec2},
    {7,enum_value_vec3},
    {2,enum_value_vec4},
    {7,enum_value_vec5},
    {6,enum_value_vec6},
    {10,enum_value_vec7},
    {2,enum_value_vec8},
    {2,enum_value_vec9},
    {2,enum_value_vec10},
    {2,enum_value_vec11},
    {3,enum_value_vec12},
    {2,enum_value_vec13},
    {4,enum_value_vec14},
    {3,enum_value_vec15},
    {4,enum_value_vec16},
    {4,enum_value_vec17},
    {3,enum_value_vec18},
    {5,enum_value_vec19},
    {4,enum_value_vec20},
    {4,enum_value_vec21},
    {3,enum_value_vec22},
    {4,enum_value_vec23},
    {7,enum_value_vec24},
    {4,enum_value_vec25},
    {2,enum_value_vec26},
    {5,enum_value_vec27},
    {3,enum_value_vec28},
  };
externaldef(uil_sym_glbl) UilEnumSetDescDef *enum_set_table =
		enum_set_table_vec;
/*
 * Enumeration set table, accessed by sym_k_..._arg code. Each non-zero entry
 * is the sym_k_..._enumset code for the argument's enumeration set.
 */
static unsigned short int argument_enumset_table_vec[] =
  {
    0,
    0,
    0,
    0,
    0,
    0,
    1,
    0,
    0,
    0,
    0,
    0,
    0,
    2,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    3,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    4,
    0,
    0,
    0,
    0,
    0,
    5,
    0,
    0,
    6,
    0,
    7,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    8,
    0,
    1,
    0,
    0,
    0,
    0,
    0,
    0,
    9,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    10,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    11,
    3,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    12,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    1,
    0,
    0,
    0,
    0,
    0,
    0,
    13,
    0,
    14,
    0,
    0,
    0,
    0,
    15,
    16,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    17,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    18,
    0,
    3,
    0,
    0,
    0,
    19,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    20,
    21,
    0,
    0,
    0,
    0,
    0,
    0,
    22,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    23,
    0,
    0,
    24,
    0,
    0,
    25,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    26,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    3,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    27,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    28,
    0,
    0,
    0,
    0,
    0,
    0,
  };
externaldef(uil_sym_glbl) unsigned short int *argument_enumset_table =
		argument_enumset_table_vec;
/*
 * Enumeration value table, accessed by sym_k_..._enumval code. Each entry is
 * the actual value associated with the code.
 */
static int enumval_values_table_vec[] =
  {
  0,
  Xm1000TH_INCHES,
  Xm100TH_FONT_UNITS,
  Xm100TH_MILLIMETERS,
  Xm100TH_POINTS,
  XmALIGNMENT_BEGINNING,
  XmALIGNMENT_CENTER,
  XmALIGNMENT_END,
  XmAPPLICATION_DEFINED,
  XmARROW_DOWN,
  XmARROW_LEFT,
  XmARROW_RIGHT,
  XmARROW_UP,
  XmAS_NEEDED,
  XmATTACH_FORM,
  XmATTACH_NONE,
  XmATTACH_OPPOSITE_FORM,
  XmATTACH_OPPOSITE_WIDGET,
  XmATTACH_POSITION,
  XmATTACH_SELF,
  XmATTACH_WIDGET,
  XmAUTOMATIC,
  XmBOTTOM_LEFT,
  XmBOTTOM_RIGHT,
  XmBROWSE_SELECT,
  XmCOMMAND_ABOVE_WORKSPACE,
  XmCOMMAND_BELOW_WORKSPACE,
  XmCONSTANT,
  XmDIALOG_APPLICATION_MODAL,
  XmDIALOG_CANCEL_BUTTON,
  XmDIALOG_DEFAULT_BUTTON,
  XmDIALOG_ERROR,
  XmDIALOG_FILE_SELECTION,
  XmDIALOG_FULL_APPLICATION_MODAL,
  XmDIALOG_HELP_BUTTON,
  XmDIALOG_INFORMATION,
  XmDIALOG_MESSAGE,
  XmDIALOG_MESSAGE_LABEL,
  XmDIALOG_MODELESS,
  XmDIALOG_OK_BUTTON,
  XmDIALOG_PRIMARY_APPLICATION_MODAL,
  XmDIALOG_PROMPT,
  XmDIALOG_QUESTION,
  XmDIALOG_SELECTION,
  XmDIALOG_SEPARATOR,
  XmDIALOG_SYMBOL_LABEL,
  XmDIALOG_SYSTEM_MODAL,
  XmDIALOG_WARNING,
  XmDIALOG_WORKING,
  XmDIALOG_WORK_AREA,
  XmDOUBLE_DASHED_LINE,
  XmDOUBLE_LINE,
  XmEXCLUSIVE_TAB_GROUP,
  XmEXTENDED_SELECT,
  XmFILE_DIRECTORY,
  XmFILE_REGULAR,
  XmHORIZONTAL,
  XmMAX_ON_BOTTOM,
  XmMAX_ON_LEFT,
  XmMAX_ON_RIGHT,
  XmMAX_ON_TOP,
  XmMENU_BAR,
  XmMENU_OPTION,
  XmMENU_POPUP,
  XmMENU_PULLDOWN,
  XmMULTICLICK_DISCARD,
  XmMULTICLICK_KEEP,
  XmMULTIPLE_SELECT,
  XmMULTI_LINE_EDIT,
  XmNONE,
  XmNO_LINE,
  XmNO_ORIENTATION,
  XmNO_PACKING,
  XmN_OF_MANY,
  XmONE_OF_MANY,
  XmPACK_COLUMN,
  XmPACK_NONE,
  XmPACK_TIGHT,
  XmPIXELS,
  XmPIXMAP,
  XmRESIZE_ANY,
  XmRESIZE_GROW,
  XmRESIZE_IF_POSSIBLE,
  XmRESIZE_NONE,
  XmSHADOW_ETCHED_IN,
  XmSHADOW_ETCHED_OUT,
  XmSHADOW_IN,
  XmSHADOW_OUT,
  XmSINGLE_DASHED_LINE,
  XmSINGLE_LINE,
  XmSINGLE_LINE_EDIT,
  XmSINGLE_SELECT,
  XmSTATIC,
  XmSTICKY_TAB_GROUP,
  XmSTRING,
  XmSTRING_DIRECTION_L_TO_R,
  XmSTRING_DIRECTION_R_TO_L,
  XmTAB_GROUP,
  XmTOP_LEFT,
  XmTOP_RIGHT,
  XmVARIABLE,
  XmVERTICAL,
  XmWORK_AREA,
  };
externaldef(uil_sym_glbl) int *enumval_values_table =
		enumval_values_table_vec;
