# /usr/src/lib/c2/c2.mac2/Makefile for MacMach

all:	c2 .depend

c2:	FRC
	@echo "*** c2 not implemented for mac2 ***"

clean:	FRC
	rm -f .depend *.o *.s c2

install: FRC
	@echo "*** c2 not implemented for mac2 ***"

.depend:
	@echo "#`date`" >.depend
#	mkdep -f .depend ${CFLAGS} ${SRCS}

-include .depend

FRC:
