# /usr/src/usr.lib/libm/mac2/Makefile for MacMach

# MacMach libm goodies, see /usr/include/mac2/math.h for inline functions

MAC2OBJS = acosh.o asincos.o asinh.o atan.o atan2.o atanh.o cabs.o cbrt.o \
	   cosh.o exp.o expm1.o floor.o log.o log10.o log1p.o pow.o \
	   sincos.o sinh.o support.o tan.o tanh.o

include Makefile-common

FRC:
