...\"	index formatting macros
...\"
...\"
...\"	Iy  --  called between letters of the alphabet
.de Iy
.if !\\$1 \{\
.	fl
.	sp 5v
.	ne .75i
.	in \\n(I#u						\" do indent
\s30\&\\$1\s0
.	sp 1
.	rm I! I@
'	br \}
..
...\"
...\"
...\"	Ix  --  called for an individual index item
.de Ix
'in \\n(I#u						\" do indent
.if !\\$1\\*(I! \{\
.br
.sp .5v                           	\" make sure we're at the start of a line
.ti 0							\" major is always at left margin
\&\\$1\c\"						\" and - output "Major"
.ds I! \\$1\"					\" save major name
.	rm I@
'	br \}
.ie \\$2\\*(I@ \{\
.	ie \\$4 , \\$3\c\"	\" same minor - just output page #
.	el , \fB\\$3\fP\c\"			\"     highlight version
'	br \}
.el \{\
.	br							\" make sure we're on a new line
.	fl
.	ie \\$4 \&\\$2, \&\\$3\c\"	and output "Minor, page#"
.	el \&\\$2, \fB\\$3\fP\c\"	\"     highlight version
.	ds I@ \\$2\"				\" save minor name
'	br \}
..
...\"
...\"	the string I! is used to hold the last major index name
.ds I!
...\"
...\"	the string I@ is used to hold the last minor index name
.ds I@
...\"
...\"	the register I# is used to hold the current indent
.nr I# .5i
...\"
...\"	to get around formatter and sorting limitations:
'fl
...\"
...\"
...\"
...\"	do everything in two column mode:
.2C
.rs
.nh			\" NO hyphenation
.na			\" no justification
.nr Hu 1
.HU "Index"
.tr ~-^\&\"	\" tilde becomes a dash, hat goes to null
.Ix ".mwmrc" "" "1~12" ""
.Ix ".mwmrc" "" "1~23" ""
.Ix ".Xdefaults" "" "1~6" ""
.Iy "A"
.Ix "ApplicationShell" "" "1~34" ""
.Ix "atoms" "" "1~282" ""
.Ix "atoms" "" "1~291" ""
.Iy "B"
.Ix "borders" "resize" "1~4" ""
.Iy "C"
.Ix "CascadeButton functions" "XmCascadeButtonHighlight" "1~132" ""
.Ix "CascadeButtonGadget functions" "XmCascadeButtonGadgetHighlight" "1~131" ""
.Ix "click to type" "" "1~15" ""
.Ix "clipboard functions" "XmClipboardCancelCopy" "1~133" ""
.Ix "clipboard functions" "XmClipboardCopy" "1~134" ""
.Ix "clipboard functions" "XmClipboardCopyByName" "1~136" ""
.Ix "clipboard functions" "XmClipboardEndCopy" "1~137" ""
.Ix "clipboard functions" "XmClipboardEndRetrieve" "1~138" ""
.Ix "clipboard functions" "XmClipboardInquireCount" "1~139" ""
.Ix "clipboard functions" "XmClipboardInquireFormat" "1~140" ""
.Ix "clipboard functions" "XmClipboardInquireLength" "1~141" ""
.Ix "clipboard functions" "XmClipboardInquirePendingItems" "1~142" ""
.Ix "clipboard functions" "XmClipboardLock" "1~143" ""
.Ix "clipboard functions" "XmClipboardRegisterFormat" "1~144" ""
.Ix "clipboard functions" "XmClipboardRetrieve" "1~145" ""
.Ix "clipboard functions" "XmClipboardStartCopy" "1~147" ""
.Ix "clipboard functions" "XmClipboardStartRetrieve" "1~149" ""
.Ix "clipboard functions" "XmClipboardUndoCopy" "1~150" ""
.Ix "clipboard functions" "XmClipboardUnlock" "1~151" ""
.Ix "clipboard functions" "XmClipboardWithdrawFormat" "1~152" ""
.Ix "Color functions" "XmGetColorCalculation" "1~283" ""
.Ix "Color functions" "XmGetColors" "1~284" ""
.Ix "Color functions" "XmSetColorCalculation" "1~461" ""
.Ix "command functions" "XmCommandAppendValue" "1~159" ""
.Ix "command functions" "XmCommandError" "1~160" ""
.Ix "command functions" "XmCommandGetChild" "1~161" ""
.Ix "command functions" "XmCommandSetValue" "1~162" ""
.Ix "Composite" "" "1~38" ""
.Ix "compound string functions" "XmCvtCTToXmString" "1~225" ""
.Ix "compound string functions" "XmCvtXmStringToCT" "1~227" ""
.Ix "compound string functions" "XmFontListAdd" "1~259" ""
.Ix "compound string functions" "XmFontListCopy" "1~260" ""
.Ix "compound string functions" "XmFontListCreate" "1~261" ""
.Ix "compound string functions" "XmFontListFree" "1~262" ""
.Ix "compound string functions" "XmFontListFreeFontContext" "1~263" ""
.Ix "compound string functions" "XmFontListGetNextFont" "1~264" ""
.Ix "compound string functions" "XmFontListInitFontContext" "1~265" ""
.Ix "compound string functions" "XmStringBaseline" "1~468" ""
.Ix "compound string functions" "XmStringByteCompare" "1~469" ""
.Ix "compound string functions" "XmStringCompare" "1~470" ""
.Ix "compound string functions" "XmStringConcat" "1~471" ""
.Ix "compound string functions" "XmStringCopy" "1~472" ""
.Ix "compound string functions" "XmStringCreate" "1~473" ""
.Ix "compound string functions" "XmStringCreateLtoR" "1~474" ""
.Ix "compound string functions" "XmStringCreateSimple" "1~475" ""
.Ix "compound string functions" "XmStringDirectionCreate" "1~477" ""
.Ix "compound string functions" "XmStringDraw" "1~478" ""
.Ix "compound string functions" "XmStringDrawImage" "1~479" ""
.Ix "compound string functions" "XmStringDrawUnderline" "1~480" ""
.Ix "compound string functions" "XmStringEmpty" "1~482" ""
.Ix "compound string functions" "XmStringExtent" "1~483" ""
.Ix "compound string functions" "XmStringFree" "1~484" ""
.Ix "compound string functions" "XmStringFreeContext" "1~485" ""
.Ix "compound string functions" "XmStringGetLtoR" "1~486" ""
.Ix "compound string functions" "XmStringGetNextComponent" "1~487" ""
.Ix "compound string functions" "XmStringGetNextSegment" "1~489" ""
.Ix "compound string functions" "XmStringHasSubstring" "1~490" ""
.Ix "compound string functions" "XmStringHeight" "1~491" ""
.Ix "compound string functions" "XmStringInitContext" "1~492" ""
.Ix "compound string functions" "XmStringLength" "1~493" ""
.Ix "compound string functions" "XmStringLineCount" "1~494" ""
.Ix "compound string functions" "XmStringNConcat" "1~495" ""
.Ix "compound string functions" "XmStringNCopy" "1~496" ""
.Ix "compound string functions" "XmStringPeekNextComponent" "1~497" ""
.Ix "compound string functions" "XmStringSegmentCreate" "1~498" ""
.Ix "compound string functions" "XmStringSeparatorCreate" "1~499" ""
.Ix "compound string functions" "XmStringWidth" "1~501" ""
.Ix "Constraint" "" "1~40" ""
.Ix "Core" "" "1~42" ""
.Ix "creation functions" "XmCreateArrowButton" "1~165" ""
.Ix "creation functions" "XmCreateArrowButtonGadget" "1~166" ""
.Ix "creation functions" "XmCreateBulletinBoard" "1~167" ""
.Ix "creation functions" "XmCreateBulletinBoardDialog" "1~168" ""
.Ix "creation functions" "XmCreateCascadeButton" "1~169" ""
.Ix "creation functions" "XmCreateCascadeButtonGadget" "1~170" ""
.Ix "creation functions" "XmCreateCommand" "1~171" ""
.Ix "creation functions" "XmCreateDialogShell" "1~172" ""
.Ix "creation functions" "XmCreateDrawingArea" "1~173" ""
.Ix "creation functions" "XmCreateDrawnButton" "1~174" ""
.Ix "creation functions" "XmCreateErrorDialog" "1~175" ""
.Ix "creation functions" "XmCreateFileSelectionBox" "1~176" ""
.Ix "creation functions" "XmCreateFileSelectionDialog" "1~177" ""
.Ix "creation functions" "XmCreateForm" "1~178" ""
.Ix "creation functions" "XmCreateFormDialog" "1~179" ""
.Ix "creation functions" "XmCreateFrame" "1~180" ""
.Ix "creation functions" "XmCreateInformationDialog" "1~181" ""
.Ix "creation functions" "XmCreateLabel" "1~182" ""
.Ix "creation functions" "XmCreateLabelGadget" "1~183" ""
.Ix "creation functions" "XmCreateList" "1~184" ""
.Ix "creation functions" "XmCreateMainWindow" "1~185" ""
.Ix "creation functions" "XmCreateMenuBar" "1~186" ""
.Ix "creation functions" "XmCreateMenuShell" "1~187" ""
.Ix "creation functions" "XmCreateMessageBox" "1~188" ""
.Ix "creation functions" "XmCreateMessageDialog" "1~189" ""
.Ix "creation functions" "XmCreateOptionMenu" "1~190" ""
.Ix "creation functions" "XmCreatePanedWindow" "1~192" ""
.Ix "creation functions" "XmCreatePopupMenu" "1~193" ""
.Ix "creation functions" "XmCreatePromptDialog" "1~194" ""
.Ix "creation functions" "XmCreatePulldownMenu" "1~195" ""
.Ix "creation functions" "XmCreatePushButton" "1~197" ""
.Ix "creation functions" "XmCreatePushButtonGadget" "1~198" ""
.Ix "creation functions" "XmCreateQuestionDialog" "1~199" ""
.Ix "creation functions" "XmCreateRadioBox" "1~200" ""
.Ix "creation functions" "XmCreateRowColumn" "1~201" ""
.Ix "creation functions" "XmCreateScale" "1~202" ""
.Ix "creation functions" "XmCreateScrollBar" "1~203" ""
.Ix "creation functions" "XmCreateScrolledList" "1~204" ""
.Ix "creation functions" "XmCreateScrolledText" "1~205" ""
.Ix "creation functions" "XmCreateScrolledWindow" "1~207" ""
.Ix "creation functions" "XmCreateSelectionBox" "1~208" ""
.Ix "creation functions" "XmCreateSelectionDialog" "1~209" ""
.Ix "creation functions" "XmCreateSeparator" "1~210" ""
.Ix "creation functions" "XmCreateSeparatorGadget" "1~211" ""
.Ix "creation functions" "XmCreateSimpleCheckBox" "1~212" ""
.Ix "creation functions" "XmCreateSimpleMenuBar" "1~213" ""
.Ix "creation functions" "XmCreateSimpleOptionMenu" "1~214" ""
.Ix "creation functions" "XmCreateSimplePopupMenu" "1~215" ""
.Ix "creation functions" "XmCreateSimplePulldownMenu" "1~216" ""
.Ix "creation functions" "XmCreateSimpleRadioBox" "1~217" ""
.Ix "creation functions" "XmCreateText" "1~218" ""
.Ix "creation functions" "XmCreateTextField" "1~219" ""
.Ix "creation functions" "XmCreateToggleButton" "1~220" ""
.Ix "creation functions" "XmCreateToggleButtonGadget" "1~221" ""
.Ix "creation functions" "XmCreateWarningDialog" "1~222" ""
.Ix "creation functions" "XmCreateWorkArea" "1~223" ""
.Ix "creation functions" "XmCreateWorkingDialog" "1~224" ""
.Ix "creation functions" "XmVaCreateSimpleCheckBox" "1~605" ""
.Ix "creation functions" "XmVaCreateSimpleMenuBar" "1~607" ""
.Ix "creation functions" "XmVaCreateSimpleOptionMenu" "1~609" ""
.Ix "creation functions" "XmVaCreateSimplePopupMenu" "1~611" ""
.Ix "creation functions" "XmVaCreateSimplePulldownMenu" "1~614" ""
.Ix "creation functions" "XmVaCreateSimpleRadioBox" "1~618" ""
.Iy "D"
.Ix "data types" "XmFontList" "1~258" ""
.Ix "data types" "XmString" "1~467" ""
.Ix "data types" "XmStringDirection" "1~476" ""
.Ix "data types" "XmStringTable" "1~500" ""
.Ix "data types" "XmTextPosition" "1~569" ""
.Ix "default bindings" "VirtualBindings" "1~86" ""
.Iy "E"
.Ix "explicit" "" "1~15" ""
.Ix "explicit" "" "1~6" ""
.Iy "F"
.Ix "FileSelectionBox functions" "XmFileSelectionBoxGetChild" "1~256" ""
.Ix "FileSelectionBox functions" "XmFileSelectionDoSearch" "1~257" ""
.Ix "focus policy" "click to type" "1~15" ""
.Ix "focus policy" "click to type" "1~6" ""
.Ix "focus policy" "explicit" "1~15" ""
.Ix "focus policy" "explicit" "1~6" ""
.Ix "focus policy" "pointer" "1~15" ""
.Ix "focus policy" "real estate" "1~15" ""
.Ix "focus policy" "real estate" "1~6" ""
.Iy "I"
.Ix "icon box" "" "1~5" ""
.Ix "icons" "" "1~4" ""
.Ix "input focus" "" "1~15" ""
.Ix "input focus" "" "1~6" ""
.Ix "input focus" "click to type" "1~15" ""
.Ix "input focus" "click to type" "1~6" ""
.Ix "input focus" "explicit" "1~15" ""
.Ix "input focus" "explicit" "1~6" ""
.Ix "input focus" "pointer" "1~15" ""
.Ix "input focus" "real estate" "1~15" ""
.Iy "L"
.Ix "List functions" "XmListAddItem" "1~320" ""
.Ix "List functions" "XmListAddItems" "1~321" ""
.Ix "List functions" "XmListAddItemUnselected" "1~322" ""
.Ix "List functions" "XmListDeleteAllItems" "1~323" ""
.Ix "List functions" "XmListDeleteItem" "1~324" ""
.Ix "List functions" "XmListDeleteItems" "1~325" ""
.Ix "List functions" "XmListDeleteItemsPos" "1~326" ""
.Ix "List functions" "XmListDeletePos" "1~327" ""
.Ix "List functions" "XmListDeselectAllItems" "1~328" ""
.Ix "List functions" "XmListDeselectItem" "1~329" ""
.Ix "List functions" "XmListDeselectPos" "1~330" ""
.Ix "List functions" "XmListGetMatchPos" "1~331" ""
.Ix "List functions" "XmListGetSelectedPos" "1~332" ""
.Ix "List functions" "XmListItemExists" "1~333" ""
.Ix "List functions" "XmListItemPos" "1~334" ""
.Ix "List functions" "XmListReplaceItems" "1~335" ""
.Ix "List functions" "XmListReplaceItemsPos" "1~336" ""
.Ix "List functions" "XmListSelectItem" "1~337" ""
.Ix "List functions" "XmListSelectPos" "1~338" ""
.Ix "List functions" "XmListSetAddMode" "1~339" ""
.Ix "List functions" "XmListSetBottomItem" "1~340" ""
.Ix "List functions" "XmListSetBottomPos" "1~341" ""
.Ix "List functions" "XmListSetHorizPos" "1~342" ""
.Ix "List functions" "XmListSetItem" "1~343" ""
.Ix "List functions" "XmListSetPos" "1~344" ""
.Iy "M"
.Ix "MainWindow functions" "XmMainWindowSep1" "1~349" ""
.Ix "MainWindow functions" "XmMainWindowSep2" "1~350" ""
.Ix "MainWindow functions" "XmMainWindowSep3" "1~351" ""
.Ix "MainWindow functions" "XmMainWindowSetAreas" "1~352" ""
.Ix "manual pages" "access" "ix" ""
.Ix "manual pages" "format" "ix" ""
.Ix "maximize button" "" "1~4" ""
.Ix "maximize" "" "1~4" ""
.Ix "menu button" "" "1~4" ""
.Ix "menu" "" "1~4" ""
.Ix "MessageBox functions" "XmMessageBoxGetChild" "1~370" ""
.Ix "minimize button" "" "1~4" ""
.Ix "minimize" "" "1~4" ""
.Ix "MrmCloseHierarchy" "" "1~45" ""
.Ix "MrmFetchColorLiteral" "" "1~46" ""
.Ix "MrmFetchIconLiteral" "" "1~47" ""
.Ix "MrmFetchLiteral" "" "1~48" ""
.Ix "MrmFetchSetValues" "" "1~49" ""
.Ix "MrmFetchWidget" "" "1~51" ""
.Ix "MrmFetchWidgetOverride" "" "1~53" ""
.Ix "MrmInitialize" "" "1~55" ""
.Ix "MrmOpenHierarchy" "" "1~56" ""
.Ix "MrmRegisterClass" "" "1~59" ""
.Ix "MrmRegisterNames" "" "1~60" ""
.Ix "MrmRegisterNamesInHierarchy" "" "1~61" ""
.Ix "mwm" "" "1~3" ""
.Ix "mwm" "resources" "1~10" ""
.Ix "mwm" "resources" "1~12" ""
.Ix "mwm" "resources" "1~13" ""
.Ix "mwm" "resources" "1~14" ""
.Ix "mwm" "resources" "1~15" ""
.Ix "mwm" "resources" "1~16" ""
.Ix "mwm" "resources" "1~17" ""
.Ix "mwm" "resources" "1~18" ""
.Ix "mwm" "resources" "1~20" ""
.Ix "mwm" "resources" "1~21" ""
.Ix "mwm" "resources" "1~22" ""
.Ix "mwm" "resources" "1~23" ""
.Ix "mwm" "resources" "1~7" ""
.Ix "mwm" "resources" "1~8" ""
.Ix "mwm" "resources" "1~9" ""
.Iy "O"
.Ix "Object" "" "1~62" ""
.Ix "OverrideShell" "" "1~63" ""
.Iy "P"
.Ix "pixmaps" "" "1~230" ""
.Ix "pixmaps" "" "1~287" ""
.Ix "pixmaps" "" "1~290" ""
.Ix "pixmaps" "" "1~603" ""
.Ix "pointer" "" "1~15" ""
.Ix "protocols" "" "1~100" ""
.Ix "protocols" "" "1~101" ""
.Ix "protocols" "" "1~102" ""
.Ix "protocols" "" "1~103" ""
.Ix "protocols" "" "1~228" ""
.Ix "protocols" "" "1~229" ""
.Ix "protocols" "" "1~398" ""
.Ix "protocols" "" "1~399" ""
.Ix "protocols" "" "1~401" ""
.Ix "protocols" "" "1~402" ""
.Ix "protocols" "" "1~465" ""
.Ix "protocols" "" "1~466" ""
.Ix "protocols" "" "1~97" ""
.Ix "protocols" "" "1~98" ""
.Ix "protocols" "" "1~99" ""
.Iy "R"
.Ix "real estate" "" "1~15" ""
.Ix "real estate" "" "1~6" ""
.Ix "RectObj" "" "1~65" ""
.Ix "resize borders" "" "1~4" ""
.Ix "resource description file" "" "1~12" ""
.Ix "resource description file" "" "1~23" ""
.Ix "resources" "" "1~10" ""
.Ix "resources" "" "1~12" ""
.Ix "resources" "" "1~13" ""
.Ix "resources" "" "1~14" ""
.Ix "resources" "" "1~15" ""
.Ix "resources" "" "1~16" ""
.Ix "resources" "" "1~17" ""
.Ix "resources" "" "1~18" ""
.Ix "resources" "" "1~20" ""
.Ix "resources" "" "1~21" ""
.Ix "resources" "" "1~22" ""
.Ix "resources" "" "1~23" ""
.Ix "resources" "" "1~6" ""
.Ix "resources" "" "1~7" ""
.Ix "resources" "" "1~8" ""
.Ix "resources" "" "1~9" ""
.Ix "RowColumn functions" "XmGetMenuCursor" "1~286" ""
.Ix "RowColumn functions" "XmGetPostedFromWidget" "1~289" ""
.Ix "RowColumn functions" "XmMenuPosition" "1~359" ""
.Ix "RowColumn functions" "XmOptionButtonGadget" "1~371" ""
.Ix "RowColumn functions" "XmOptionLabelGadget" "1~372" ""
.Ix "RowColumn functions" "XmSetMenuCursor" "1~464" ""
.Iy "S"
.Ix "Scale functions" "XmScaleGetValue" "1~428" ""
.Ix "Scale functions" "XmScaleSetValue" "1~429" ""
.Ix "ScrollBar functions" "XmScrollBarGetValues" "1~438" ""
.Ix "ScrollBar functions" "XmScrollBarSetValues" "1~439" ""
.Ix "ScrolledWindow functions" "XmScrolledWindowSetAreas" "1~446" ""
.Ix "SelectionBox functions" "XmSelectionBoxGetChild" "1~454" ""
.Ix "session manager" "" "1~3" ""
.Ix "Shell" "" "1~67" ""
.Iy "T"
.Ix "Text functions" "XmTextClearSelection" "1~521" ""
.Ix "Text functions" "XmTextCopy" "1~522" ""
.Ix "Text functions" "XmTextCut" "1~523" ""
.Ix "Text functions" "XmTextGetBaseline" "1~556" ""
.Ix "Text functions" "XmTextGetEditable" "1~557" ""
.Ix "Text functions" "XmTextGetInsertionPosition" "1~558" ""
.Ix "Text functions" "XmTextGetLastPosition" "1~559" ""
.Ix "Text functions" "XmTextGetMaxLength" "1~560" ""
.Ix "Text functions" "XmTextGetSelection" "1~561" ""
.Ix "Text functions" "XmTextGetSelectionPosition" "1~562" ""
.Ix "Text functions" "XmTextGetSource" "1~563" ""
.Ix "Text functions" "XmTextGetString" "1~564" ""
.Ix "Text functions" "XmTextGetTopCharacter" "1~565" ""
.Ix "Text functions" "XmTextInsert" "1~566" ""
.Ix "Text functions" "XmTextPaste" "1~567" ""
.Ix "Text functions" "XmTextPosToXY" "1~568" ""
.Ix "Text functions" "XmTextRemove" "1~570" ""
.Ix "Text functions" "XmTextReplace" "1~571" ""
.Ix "Text functions" "XmTextScroll" "1~572" ""
.Ix "Text functions" "XmTextSetAddMode" "1~573" ""
.Ix "Text functions" "XmTextSetEditable" "1~574" ""
.Ix "Text functions" "XmTextSetHighlight" "1~575" ""
.Ix "Text functions" "XmTextSetInsertionPosition" "1~576" ""
.Ix "Text functions" "XmTextSetMaxLength" "1~577" ""
.Ix "Text functions" "XmTextSetSelection" "1~578" ""
.Ix "Text functions" "XmTextSetSource" "1~579" ""
.Ix "Text functions" "XmTextSetString" "1~580" ""
.Ix "Text functions" "XmTextSetTopCharacter" "1~581" ""
.Ix "Text functions" "XmTextShowPosition" "1~582" ""
.Ix "Text functions" "XmTextXYToPos" "1~583" ""
.Ix "TextField functions" "XmTextFieldClearSelection" "1~531" ""
.Ix "TextField functions" "XmTextFieldCopy" "1~532" ""
.Ix "TextField functions" "XmTextFieldCut" "1~533" ""
.Ix "TextField functions" "XmTextFieldGetBaseline" "1~534" ""
.Ix "TextField functions" "XmTextFieldGetEditable" "1~535" ""
.Ix "TextField functions" "XmTextFieldGetInsertionPosition" "1~536" ""
.Ix "TextField functions" "XmTextFieldGetLastPosition" "1~537" ""
.Ix "TextField functions" "XmTextFieldGetMaxLength" "1~538" ""
.Ix "TextField functions" "XmTextFieldGetSelection" "1~539" ""
.Ix "TextField functions" "XmTextFieldGetSelectionPosition" "1~540" ""
.Ix "TextField functions" "XmTextFieldGetString" "1~541" ""
.Ix "TextField functions" "XmTextFieldInsert" "1~542" ""
.Ix "TextField functions" "XmTextFieldPaste" "1~543" ""
.Ix "TextField functions" "XmTextFieldPosToXY" "1~544" ""
.Ix "TextField functions" "XmTextFieldRemove" "1~545" ""
.Ix "TextField functions" "XmTextFieldReplace" "1~546" ""
.Ix "TextField functions" "XmTextFieldSetAddMode" "1~547" ""
.Ix "TextField functions" "XmTextFieldSetEditable" "1~548" ""
.Ix "TextField functions" "XmTextFieldSetHighlight" "1~549" ""
.Ix "TextField functions" "XmTextFieldSetInsertionPosition" "1~550" ""
.Ix "TextField functions" "XmTextFieldSetMaxLength" "1~551" ""
.Ix "TextField functions" "XmTextFieldSetSelection" "1~552" ""
.Ix "TextField functions" "XmTextFieldSetString" "1~553" ""
.Ix "TextField functions" "XmTextFieldShowPosition" "1~554" ""
.Ix "TextField functions" "XmTextFieldXYToPos" "1~555" ""
.Ix "title bar" "" "1~4" ""
.Ix "ToggleButton functions" "XmToggleButtonGetState" "1~600" ""
.Ix "ToggleButton functions" "XmToggleButtonSetState" "1~601" ""
.Ix "ToggleButtonGadget functions" "XmToggleButtonGadgetGetState" "1~598" ""
.Ix "ToggleButtonGadget functions" "XmToggleButtonGadgetSetState" "1~599" ""
.Ix "Toolkit functions" "XmTrackingLocate" "1~602" ""
.Ix "TopLevelShell" "" "1~70" ""
.Ix "TransientShell" "" "1~73" ""
.Iy "U"
.Ix "uid file" "" "1~33" ""
.Ix "uid file" "" "1~46" ""
.Ix "uid hierarchy" "" "1~45" ""
.Ix "uil compiler" "" "1~76" ""
.Ix "uil functions" "MrmCloseHierarchy" "1~45" ""
.Ix "uil functions" "MrmFetchColorLiteral" "1~46" ""
.Ix "uil functions" "MrmFetchIconLiteral" "1~47" ""
.Ix "uil functions" "MrmFetchLiteral" "1~48" ""
.Ix "uil functions" "MrmFetchSetValues" "1~49" ""
.Ix "uil functions" "MrmFetchWidget" "1~51" ""
.Ix "uil functions" "MrmFetchWidgetOverride" "1~53" ""
.Ix "uil functions" "MrmInitialize" "1~55" ""
.Ix "uil functions" "MrmOpenHierarchy" "1~56" ""
.Ix "uil functions" "MrmRegisterClass" "1~59" ""
.Ix "uil functions" "MrmRegisterNames" "1~60" ""
.Ix "uil functions" "MrmRegisterNamesInHierarchy" "1~61" ""
.Ix "uil functions" "Uil" "1~76" ""
.Ix "uil functions" "UilDumpSymbolTable" "1~80" ""
.Ix "uil" "" "1~33" ""
.Ix "Uil" "" "1~76" ""
.Ix "uil" "compiler" "1~33" ""
.Ix "UilDumpSymbolTable" "" "1~80" ""
.Ix "user interface database" "" "1~33" ""
.Ix "user interface language" "" "1~33" ""
.Ix "user interface language" "compiler" "1~33" ""
.Iy "V"
.Ix "VendorShell functions" "XmActivateProtocol" "1~97" ""
.Ix "VendorShell functions" "XmActivateWMProtocol" "1~98" ""
.Ix "VendorShell functions" "XmAddProtocolCallback" "1~99" ""
.Ix "VendorShell functions" "XmAddProtocols" "1~100" ""
.Ix "VendorShell functions" "XmAddTabGroup" "1~101" ""
.Ix "VendorShell functions" "XmAddWMProtocolCallback" "1~102" ""
.Ix "VendorShell functions" "XmAddWMProtocols" "1~103" ""
.Ix "VendorShell functions" "XmDeactivateProtocol" "1~228" ""
.Ix "VendorShell functions" "XmDeactivateWMProtocol" "1~229" ""
.Ix "VendorShell functions" "XmRemoveProtocolCallback" "1~398" ""
.Ix "VendorShell functions" "XmRemoveProtocols" "1~399" ""
.Ix "VendorShell functions" "XmRemoveWMProtocolCallback" "1~401" ""
.Ix "VendorShell functions" "XmRemoveWMProtocols" "1~402" ""
.Ix "VendorShell functions" "XmSetProtocolHooks" "1~465" ""
.Ix "VendorShell functions" "XmSetWMProtocolHooks" "1~466" ""
.Ix "VendorShell" "" "1~81" ""
.Ix "VirtualBindings" "" "1~86" ""
.Iy "W"
.Ix "widget class" "ApplicationShell" "1~34" ""
.Ix "widget class" "ArrowButton" "1~104" ""
.Ix "widget class" "ArrowButtonGadget" "1~109" ""
.Ix "widget class" "BulletinBoard" "1~113" ""
.Ix "widget class" "CascadeButton" "1~120" ""
.Ix "widget class" "CascadeButtonGadget" "1~126" ""
.Ix "widget class" "Command" "1~153" ""
.Ix "widget class" "Composite" "1~38" ""
.Ix "widget class" "Constraint" "1~40" ""
.Ix "widget class" "Core" "1~42" ""
.Ix "widget class" "DialogShell" "1~231" ""
.Ix "widget class" "DrawingArea" "1~235" ""
.Ix "widget class" "DrawnButton" "1~239" ""
.Ix "widget class" "FileSelectionBox" "1~246" ""
.Ix "widget class" "Form" "1~266" ""
.Ix "widget class" "Frame" "1~275" ""
.Ix "widget class" "Gadget" "1~278" ""
.Ix "widget class" "Label" "1~293" ""
.Ix "widget class" "LabelGadget" "1~300" ""
.Ix "widget class" "List" "1~306" ""
.Ix "widget class" "MainWindow" "1~345" ""
.Ix "widget class" "Manager" "1~353" ""
.Ix "widget class" "MenuShell" "1~360" ""
.Ix "widget class" "MessageBox" "1~364" ""
.Ix "widget class" "Object" "1~62" ""
.Ix "widget class" "OverrideShell" "1~63" ""
.Ix "widget class" "PanedWindow" "1~373" ""
.Ix "widget class" "Primitive" "1~378" ""
.Ix "widget class" "PushButton" "1~385" ""
.Ix "widget class" "PushButtonGadget" "1~392" ""
.Ix "widget class" "RectObj" "1~65" ""
.Ix "widget class" "RowColumn" "1~407" ""
.Ix "widget class" "Scale" "1~421" ""
.Ix "widget class" "ScrollBar" "1~430" ""
.Ix "widget class" "ScrolledWindow" "1~440" ""
.Ix "widget class" "SelectionBox" "1~447" ""
.Ix "widget class" "Separator" "1~455" ""
.Ix "widget class" "SeparatorGadget" "1~458" ""
.Ix "widget class" "Shell" "1~67" ""
.Ix "widget class" "Text" "1~502" ""
.Ix "widget class" "ToggleButton" "1~584" ""
.Ix "widget class" "ToggleButtonGadget" "1~592" ""
.Ix "widget class" "TopLevelShell" "1~70" ""
.Ix "widget class" "TransientShell" "1~73" ""
.Ix "widget class" "VendorShell" "1~81" ""
.Ix "widget class" "WMShell" "1~91" ""
.Ix "window manager" "" "1~3" ""
.Ix "window menu" "" "1~4" ""
.Ix "WMShell" "" "1~91" ""
.Iy "X"
.Ix "XmActivateProtocol" "" "1~97" ""
.Ix "XmActivateWMProtocol" "" "1~98" ""
.Ix "XmAddProtocolCallback" "" "1~99" ""
.Ix "XmAddProtocols" "" "1~100" ""
.Ix "XmAddTabGroup" "" "1~101" ""
.Ix "XmAddWMProtocolCallback" "" "1~102" ""
.Ix "XmAddWMProtocols" "" "1~103" ""
.Ix "XmArrowButton" "" "1~104" ""
.Ix "XmArrowButtonGadget" "" "1~109" ""
.Ix "XmBulletinBoard" "" "1~113" ""
.Ix "XmCascadeButton" "" "1~120" ""
.Ix "XmCascadeButtonGadget" "" "1~126" ""
.Ix "XmCascadeButtonGadgetHighlight" "" "1~131" ""
.Ix "XmCascadeButtonHighlight" "" "1~132" ""
.Ix "XmClipboardCancelCopy" "" "1~133" ""
.Ix "XmClipboardCopy" "" "1~134" ""
.Ix "XmClipboardCopyByName" "" "1~136" ""
.Ix "XmClipboardEndCopy" "" "1~137" ""
.Ix "XmClipboardEndRetrieve" "" "1~138" ""
.Ix "XmClipboardInquireCount" "" "1~139" ""
.Ix "XmClipboardInquireFormat" "" "1~140" ""
.Ix "XmClipboardInquireLength" "" "1~141" ""
.Ix "XmClipboardInquirePendingItems" "" "1~142" ""
.Ix "XmClipboardLock" "" "1~143" ""
.Ix "XmClipboardRegisterFormat" "" "1~144" ""
.Ix "XmClipboardRetrieve" "" "1~145" ""
.Ix "XmClipboardStartCopy" "" "1~147" ""
.Ix "XmClipboardStartRetrieve" "" "1~149" ""
.Ix "XmClipboardUndoCopy" "" "1~150" ""
.Ix "XmClipboardUnlock" "" "1~151" ""
.Ix "XmClipboardWithdrawFormat" "" "1~152" ""
.Ix "XmCommand" "" "1~153" ""
.Ix "XmCommandAppendValue" "" "1~159" ""
.Ix "XmCommandError" "" "1~160" ""
.Ix "XmCommandGetChild" "" "1~161" ""
.Ix "XmCommandSetValue" "" "1~162" ""
.Ix "XmConvertUnits" "" "1~163" ""
.Ix "XmCreateArrowButton" "" "1~165" ""
.Ix "XmCreateArrowButtonGadget" "" "1~166" ""
.Ix "XmCreateBulletinBoard" "" "1~167" ""
.Ix "XmCreateBulletinBoardDialog" "" "1~168" ""
.Ix "XmCreateCascadeButton" "" "1~169" ""
.Ix "XmCreateCascadeButtonGadget" "" "1~170" ""
.Ix "XmCreateCommand" "" "1~171" ""
.Ix "XmCreateDialogShell" "" "1~172" ""
.Ix "XmCreateDrawingArea" "" "1~173" ""
.Ix "XmCreateDrawnButton" "" "1~174" ""
.Ix "XmCreateErrorDialog" "" "1~175" ""
.Ix "XmCreateFileSelectionBox" "" "1~176" ""
.Ix "XmCreateFileSelectionDialog" "" "1~177" ""
.Ix "XmCreateForm" "" "1~178" ""
.Ix "XmCreateFormDialog" "" "1~179" ""
.Ix "XmCreateFrame" "" "1~180" ""
.Ix "XmCreateInformationDialog" "" "1~181" ""
.Ix "XmCreateLabel" "" "1~182" ""
.Ix "XmCreateLabelGadget" "" "1~183" ""
.Ix "XmCreateList" "" "1~184" ""
.Ix "XmCreateMainWindow" "" "1~185" ""
.Ix "XmCreateMenuBar" "" "1~186" ""
.Ix "XmCreateMenuShell" "" "1~187" ""
.Ix "XmCreateMessageBox" "" "1~188" ""
.Ix "XmCreateMessageDialog" "" "1~189" ""
.Ix "XmCreateOptionMenu" "" "1~190" ""
.Ix "XmCreatePanedWindow" "" "1~192" ""
.Ix "XmCreatePopupMenu" "" "1~193" ""
.Ix "XmCreatePromptDialog" "" "1~194" ""
.Ix "XmCreatePulldownMenu" "" "1~195" ""
.Ix "XmCreatePushButton" "" "1~197" ""
.Ix "XmCreatePushButtonGadget" "" "1~198" ""
.Ix "XmCreateQuestionDialog" "" "1~199" ""
.Ix "XmCreateRadioBox" "" "1~200" ""
.Ix "XmCreateRowColumn" "" "1~201" ""
.Ix "XmCreateScale" "" "1~202" ""
.Ix "XmCreateScrollBar" "" "1~203" ""
.Ix "XmCreateScrolledList" "" "1~204" ""
.Ix "XmCreateScrolledText" "" "1~205" ""
.Ix "XmCreateScrolledWindow" "" "1~207" ""
.Ix "XmCreateSelectionBox" "" "1~208" ""
.Ix "XmCreateSelectionDialog" "" "1~209" ""
.Ix "XmCreateSeparator" "" "1~210" ""
.Ix "XmCreateSeparatorGadget" "" "1~211" ""
.Ix "XmCreateSimpleCheckBox" "" "1~212" ""
.Ix "XmCreateSimpleMenuBar" "" "1~213" ""
.Ix "XmCreateSimpleOptionMenu" "" "1~214" ""
.Ix "XmCreateSimplePopupMenu" "" "1~215" ""
.Ix "XmCreateSimplePulldownMenu" "" "1~216" ""
.Ix "XmCreateSimpleRadioBox" "" "1~217" ""
.Ix "XmCreateText" "" "1~218" ""
.Ix "XmCreateTextField" "" "1~219" ""
.Ix "XmCreateToggleButton" "" "1~220" ""
.Ix "XmCreateToggleButtonGadget" "" "1~221" ""
.Ix "XmCreateWarningDialog" "" "1~222" ""
.Ix "XmCreateWorkArea" "" "1~223" ""
.Ix "XmCreateWorkingDialog" "" "1~224" ""
.Ix "XmCvtCTToXmString" "" "1~225" ""
.Ix "XmCvtStringToUnitType" "" "1~226" ""
.Ix "XmCvtXmStringToCT" "" "1~227" ""
.Ix "XmDeactivateProtocol" "" "1~228" ""
.Ix "XmDeactivateWMProtocol" "" "1~229" ""
.Ix "XmDestroyPixmap" "" "1~230" ""
.Ix "XmDialogShell" "" "1~231" ""
.Ix "XmDrawingArea" "" "1~235" ""
.Ix "XmDrawnButton" "" "1~239" ""
.Ix "XmFileSelectionBox" "" "1~246" ""
.Ix "XmFileSelectionBoxGetChild" "" "1~256" ""
.Ix "XmFileSelectionDoSearch" "" "1~257" ""
.Ix "XmFontList" "" "1~258" ""
.Ix "XmFontListAdd" "" "1~259" ""
.Ix "XmFontListCopy" "" "1~260" ""
.Ix "XmFontListCreate" "" "1~261" ""
.Ix "XmFontListFree" "" "1~262" ""
.Ix "XmFontListFreeFontContext" "" "1~263" ""
.Ix "XmFontListGetNextFont" "" "1~264" ""
.Ix "XmFontListInitFontContext" "" "1~265" ""
.Ix "XmForm" "" "1~266" ""
.Ix "XmFrame" "" "1~275" ""
.Ix "XmGadget" "" "1~278" ""
.Ix "XmGetAtomName" "" "1~282" ""
.Ix "XmGetColorCalculation" "" "1~283" ""
.Ix "XmGetColors" "" "1~284" ""
.Ix "XmGetDestination" "" "1~285" ""
.Ix "XmGetMenuCursor" "" "1~286" ""
.Ix "XmGetPixmap" "" "1~287" ""
.Ix "XmGetPostedFromWidget" "" "1~289" ""
.Ix "XmInstallImage" "" "1~290" ""
.Ix "XmInternAtom" "" "1~291" ""
.Ix "XmIsMotifWMRunning" "" "1~292" ""
.Ix "XmLabel" "" "1~293" ""
.Ix "XmLabelGadget" "" "1~300" ""
.Ix "XmList" "" "1~306" ""
.Ix "XmListAddItem" "" "1~320" ""
.Ix "XmListAddItems" "" "1~321" ""
.Ix "XmListAddItemUnselected" "" "1~322" ""
.Ix "XmListDeleteAllItems" "" "1~323" ""
.Ix "XmListDeleteItem" "" "1~324" ""
.Ix "XmListDeleteItems" "" "1~325" ""
.Ix "XmListDeleteItemsPos" "" "1~326" ""
.Ix "XmListDeletePos" "" "1~327" ""
.Ix "XmListDeselectAllItems" "" "1~328" ""
.Ix "XmListDeselectItem" "" "1~329" ""
.Ix "XmListDeselectPos" "" "1~330" ""
.Ix "XmListGetMatchPos" "" "1~331" ""
.Ix "XmListGetSelectedPos" "" "1~332" ""
.Ix "XmListItemExists" "" "1~333" ""
.Ix "XmListItemPos" "" "1~334" ""
.Ix "XmListReplaceItems" "" "1~335" ""
.Ix "XmListReplaceItemsPos" "" "1~336" ""
.Ix "XmListSelectItem" "" "1~337" ""
.Ix "XmListSelectPos" "" "1~338" ""
.Ix "XmListSetAddMode" "" "1~339" ""
.Ix "XmListSetBottomItem" "" "1~340" ""
.Ix "XmListSetBottomPos" "" "1~341" ""
.Ix "XmListSetHorizPos" "" "1~342" ""
.Ix "XmListSetItem" "" "1~343" ""
.Ix "XmListSetPos" "" "1~344" ""
.Ix "XmMainWindow" "" "1~345" ""
.Ix "XmMainWindowSep1" "" "1~349" ""
.Ix "XmMainWindowSep2" "" "1~350" ""
.Ix "XmMainWindowSep3" "" "1~351" ""
.Ix "XmMainWindowSetAreas" "" "1~352" ""
.Ix "XmManager" "" "1~353" ""
.Ix "XmMenuPosition" "" "1~359" ""
.Ix "XmMenuShell" "" "1~360" ""
.Ix "XmMessageBox" "" "1~364" ""
.Ix "XmMessageBoxGetChild" "" "1~370" ""
.Ix "XmOptionButtonGadget" "" "1~371" ""
.Ix "XmOptionLabelGadget" "" "1~372" ""
.Ix "XmPanedWindow" "" "1~373" ""
.Ix "XmPrimitive" "" "1~378" ""
.Ix "XmProcessTraversal" "" "1~384" ""
.Ix "XmPushButton" "" "1~385" ""
.Ix "XmPushButtonGadget" "" "1~392" ""
.Ix "XmRemoveProtocolCallback" "" "1~398" ""
.Ix "XmRemoveProtocols" "" "1~399" ""
.Ix "XmRemoveTabGroup" "" "1~400" ""
.Ix "XmRemoveWMProtocolCallback" "" "1~401" ""
.Ix "XmRemoveWMProtocols" "" "1~402" ""
.Ix "XmResolveAllPartOffsets" "" "1~403" ""
.Ix "XmResolvePartOffsets" "" "1~405" ""
.Ix "XmRowColumn" "" "1~407" ""
.Ix "XmScale" "" "1~421" ""
.Ix "XmScaleGetValue" "" "1~428" ""
.Ix "XmScaleSetValue" "" "1~429" ""
.Ix "XmScrollBar" "" "1~430" ""
.Ix "XmScrollBarGetValues" "" "1~438" ""
.Ix "XmScrollBarSetValues" "" "1~439" ""
.Ix "XmScrolledWindow" "" "1~440" ""
.Ix "XmScrolledWindowSetAreas" "" "1~446" ""
.Ix "XmSelectionBox" "" "1~447" ""
.Ix "XmSelectionBoxGetChild" "" "1~454" ""
.Ix "XmSeparator" "" "1~455" ""
.Ix "XmSeparatorGadget" "" "1~458" ""
.Ix "XmSetColorCalculation" "" "1~461" ""
.Ix "XmSetFontUnit" "" "1~462" ""
.Ix "XmSetFontUnits" "" "1~463" ""
.Ix "XmSetMenuCursor" "" "1~464" ""
.Ix "XmSetProtocolHooks" "" "1~465" ""
.Ix "XmSetWMProtocolHooks" "" "1~466" ""
.Ix "XmString" "" "1~467" ""
.Ix "XmStringBaseline" "" "1~468" ""
.Ix "XmStringByteCompare" "" "1~469" ""
.Ix "XmStringCompare" "" "1~470" ""
.Ix "XmStringConcat" "" "1~471" ""
.Ix "XmStringCopy" "" "1~472" ""
.Ix "XmStringCreate" "" "1~473" ""
.Ix "XmStringCreateLtoR" "" "1~474" ""
.Ix "XmStringCreateSimple" "" "1~475" ""
.Ix "XmStringDirection" "" "1~476" ""
.Ix "XmStringDirectionCreate" "" "1~477" ""
.Ix "XmStringDraw" "" "1~478" ""
.Ix "XmStringDrawImage" "" "1~479" ""
.Ix "XmStringDrawUnderline" "" "1~480" ""
.Ix "XmStringEmpty" "" "1~482" ""
.Ix "XmStringExtent" "" "1~483" ""
.Ix "XmStringFree" "" "1~484" ""
.Ix "XmStringFreeContext" "" "1~485" ""
.Ix "XmStringGetLtoR" "" "1~486" ""
.Ix "XmStringGetNextComponent" "" "1~487" ""
.Ix "XmStringGetNextSegment" "" "1~489" ""
.Ix "XmStringHasSubstring" "" "1~490" ""
.Ix "XmStringHeight" "" "1~491" ""
.Ix "XmStringInitContext" "" "1~492" ""
.Ix "XmStringLength" "" "1~493" ""
.Ix "XmStringLineCount" "" "1~494" ""
.Ix "XmStringNConcat" "" "1~495" ""
.Ix "XmStringNCopy" "" "1~496" ""
.Ix "XmStringPeekNextComponent" "" "1~497" ""
.Ix "XmStringSegmentCreate" "" "1~498" ""
.Ix "XmStringSeparatorCreate" "" "1~499" ""
.Ix "XmStringTable" "" "1~500" ""
.Ix "XmStringWidth" "" "1~501" ""
.Ix "XmText" "" "1~502" ""
.Ix "XmTextClearSelection" "" "1~521" ""
.Ix "XmTextCopy" "" "1~522" ""
.Ix "XmTextCut" "" "1~523" ""
.Ix "XmTextFieldClearSelection" "" "1~531" ""
.Ix "XmTextFieldCopy" "" "1~532" ""
.Ix "XmTextFieldCut" "" "1~533" ""
.Ix "XmTextFieldGetBaseline" "" "1~534" ""
.Ix "XmTextFieldGetEditable" "" "1~535" ""
.Ix "XmTextFieldGetInsertionPosition" "" "1~536" ""
.Ix "XmTextFieldGetLastPosition" "" "1~537" ""
.Ix "XmTextFieldGetMaxLength" "" "1~538" ""
.Ix "XmTextFieldGetSelection" "" "1~539" ""
.Ix "XmTextFieldGetSelectionPosition" "" "1~540" ""
.Ix "XmTextFieldGetString" "" "1~541" ""
.Ix "XmTextFieldInsert" "" "1~542" ""
.Ix "XmTextFieldPaste" "" "1~543" ""
.Ix "XmTextFieldPosToXY" "" "1~544" ""
.Ix "XmTextFieldRemove" "" "1~545" ""
.Ix "XmTextFieldReplace" "" "1~546" ""
.Ix "XmTextFieldSetAddMode" "" "1~547" ""
.Ix "XmTextFieldSetEditable" "" "1~548" ""
.Ix "XmTextFieldSetHighlight" "" "1~549" ""
.Ix "XmTextFieldSetInsertionPosition" "" "1~550" ""
.Ix "XmTextFieldSetMaxLength" "" "1~551" ""
.Ix "XmTextFieldSetSelection" "" "1~552" ""
.Ix "XmTextFieldSetString" "" "1~553" ""
.Ix "XmTextFieldShowPosition" "" "1~554" ""
.Ix "XmTextFieldXYToPos" "" "1~555" ""
.Ix "XmTextGetBaseline" "" "1~556" ""
.Ix "XmTextGetEditable" "" "1~557" ""
.Ix "XmTextGetInsertionPosition" "" "1~558" ""
.Ix "XmTextGetLastPosition" "" "1~559" ""
.Ix "XmTextGetMaxLength" "" "1~560" ""
.Ix "XmTextGetSelection" "" "1~561" ""
.Ix "XmTextGetSelectionPosition" "" "1~562" ""
.Ix "XmTextGetSource" "" "1~563" ""
.Ix "XmTextGetString" "" "1~564" ""
.Ix "XmTextGetTopCharacter" "" "1~565" ""
.Ix "XmTextInsert" "" "1~566" ""
.Ix "XmTextPaste" "" "1~567" ""
.Ix "XmTextPosition" "" "1~569" ""
.Ix "XmTextPosToXY" "" "1~568" ""
.Ix "XmTextRemove" "" "1~570" ""
.Ix "XmTextReplace" "" "1~571" ""
.Ix "XmTextScroll" "" "1~572" ""
.Ix "XmTextSetAddMode" "" "1~573" ""
.Ix "XmTextSetEditable" "" "1~574" ""
.Ix "XmTextSetHighlight" "" "1~575" ""
.Ix "XmTextSetInsertionPosition" "" "1~576" ""
.Ix "XmTextSetMaxLength" "" "1~577" ""
.Ix "XmTextSetSelection" "" "1~578" ""
.Ix "XmTextSetSource" "" "1~579" ""
.Ix "XmTextSetString" "" "1~580" ""
.Ix "XmTextSetTopCharacter" "" "1~581" ""
.Ix "XmTextShowPosition" "" "1~582" ""
.Ix "XmTextXYToPos" "" "1~583" ""
.Ix "XmToggleButton" "" "1~584" ""
.Ix "XmToggleButtonGadget" "" "1~592" ""
.Ix "XmToggleButtonGadgetGetState" "" "1~598" ""
.Ix "XmToggleButtonGadgetSetState" "" "1~599" ""
.Ix "XmToggleButtonGetState" "" "1~600" ""
.Ix "XmToggleButtonSetState" "" "1~601" ""
.Ix "XmTrackingLocate" "" "1~602" ""
.Ix "XmUninstallImage" "" "1~603" ""
.Ix "XmUpdateDisplay" "" "1~604" ""
.Ix "XmVaCreateSimpleCheckBox" "" "1~605" ""
.Ix "XmVaCreateSimpleMenuBar" "" "1~607" ""
.Ix "XmVaCreateSimpleOptionMenu" "" "1~609" ""
.Ix "XmVaCreateSimplePopupMenu" "" "1~611" ""
.Ix "XmVaCreateSimplePulldownMenu" "" "1~614" ""
.Ix "XmVaCreateSimpleRadioBox" "" "1~618" ""
...\"	index formatting macros
...\"
...\"     this simply restores one column text
.1C
