...\"	index formatting macros
...\"
...\"
...\"	Iy  --  called between letters of the alphabet
.de Iy
.if !\\$1 \{\
.	fl
.	sp 5v
.	ne .75i
.	in \\n(I#u						\" do indent
\s30\&\\$1\s0
.	sp 1
.	rm I! I@
'	br \}
..
...\"
...\"
...\"	Ix  --  called for an individual index item
.de Ix
'in \\n(I#u						\" do indent
.if !\\$1\\*(I! \{\
.br
.sp .5v                           	\" make sure we're at the start of a line
.ti 0							\" major is always at left margin
\&\\$1\c\"						\" and - output "Major"
.ds I! \\$1\"					\" save major name
.	rm I@
'	br \}
.ie \\$2\\*(I@ \{\
.	ie \\$4 , \\$3\c\"	\" same minor - just output page #
.	el , \fB\\$3\fP\c\"			\"     highlight version
'	br \}
.el \{\
.	br							\" make sure we're on a new line
.	fl
.	ie \\$4 \&\\$2, \&\\$3\c\"	and output "Minor, page#"
.	el \&\\$2, \fB\\$3\fP\c\"	\"     highlight version
.	ds I@ \\$2\"				\" save minor name
'	br \}
..
...\"
...\"	the string I! is used to hold the last major index name
.ds I!
...\"
...\"	the string I@ is used to hold the last minor index name
.ds I@
...\"
...\"	the register I# is used to hold the current indent
.nr I# .5i
...\"
...\"	to get around formatter and sorting limitations:
'fl
...\"
...\"
...\"
...\"	do everything in two column mode:
.2C
.rs
.nh			\" NO hyphenation
.na			\" no justification
.nr Hu 1
.HU "Index"
.tr ~-^\&\"	\" tilde becomes a dash, hat goes to null
.Iy "A"
.Ix "acceleration" "" "2~6" ""
.Ix "accelerators" "" "3~12" ""
.Ix "accelerators" "" "4~20" ""
.Ix "accelerators" "" "4~21" ""
.Ix "accelerators" "" "7~3" ""
.Ix "accelerators" "" "7~4" ""
.Ix "actions" "DialogBox" "4~22" ""
.Ix "activation" "" "7~4" ""
.Ix "activation" "basic" "3~12" ""
.Ix "activation" "component" "3~11" ""
.Ix "activation" "Menu system" "2~14" ""
.Ix "active voice" "" "6~5" ""
.Ix "active window" "" "2~1" ""
.Ix "acts requiring actions" "" "1~5" ""
.Ix "add mode" "" "3~5" ""
.Ix "addresses" "" "6~3" ""
.Ix "affirmative statements" "" "6~5" ""
.Ix "alignment" "horizontal" "4~19" ""
.Ix "alignment" "vertical" "4~19" ""
.Ix "alphanumeric date formats" "" "6~3" ""
.Ix "alphanumeric lists" "" "6~1" ""
.Ix "anchor toggle" "" "3~4" ""
.Ix "anchor" "" "3~3" ""
.Ix "anchor" "" "3~4" ""
.Ix "anchor" "" "3~6" ""
.Ix "ANS X3.159~1989" "" "6~1" ""
.Ix "ANSI C" "" "6~1" ""
.Ix "application design" "" "4~1" ""
.Ix "application modal" "" "4~22" ""
.Ix "application modal" "" "5~3" ""
.Ix "application title" "" "5~5" ""
.Ix "Apply" "" "4~22" ""
.Ix "Apply" "" "7~16" ""
.Ix "arrow pointer" "" "2~5" ""
.Ix "arrow pointer" "" "2~6" ""
.Ix "arrow pointer" "" "7~53" ""
.Ix "arrow pointer" "" "7~54" ""
.Ix "arrow pointer" "four~directional" "2~5" ""
.Ix "arrow pointer" "four~directional" "7~54" ""
.Ix "audience" "" "vii" ""
.Ix "autorepeat" "" "3~14" ""
.Iy "B"
.Ix "Balance~Beam" "" "3~3" ""
.Ix "base" "" "6~1" ""
.Ix "basic activation" "" "3~12" ""
.Ix "basic activation" "" "7~4" ""
.Ix "basic controls" "" "4~1" ""
.Ix "basic controls" "" "4~5" ""
.Ix "basic controls" "Cascade Button" "4~1" ""
.Ix "basic controls" "CheckButton" "4~2" ""
.Ix "basic controls" "Label" "4~1" ""
.Ix "basic controls" "OptionButton" "4~1" ""
.Ix "basic controls" "PushButton" "4~1" ""
.Ix "basic controls" "RadioButton" "4~2" ""
.Ix "basic controls" "Separator" "4~1" ""
.Ix "basic controls" "ToggleButton" "4~1" ""
.Ix "basic groups" "" "4~1" ""
.Ix "basic groups" "" "4~2" ""
.Ix "basic groups" "" "B~1" ""
.Ix "basic groups" "Menu" "4~2" ""
.Ix "basic groups" "MenuBar" "4~2" ""
.Ix "basic groups" "Panel" "4~2" ""
.Ix "BCustom" "" "2~3" ""
.Ix "BCustom" "" "2~4" ""
.Ix "BCustom" "" "7~36" ""
.Ix "BDrag" "" "2~3" ""
.Ix "BDrag" "" "2~4" ""
.Ix "BDrag" "" "7~36" ""
.Ix "BMenu" "" "2~3" ""
.Ix "BMenu" "" "2~4" ""
.Ix "box" "icon" "5~9" ""
.Ix "box" "icon" "7~33" ""
.Ix "BQuickCopy" "" "3~10" ""
.Ix "BQuickCopy" "" "7~59" ""
.Ix "BQuickCutDrag" "" "3~10" ""
.Ix "BQuickCutDrag" "" "7~59" ""
.Ix "BQuickPaste" "" "7~59" ""
.Ix "browse selections" "" "3~2" ""
.Ix "browse selections" "" "3~3" ""
.Ix "browse selections" "" "3~6" ""
.Ix "browse selections" "" "7~69" ""
.Ix "BSelect" "" "2~3" ""
.Ix "BSelect" "" "2~4" ""
.Ix "BSelect" "" "3~12" ""
.Ix "BSelect" "" "7~36" ""
.Ix "BToggle" "" "3~4" ""
.Ix "buttons" "" "5~5" ""
.Ix "buttons" "system Menu" "5~6" ""
.Ix "buttons" "window Menu" "5~6" ""
.Iy "C"
.Ix "can" "" "ix" ""
.Ix "Cancel" "" "4~23" ""
.Ix "Cancel" "" "7~16" ""
.Ix "canceling a selection" "" "3~6" ""
.Ix "Canvas" "" "4~2" ""
.Ix "Canvas" "" "4~4" ""
.Ix "Canvas" "" "4~6" ""
.Ix "Canvas" "" "7~8" ""
.Ix "Canvas" "" "7~22" ""
.Ix "Canvas" "" "B~1" ""
.Ix "CascadeButton" "" "2~7" ""
.Ix "CascadeButton" "" "4~1" ""
.Ix "CascadeButton" "" "7~6" ""
.Ix "CascadeButton" "" "7~9" ""
.Ix "CascadeButton" "" "B~1" ""
.Ix "caution pointer" "" "2~6" ""
.Ix "caution pointer" "" "7~54" ""
.Ix "certification checklist" "" "ix" ""
.Ix "CheckBox" "" "4~5" ""
.Ix "CheckButton" "" "4~2" ""
.Ix "CheckButton" "" "7~6" ""
.Ix "CheckButton" "" "7~10" ""
.Ix "CheckButton" "" "7~77" ""
.Ix "CheckButton" "" "B~1" ""
.Ix "choosing components" "" "4~1" ""
.Ix "Clear" "" "4~11" ""
.Ix "Clear" "" "7~19" ""
.Ix "Click" "" "2~4" ""
.Ix "click~to~type" "" "2~2" ""
.Ix "click~to~type" "" "7~28" ""
.Ix "client areas" "" "4~6" ""
.Ix "client areas" "" "5~4" ""
.Ix "clipboard selection actions" "" "3~11" ""
.Ix "Close" "" "4~10" ""
.Ix "Close" "" "5~7" ""
.Ix "Close" "" "7~23" ""
.Ix "Close" "" "7~79" ""
.Ix "collating sequences" "" "6~1" ""
.Ix "collections" "graphics~like" "3~1" ""
.Ix "collections" "list~like" "3~1" ""
.Ix "collections" "text~like" "3~1" ""
.Ix "colors" "" "1~4" ""
.Ix "columns" "aligning" "4~19" ""
.Ix "command area" "" "4~6" ""
.Ix "command area" "" "4~7" ""
.Ix "Command DialogBox" "" "4~13" ""
.Ix "Command DialogBox" "" "7~13" ""
.Ix "CommandBox" "" "7~12" ""
.Ix "common actions" "" "7~16" ""
.Ix "common DialogBox actions" "" "4~22" ""
.Ix "Common User Access" "" "vii" ""
.Ix "compliance conventions" "" "ix" ""
.Ix "component activation" "" "3~1" ""
.Ix "component activation" "" "3~11" ""
.Ix "component navigation" "" "2~11" ""
.Ix "components" "arranging" "4~18" ""
.Ix "components" "choosing" "4~1" ""
.Ix "components" "design" "4~28" ""
.Ix "components" "design" "7~1" ""
.Ix "components" "grouping" "4~18" ""
.Ix "components" "interactive" "4~4" ""
.Ix "components" "modal" "4~26" ""
.Ix "components" "multiple~choice" "4~4" ""
.Ix "components" "multiple~choice" "4~5" ""
.Ix "components" "Scrollable" "2~7" ""
.Ix "components" "simple" "4~26" ""
.Ix "components" "single~choice" "4~4" ""
.Ix "components" "single~choice" "4~5" ""
.Ix "components" "text" "7~73" ""
.Ix "components" "window" "5~3" ""
.Ix "Composite" "" "B~1" ""
.Ix "Composition" "" "4~3" ""
.Ix "Composition" "" "7~14" ""
.Ix "Composition" "" "7~38" ""
.Ix "configurability" "" "5~1" ""
.Ix "consistency" "" "1~4" ""
.Ix "context~sensitive help" "" "1~5" ""
.Ix "contrast" "screen objects" "1~4" ""
.Ix "control panel" "" "4~18" ""
.Ix "controls" "" "7~1" ""
.Ix "Copy" "" "4~11" ""
.Ix "Copy" "" "7~19" ""
.Ix "copying" "" "3~8" ""
.Ix "copying" "" "7~55" ""
.Ix "copying" "" "7~59" ""
.Ix "corner handles" "" "5~5" ""
.Ix "country~specific data formats" "" "6~2" ""
.Ix "currency" "" "6~3" ""
.Ix "cursor" "" "2~8" ""
.Ix "cursor" "item" "2~10" ""
.Ix "cursor" "location" "2~1" ""
.Ix "cursor" "location" "2~2" ""
.Ix "cursor" "location" "2~7" ""
.Ix "cursor" "location" "2~8" ""
.Ix "cursor" "location" "2~11" ""
.Ix "cursor" "location" "2~13" ""
.Ix "cursor" "location" "3~5" ""
.Ix "cursor" "text insertion" "2~1" ""
.Ix "cursor" "text insertion" "2~9" ""
.Ix "Cut" "" "4~11" ""
.Ix "Cut" "" "7~19" ""
.Ix "cutting" "" "7~55" ""
.Ix "cutting" "" "7~59" ""
.Iy "D"
.Ix "data formats" "country~specific" "6~2" ""
.Ix "data formats" "country~specific" "6~3" ""
.Ix "data formats" "currency" "6~3" ""
.Ix "date formats" "" "6~3" ""
.Ix "decimal separators" "" "6~2" ""
.Ix "decoration" "windows" "5~3" ""
.Ix "default action" "selecting" "3~13" ""
.Ix "default action" "selecting" "7~4" ""
.Ix "default action" "selecting" "7~15" ""
.Ix "default push button" "" "4~25" ""
.Ix "defaults" "" "4~25" ""
.Ix "delay" "" "4~27" ""
.Ix "Delete" "" "4~11" ""
.Ix "Delete" "" "7~19" ""
.Ix "deselecting" "" "3~6" ""
.Ix "Design" "" "1~1" ""
.Ix "design" "applications" "4~1" ""
.Ix "design" "components" "4~28" ""
.Ix "design" "components" "7~1" ""
.Ix "design" "DialogBox" "4~21" ""
.Ix "design" "graphical symbols" "6~4" ""
.Ix "design" "icons" "6~4" ""
.Ix "design" "pointer shapes" "2~5" ""
.Ix "design" "pointer shapes" "6~4" ""
.Ix "design" "pointer shapes" "7~53" ""
.Ix "design" "window manager" "5~1" ""
.Ix "destructive actions" "" "4~21" ""
.Ix "dialog box" "" "4~21" ""
.Ix "DialogBox" "" "2~11" ""
.Ix "DialogBox" "" "4~3" ""
.Ix "DialogBox" "" "4~4" ""
.Ix "DialogBox" "" "4~6" ""
.Ix "DialogBox" "" "4~12" ""
.Ix "DialogBox" "" "5~1" ""
.Ix "DialogBox" "" "7~16" ""
.Ix "DialogBox" "" "B~1" ""
.Ix "DialogBox" "actions" "4~22" ""
.Ix "DialogBox" "Command" "4~13" ""
.Ix "DialogBox" "Command" "7~13" ""
.Ix "DialogBox" "designing" "4~21" ""
.Ix "DialogBox" "Error" "4~16" ""
.Ix "DialogBox" "Error" "7~21" ""
.Ix "DialogBox" "FileSelection" "4~13" ""
.Ix "DialogBox" "FileSelection" "7~27" ""
.Ix "DialogBox" "groups" "4~1" ""
.Ix "DialogBox" "Information" "4~16" ""
.Ix "DialogBox" "Information" "7~35" ""
.Ix "DialogBox" "location" "4~24" ""
.Ix "DialogBox" "Message" "4~15" ""
.Ix "DialogBox" "Message" "7~45" ""
.Ix "DialogBox" "Prompt" "4~14" ""
.Ix "DialogBox" "Prompt" "7~56" ""
.Ix "DialogBox" "Question" "4~17" ""
.Ix "DialogBox" "Question" "7~58" ""
.Ix "DialogBox" "Selection" "4~15" ""
.Ix "DialogBox" "Selection" "7~71" ""
.Ix "DialogBox" "size" "4~24" ""
.Ix "DialogBox" "Warning" "4~17" ""
.Ix "DialogBox" "Warning" "7~78" ""
.Ix "DialogBox" "Working" "4~18" ""
.Ix "DialogBox" "Working" "7~81" ""
.Ix "direct manipulation" "" "1~2" ""
.Ix "direct manipulation" "" "1~3" ""
.Ix "direct manipulation" "" "2~3" ""
.Ix "direction of scanning" "" "ix" ""
.Ix "disabling components" "" "4~26" ""
.Ix "discontiguous selection" "" "3~2" ""
.Ix "discontiguous selection" "" "3~4" ""
.Ix "discontiguous selection" "" "3~6" ""
.Ix "discontiguous selection" "" "7~69" ""
.Ix "double~clicking" "" "3~14" ""
.Ix "double~clicking" "" "7~4" ""
.Ix "Drag" "" "2~4" ""
.Ix "dragging" "" "3~7" ""
.Ix "dragging" "" "3~8" ""
.Ix "dragging" "" "3~10" ""
.Ix "drag~and~drop model" "" "3~7" ""
.Ix "drag~and~drop model" "" "3~8" ""
.Ix "drag~and~drop model" "" "7~18" ""
.Iy "E"
.Ix "edge handles" "" "5~5" ""
.Ix "edit menu" "" "4~8" ""
.Ix "edit menu" "" "4~10" ""
.Ix "edit menu" "" "7~19" ""
.Ix "edit menu" "" "7~42" ""
.Ix "Edit" "" "7~42" ""
.Ix "Enlarge~Only" "" "3~3" ""
.Ix "Error DialogBox" "" "4~16" ""
.Ix "Error DialogBox" "" "7~21" ""
.Ix "ErrorDialog" "" "7~45" ""
.Ix "errors" "" "1~5" ""
.Ix "Exit" "" "4~10" ""
.Ix "Exit" "" "7~23" ""
.Ix "expert action" "" "3~14" ""
.Ix "expert action" "" "7~4" ""
.Ix "explicit destruction" "" "1~5" ""
.Ix "explicit focus" "" "2~2" ""
.Ix "explicit focus" "" "7~28" ""
.Ix "extension models" "" "3~3" ""
.Ix "extension models" "" "3~4" ""
.Iy "F"
.Ix "feedback" "" "1~5" ""
.Ix "feedback" "" "4~24" ""
.Ix "feedback" "" "4~27" ""
.Ix "field controls" "" "2~14" ""
.Ix "field controls" "" "4~1" ""
.Ix "field controls" "" "4~2" ""
.Ix "field controls" "" "7~22" ""
.Ix "field controls" "" "B~1" ""
.Ix "field controls" "Canvas" "7~22" ""
.Ix "field controls" "List" "7~22" ""
.Ix "field controls" "Sash" "7~22" ""
.Ix "field controls" "Scale" "7~22" ""
.Ix "field controls" "ScrollBar" "7~22" ""
.Ix "field controls" "text" "7~22" ""
.Ix "field groups" "" "2~14" ""
.Ix "field navigation" "" "2~13" ""
.Ix "fields" "" "2~11" ""
.Ix "file menu" "" "4~8" ""
.Ix "file menu" "" "4~9" ""
.Ix "file menu" "" "7~23" ""
.Ix "file menu" "" "7~42" ""
.Ix "File" "" "7~42" ""
.Ix "FileSelctionBox" "" "B~1" ""
.Ix "FileSelection DialogBox" "" "4~13" ""
.Ix "FileSelection DialogBox" "" "7~27" ""
.Ix "FileSelectionBox" "" "7~25" ""
.Ix "fill" "" "2~10" ""
.Ix "fixed layout" "" "4~19" ""
.Ix "flexibility" "" "1~2" ""
.Ix "flexibility" "" "4~27" ""
.Ix "focus policies" "" "2~1" ""
.Ix "focus policies" "" "2~2" ""
.Ix "focus policies" "" "7~28" ""
.Ix "focus" "explicit" "2~1" ""
.Ix "focus" "explicit" "2~2" ""
.Ix "focus" "explicit" "7~28" ""
.Ix "focus" "implicit" "2~1" ""
.Ix "focus" "implicit" "2~2" ""
.Ix "focus" "implicit" "7~28" ""
.Ix "focus" "keyboard" "2~1" ""
.Ix "focus" "keyboard" "2~2" ""
.Ix "formats" "addresses" "6~3" ""
.Ix "formats" "data" "6~2" ""
.Ix "formats" "dates" "6~3" ""
.Ix "formats" "messages" "6~5" ""
.Ix "formats" "telephone numbers" "6~3" ""
.Ix "formats" "time" "6~3" ""
.Ix "four~directional arrow pointer" "" "2~5" ""
.Ix "four~directional arrow pointer" "" "7~54" ""
.Ix "Frame" "" "4~3" ""
.Ix "Frame" "" "7~29" ""
.Ix "Frame" "" "7~30" ""
.Ix "Frame" "" "B~1" ""
.Ix "framing groups" "" "4~1" ""
.Ix "framing groups" "" "4~3" ""
.Ix "framing groups" "" "7~30" ""
.Ix "framing groups" "" "B~1" ""
.Ix "framing groups" "Frame" "4~3" ""
.Ix "framing groups" "MainWindow" "4~3" ""
.Ix "framing groups" "ScrolledWindow" "4~3" ""
.Ix "full toggle" "" "3~5" ""
.Iy "G"
.Ix "gain" "" "2~6" ""
.Ix "graphics tablet" "" "2~3" ""
.Ix "graphics tablet" "" "7~36" ""
.Ix "graphics" "" "4~25" ""
.Ix "graphics~like collections" "" "3~1" ""
.Ix "group reference" "" "7~1" ""
.Ix "grouping" "components" "4~18" ""
.Ix "grouping" "menu selections" "4~21" ""
.Ix "grouping" "separators" "6~2" ""
.Iy "H"
.Ix "handles" "" "5~5" ""
.Ix "Help Menu" "" "7~31" ""
.Ix "Help" "" "4~23" ""
.Ix "Help" "" "4~27" ""
.Ix "Help" "" "7~16" ""
.Ix "Help" "" "7~42" ""
.Ix "help" "activation" "3~13" ""
.Ix "help" "activation" "7~4" ""
.Ix "help" "context~sensitive" "1~5" ""
.Ix "help" "context~sensitive" "4~12" ""
.Ix "help" "contex~sensitive" "4~27" ""
.Ix "help" "index" "4~12" ""
.Ix "help" "menu" "4~8" ""
.Ix "help" "menu" "4~11" ""
.Ix "help" "menu" "7~42" ""
.Ix "help" "tutorial" "4~12" ""
.Ix "help" "version" "4~12" ""
.Ix "horizontal alignment" "" "4~19" ""
.Ix "hot key" "" "5~1" ""
.Ix "hotspot" "" "2~5" ""
.Ix "hotspot" "" "2~6" ""
.Ix "hotspot" "" "7~53" ""
.Ix "hourglass pointer" "" "2~5" ""
.Ix "hourglass pointer" "" "7~53" ""
.Iy "I"
.Ix "icon box" "" "5~9" ""
.Ix "icon Menu" "" "5~8" ""
.Ix "icon Menu" "" "7~32" ""
.Ix "IconBox" "" "7~33" ""
.Ix "iconized window" "" "5~2" ""
.Ix "icons" "" "5~2" ""
.Ix "icons" "" "5~8" ""
.Ix "icons" "" "6~4" ""
.Ix "icons" "" "7~34" ""
.Ix "immediacy of response" "" "1~3" ""
.Ix "implicit focus" "" "2~1" ""
.Ix "implicit focus" "" "2~2" ""
.Ix "implicit focus" "" "7~28" ""
.Ix "In Context" "" "7~31" ""
.Ix "Index" "" "4~12" ""
.Ix "Index" "" "7~31" ""
.Ix "Information Dialog" "" "7~35" ""
.Ix "Information DialogBox" "" "4~16" ""
.Ix "InformationDialog" "" "7~45" ""
.Ix "input devices" "" "2~1" ""
.Ix "input devices" "" "2~3" ""
.Ix "input devices" "" "7~36" ""
.Ix "input focus" "" "2~1" ""
.Ix "input" "keyboard" "viii" ""
.Ix "interactions" "" "4~24" ""
.Ix "interactive methods" "" "4~4" ""
.Ix "internal window navigation" "" "2~2" ""
.Ix "internationalization" "" "6~1" ""
.Ix "internationalization" "" "6~2" ""
.Ix "internationalization" "" "6~4" ""
.Ix "internationalization" "" "6~5" ""
.Ix "internationalization" "collating sequences" "6~1" ""
.Ix "internationalization" "data formats" "6~2" ""
.Ix "internationalization" "date formats" "6~3" ""
.Ix "internationalization" "numbers" "6~3" ""
.Ix "internationalization" "telephone numbers" "6~3" ""
.Ix "intraaplication consistency" "" "1~4" ""
.Ix "item cursor" "" "2~10" ""
.Ix "I~beam pointer" "" "2~5" ""
.Ix "I~beam pointer" "" "7~53" ""
.Iy "J"
.Ix "joystick" "" "2~3" ""
.Ix "joystick" "" "7~36" ""
.Iy "K"
.Ix "KActivate" "" "2~14" ""
.Ix "KActivate" "" "3~12" ""
.Ix "KBackSpace" "" "3~11" ""
.Ix "KBegin Data" "" "2~14" ""
.Ix "KBeginLine" "" "2~14" ""
.Ix "KCancel" "" "2~16" ""
.Ix "KCancel" "" "3~6" ""
.Ix "KCopy" "" "3~11" ""
.Ix "KCut" "" "3~11" ""
.Ix "KDelete" "" "3~11" ""
.Ix "KDeselectAll" "" "3~6" ""
.Ix "KDeSelectAll" "" "3~7" ""
.Ix "KDown" "" "2~12" ""
.Ix "KDown" "" "2~13" ""
.Ix "KDown" "" "2~15" ""
.Ix "KDown" "" "5~10" ""
.Ix "KDown" "" "7~47" ""
.Ix "KEnd Data" "" "2~14" ""
.Ix "KEnd Line" "" "2~14" ""
.Ix "key names" "virtual" "viii" ""
.Ix "keyboard" "" "2~7" ""
.Ix "keyboard" "events" "2~1" ""
.Ix "keyboard" "focus" "2~1" ""
.Ix "keyboard" "focus" "2~11" ""
.Ix "keyboard" "focus" "7~28" ""
.Ix "keyboard" "input" "2~1" ""
.Ix "keyboard" "input" "2~3" ""
.Ix "keyboard" "input" "7~36" ""
.Ix "keyboard" "input" "viii" ""
.Ix "keyboard" "navigation" "2~7" ""
.Ix "keyboard" "navigation" "7~47" ""
.Ix "keyboard" "selection actions" "3~7" ""
.Ix "keyboards" "" "viii" ""
.Ix "keyboard~based operations" "" "2~2" ""
.Ix "keys" "virtual" "7~36" ""
.Ix "keys" "virtual" "viii" ""
.Ix "KHelp" "" "3~13" ""
.Ix "KLeft" "" "2~12" ""
.Ix "KLeft" "" "2~13" ""
.Ix "KLeft" "" "2~15" ""
.Ix "KLeft" "" "7~47" ""
.Ix "KMenu" "" "2~14" ""
.Ix "KMenu" "" "7~47" ""
.Ix "KMenuBar" "" "2~14" ""
.Ix "KMenuBAr" "" "7~47" ""
.Ix "KNextFamilyWindow" "" "2~11" ""
.Ix "KNextFamilyWindow" "" "5~7" ""
.Ix "KNextFamilyWindow" "" "7~47" ""
.Ix "KNextField" "" "2~12" ""
.Ix "KNextField" "" "5~10" ""
.Ix "KNextField" "" "7~47" ""
.Ix "KNextMenu" "" "2~15" ""
.Ix "KNextWindow" "" "2~11" ""
.Ix "KNextWindow" "" "5~8" ""
.Ix "KNextWindow" "" "7~47" ""
.Ix "KPaste" "" "3~11" ""
.Ix "KPrevFamilyWindow" "" "2~11" ""
.Ix "KPrevFamilyWindow" "" "7~47" ""
.Ix "KPrevFammilyWindow" "" "5~7" ""
.Ix "KPrevField" "" "2~12" ""
.Ix "KPrevField" "" "5~10" ""
.Ix "KPrevField" "" "7~47" ""
.Ix "KPrevMenu" "" "2~15" ""
.Ix "KPrevWindow" "" "2~11" ""
.Ix "KPrevWindow" "" "5~8" ""
.Ix "KPrevWindow" "" "7~47" ""
.Ix "KPrimaryCopy" "" "3~9" ""
.Ix "KPrimaryCopy" "" "7~55" ""
.Ix "KPrimaryCut" "" "3~9" ""
.Ix "KPrimaryCut" "" "7~55" ""
.Ix "KPrimaryPaste" "" "3~9" ""
.Ix "KQuickCopy" "" "3~10" ""
.Ix "KQuickCut" "" "3~10" ""
.Ix "KQuickPaste" "" "3~10" ""
.Ix "KQuickPaste" "" "7~59" ""
.Ix "KReselect" "" "7~55" ""
.Ix "KRight" "" "2~12" ""
.Ix "KRight" "" "2~13" ""
.Ix "KRight" "" "2~15" ""
.Ix "KRight" "" "5~10" ""
.Ix "KRight" "" "7~47" ""
.Ix "KSelect" ".mS" "2~14" ""
.Ix "KSelectAll" "" "3~6" ""
.Ix "KSelectAll" "" "3~7" ""
.Ix "KUndo" "" "3~11" ""
.Ix "KUp" "" "2~12" ""
.Ix "KUp" "" "2~13" ""
.Ix "KUp" "" "2~15" ""
.Ix "KUp" "" "5~10" ""
.Ix "KUp" "" "7~47" ""
.Iy "L"
.Ix "Label" "" "4~1" ""
.Ix "Label" "" "4~4" ""
.Ix "Label" "" "4~6" ""
.Ix "Label" "" "7~6" ""
.Ix "Label" "" "7~37" ""
.Ix "Label" "" "B~1" ""
.Ix "language direction" "" "ix" ""
.Ix "language independent" "" "6~4" ""
.Ix "layout groups" "" "4~1" ""
.Ix "layout groups" "" "4~3" ""
.Ix "layout groups" "" "7~38" ""
.Ix "layout groups" "" "B~1" ""
.Ix "layout" "" "4~6" ""
.Ix "layout" "fixed" "4~19" ""
.Ix "layout" "resizing" "4~19" ""
.Ix "List" "" "4~2" ""
.Ix "List" "" "4~5" ""
.Ix "List" "" "7~22" ""
.Ix "List" "" "7~39" ""
.Ix "List" "" "B~1" ""
.Ix "list~like collections" "" "3~1" ""
.Ix "localization" "" "6~1" ""
.Ix "location cursor" "" "2~1" ""
.Ix "location cursor" "" "2~2" ""
.Ix "location cursor" "" "2~7" ""
.Ix "location cursor" "" "2~8" ""
.Ix "location cursor" "" "2~11" ""
.Ix "location cursor" "" "2~12" ""
.Ix "location cursor" "" "2~13" ""
.Ix "location cursor" "" "3~5" ""
.Ix "Lower" "" "5~7" ""
.Ix "Lower" "" "7~79" ""
.Iy "M"
.Ix "main component groups" "" "4~3" ""
.Ix "main windows" "" "2~11" ""
.Ix "main windows" "" "5~1" ""
.Ix "main windows" "" "5~2" ""
.Ix "MainWindow" "" "4~3" ""
.Ix "MainWindow" "" "4~4" ""
.Ix "MainWindow" "" "4~6" ""
.Ix "MainWindow" "" "4~7" ""
.Ix "MainWindow" "" "7~30" ""
.Ix "MainWindow" "" "7~41" ""
.Ix "MainWindow" "" "B~1" ""
.Ix "manipulation" "" "1~2" ""
.Ix "manipulation" "direct" "1~3" ""
.Ix "maximize button" "" "5~4" ""
.Ix "maximize button" "" "5~5" ""
.Ix "Maximize" "" "5~7" ""
.Ix "Maximize" "" "7~79" ""
.Ix "Menu system" "activation" "2~14" ""
.Ix "Menu traversal" "" "2~14" ""
.Ix "Menu" "" "4~2" ""
.Ix "Menu" "" "4~3" ""
.Ix "Menu" "" "4~4" ""
.Ix "Menu" "" "4~6" ""
.Ix "Menu" "" "7~7" ""
.Ix "Menu" "" "7~44" ""
.Ix "Menu" "" "B~1" ""
.Ix "MenuBar" "" "2~7" ""
.Ix "MenuBar" "" "2~14" ""
.Ix "MenuBar" "" "4~2" ""
.Ix "MenuBar" "" "4~6" ""
.Ix "MenuBar" "" "4~8" ""
.Ix "MenuBar" "" "7~7" ""
.Ix "MenuBar" "" "7~42" ""
.Ix "MenuBar" "" "B~1" ""
.Ix "menus" "" "5~6" ""
.Ix "menus" "" "7~44" ""
.Ix "menus" "designing" "4~19" ""
.Ix "menus" "edit" "4~8" ""
.Ix "menus" "edit" "4~10" ""
.Ix "menus" "edit" "7~19" ""
.Ix "menus" "edit" "7~42" ""
.Ix "menus" "file" "4~8" ""
.Ix "menus" "file" "4~9" ""
.Ix "menus" "file" "7~23" ""
.Ix "menus" "file" "7~42" ""
.Ix "menus" "help" "4~8" ""
.Ix "menus" "help" "4~11" ""
.Ix "menus" "help" "7~31" ""
.Ix "menus" "help" "7~42" ""
.Ix "menus" "icon" "5~8" ""
.Ix "menus" "icon" "7~32" ""
.Ix "menus" "navigation" "2~7" ""
.Ix "menus" "option" "7~44" ""
.Ix "menus" "option" "7~49" ""
.Ix "menus" "options" "4~8" ""
.Ix "menus" "popup" "7~44" ""
.Ix "menus" "pull down" "7~44" ""
.Ix "menus" "selections" "4~21" "ordering"
.Ix "menus" "structures" "4~21" ""
.Ix "menus" "system" "7~79" ""
.Ix "menus" "view" "4~8" ""
.Ix "menus" "view" "7~42" ""
.Ix "menus" "window" "5~2" ""
.Ix "menus" "window" "5~3" ""
.Ix "menus" "window" "5~6" ""
.Ix "menus" "window" "7~79" ""
.Ix "message area" "" "4~6" ""
.Ix "message area" "" "4~7" ""
.Ix "Message DialogBox" "" "4~15" ""
.Ix "Message DialogBoxes" "" "7~45" ""
.Ix "MessageBox" "" "B~1" ""
.Ix "messages" "" "6~5" ""
.Ix "metaphors" "real world" "1~2" ""
.Ix "Microsoft Windows" "" "vii" ""
.Ix "minimize button" "" "5~4" ""
.Ix "minimize button" "" "5~5" ""
.Ix "Minimize" "" "5~7" ""
.Ix "Minimize" "" "7~79" ""
.Ix "minmized window" "" "5~2" ""
.Ix "mnemonics" "" "3~7" ""
.Ix "mnemonics" "" "3~13" ""
.Ix "mnemonics" "" "4~20" ""
.Ix "mnemonics" "" "4~21" ""
.Ix "mnemonics" "" "7~4" ""
.Ix "mnemonics" "" "7~46" ""
.Ix "modeless" "" "4~22" ""
.Ix "modeless" "" "5~3" ""
.Ix "models" "" "7~1" ""
.Ix "models" "input" "2~1" ""
.Ix "models" "navigation" "2~1" ""
.Ix "models" "selection" "3~1" ""
.Ix "modes" "" "4~26" ""
.Ix "modifiers" "" "viii" ""
.Ix "motif window manager" "" "2~1" ""
.Ix "mouse input" "" "2~3" ""
.Ix "mouse pointer shapes" "" "2~5" ""
.Ix "mouse pointer shapes" "" "7~53" ""
.Ix "mouse pointer" "" "2~1" ""
.Ix "mouse pointer" "" "2~2" ""
.Ix "mouse" "" "2~1" ""
.Ix "mouse" "" "2~3" ""
.Ix "mouse" "" "2~7" ""
.Ix "mouse" "" "7~36" ""
.Ix "mouse~based navigation" "" "2~7" ""
.Ix "Move" "" "5~7" ""
.Ix "Move" "" "7~79" ""
.Ix "moving" "" "3~8" ""
.Ix "MultiClick" "" "2~4" ""
.Ix "MultiDrag" "" "2~4" ""
.Ix "multiple cascading submenus" "" "4~21" ""
.Ix "multiple MainWindows" "" "4~7" ""
.Ix "multiple selection" "" "3~2" ""
.Ix "multiple selection" "" "3~3" ""
.Ix "multiple selection" "" "3~6" ""
.Ix "multiple selections" "" "7~69" ""
.Ix "multiple windows" "" "5~5" ""
.Ix "multiple~choice components" "" "4~4" ""
.Ix "multiple~choice components" "" "4~5" ""
.Ix "MultiPress" "" "2~4" ""
.Ix "must" "" "ix" ""
.Iy "N"
.Ix "national numbers" "" "6~3" ""
.Ix "navigation" "" "1~3" ""
.Ix "navigation" "components" "2~11" ""
.Ix "navigation" "field" "2~13" ""
.Ix "navigation" "keyboard" "7~47" ""
.Ix "navigation" "model" "2~1" ""
.Ix "navigation" "model" "2~7" ""
.Ix "navigation" "mouse~based" "2~7" ""
.Ix "navigation" "scrollable components" "2~16" ""
.Ix "navigation" "window" "2~2" ""
.Ix "navigation" "window" "5~7" ""
.Ix "New" "" "4~9" ""
.Ix "New" "" "7~23" ""
.Ix "No" "" "4~22" ""
.Ix "No" "" "7~16" ""
.Ix "nominal keys" "" "viii" ""
.Ix "normal mode" "" "3~5" ""
.Ix "numbers" "postive and negative" "6~2" ""
.Ix "numeric date formats" "" "6~3" ""
.Iy "O"
.Ix "object~action selection model" "" "3~1" ""
.Ix "object~action selection model" "" "3~9" ""
.Ix "OK" "" "4~22" ""
.Ix "OK" "" "7~16" ""
.Ix "On Context" "" "4~12" ""
.Ix "On Help" "" "4~12" ""
.Ix "On Help" "" "7~31" ""
.Ix "On Keys" "" "4~12" ""
.Ix "On Keys" "" "7~31" ""
.Ix "On Version" "" "4~12" ""
.Ix "On Version" "" "7~31" ""
.Ix "On Window" "" "4~12" ""
.Ix "On Window" "" "7~31" ""
.Ix "Open" "" "4~9" ""
.Ix "Open" "" "7~23" ""
.Ix "operation" "keyboard only" "2~3" ""
.Ix "operation" "keyboard only" "7~36" ""
.Ix "operation" "keyboard~based" "2~2" ""
.Ix "operation" "mouse only" "2~3" ""
.Ix "operation" "mouse only" "7~36" ""
.Ix "OptionButton" "" "4~1" ""
.Ix "OptionButton" "" "4~5" ""
.Ix "OptionButton" "" "7~6" ""
.Ix "OptionButton" "" "7~49" ""
.Ix "OptionButton" "" "B~1" ""
.Ix "Options Menu" "" "2~7" ""
.Ix "Options menu" "" "4~8" ""
.Ix "Options Menu" "" "4~19" ""
.Ix "Options Menu" "" "7~42" ""
.Ix "Options Menu" "" "7~44" ""
.Ix "Options Menu" "" "7~49" ""
.Ix "ordering menu selections" "" "4~21" ""
.Ix "ordering" "functions" "1~2" ""
.Ix "ordering" "menu selections" "4~21" ""
.Ix "outline highlight" "" "2~9" ""
.Iy "P"
.Ix "Pack Icons" "" "5~9" ""
.Ix "PanedWindow" "" "4~2" ""
.Ix "PanedWindow" "" "4~3" ""
.Ix "PanedWindow" "" "4~19" ""
.Ix "PanedWindow" "" "7~38" ""
.Ix "PanedWindow" "" "7~51" ""
.Ix "PanedWindow" "" "7~62" ""
.Ix "PanedWindow" "" "B~1" ""
.Ix "Panel" "" "4~2" ""
.Ix "Panel" "" "4~5" ""
.Ix "Panel" "" "7~7" ""
.Ix "Panel" "" "7~52" ""
.Ix "Panel" "" "B~1" ""
.Ix "panels" "control" "4~18" ""
.Ix "Panes" "" "4~2" ""
.Ix "Panes" "" "4~19" ""
.Ix "Panes" "" "7~38" ""
.Ix "Panes" "" "7~51" ""
.Ix "parent windows" "" "5~3" ""
.Ix "parts" "window" "5~3" ""
.Ix "Paste" "" "4~11" ""
.Ix "Paste" "" "7~19" ""
.Ix "pasting" "" "3~8" ""
.Ix "pasting" "" "7~55" ""
.Ix "pasting" "" "7~59" ""
.Ix "pointer navigation" "" "2~7" ""
.Ix "pointer shapes" "" "2~5" ""
.Ix "pointer shapes" "" "6~4" ""
.Ix "pointer shapes" "" "7~53" ""
.Ix "pointers" "" "2~1" ""
.Ix "pointers" "" "2~3" ""
.Ix "pointers" "arrow" "2~5" ""
.Ix "pointers" "arrow" "7~53" ""
.Ix "pointers" "arrow" "7~54" ""
.Ix "pointers" "caution" "2~6" ""
.Ix "pointers" "caution" "7~54" ""
.Ix "pointers" "designing" "2~6" ""
.Ix "pointers" "four~directional arrow" "7~54" ""
.Ix "pointers" "four~directional" "2~5" "arrow""
.Ix "pointers" "hourglass" "2~5" ""
.Ix "pointers" "hourglass" "7~53" ""
.Ix "pointers" "I~beam" "2~5" ""
.Ix "pointers" "I~beam" "7~53" ""
.Ix "pointers" "mouse" "2~1" ""
.Ix "pointers" "mouse" "2~2" ""
.Ix "pointers" "question" "2~6" ""
.Ix "pointers" "question" "7~54" ""
.Ix "pointers" "resize" "2~5" ""
.Ix "pointers" "resize" "7~53" ""
.Ix "pointers" "sighting" "2~6" ""
.Ix "pointers" "sighting" "7~54" ""
.Ix "pointers" "track" "2~1" ""
.Ix "pointers" "warping" "2~7" ""
.Ix "pointers" "watch" "2~5" ""
.Ix "pointers" "watch" "7~53" ""
.Ix "pointers" "X" "2~5" ""
.Ix "pointers" "X" "7~53" ""
.Ix "pointing devices" "" "2~3" ""
.Ix "pointing devices" "" "7~36" ""
.Ix "Popup Menus" "" "2~7" ""
.Ix "Popup Menus" "" "4~5" ""
.Ix "Popup Menus" "" "4~19" ""
.Ix "Popup Menus" "" "7~4" ""
.Ix "Popup Menus" "" "7~44" ""
.Ix "positive and negative values" "" "6~2" ""
.Ix "POSIX 1003.1" "" "6~1" ""
.Ix "posted menu" "" "2~8" ""
.Ix "Presentation Manager" "" "vii" ""
.Ix "Press" "" "2~4" ""
.Ix "previewing" "" "3~14" ""
.Ix "primary modal" "" "4~22" ""
.Ix "primary modal" "" "5~3" ""
.Ix "primary selection" "" "3~7" ""
.Ix "primary selection" "" "3~8" ""
.Ix "primary selection" "" "7~55" ""
.Ix "primary selection" "focus~based" "3~8" ""
.Ix "primary selections" "" "7~55" ""
.Ix "primary transfer" "" "3~8" ""
.Ix "primary transfer" "" "3~9" ""
.Ix "primary transfer" "" "7~55" ""
.Ix "primary windows" "" "2~11" ""
.Ix "primary windows" "" "5~1" ""
.Ix "primary windows" "" "5~2" ""
.Ix "PrimaryCopy" "" "7~55" ""
.Ix "PrimaryCut" "" "7~55" ""
.Ix "PrimaryPaste" "" "7~55" ""
.Ix "Print" "" "4~9" ""
.Ix "Print" "" "7~23" ""
.Ix "progress" "" "4~27" ""
.Ix "progressive disclosure" "" "1~2" ""
.Ix "Prompt DialogBox" "" "4~14" ""
.Ix "Prompt DialogBox" "" "7~56" ""
.Ix "PromptBox" "" "B~1" ""
.Ix "proper names" "" "6~3" ""
.Ix "prototypes" "" "1~2" ""
.Ix "PullDown Menus" "" "2~7" ""
.Ix "PullDown Menus" "" "4~5" ""
.Ix "PullDown Menus" "" "4~19" ""
.Ix "PullDown" "" "7~44" ""
.Ix "pull~down menu" "" "4~8" ""
.Ix "pull~down menu" "" "7~42" ""
.Ix "PushButton" "" "4~1" ""
.Ix "PushButton" "" "4~4" ""
.Ix "PushButton" "" "7~6" ""
.Ix "PushButton" "" "7~57" ""
.Ix "PushButton" "" "B~1" ""
.Iy "Q"
.Ix "Question DialogBox" "" "4~17" ""
.Ix "Question DialogBox" "" "7~58" ""
.Ix "question pointer" "" "2~6" ""
.Ix "question pointer" "" "7~54" ""
.Ix "QuestionDialog" "" "7~45" ""
.Ix "quick selection" "" "3~9" ""
.Ix "quick selection" "" "7~59" ""
.Ix "quick transfer" "" "3~7" ""
.Ix "quick transfer" "" "3~9" ""
.Ix "quick transfer" "" "3~10" ""
.Ix "quick transfer" "" "7~59" ""
.Ix "QuickCopy" "" "7~59" ""
.Ix "QuickCut" "" "7~59" ""
.Ix "QuickExtend" "" "7~59" ""
.Iy "R"
.Ix "RadioBox" "" "4~5" ""
.Ix "RadioButton" "" "4~2" ""
.Ix "RadioButton" "" "7~6" ""
.Ix "RadioButton" "" "7~60" ""
.Ix "RadioButton" "" "7~77" ""
.Ix "RadioButton" "" "B~1" ""
.Ix "range selection" "" "3~2" ""
.Ix "range selection" "" "3~3" ""
.Ix "range selection" "" "3~6" ""
.Ix "range selection" "" "7~69" ""
.Ix "reading direction" "" "6~4" ""
.Ix "real world metaphors" "" "1~2" ""
.Ix "real~estate driven" "" "2~1" ""
.Ix "reference pages" "" "7~1" ""
.Ix "related items" "" "4~21" ""
.Ix "Release" "" "2~4" ""
.Ix "ReSelect" "" "3~3" ""
.Ix "Reset" "" "4~22" ""
.Ix "Reset" "" "7~16" ""
.Ix "resize border" "" "5~4" ""
.Ix "resize border" "" "5~5" ""
.Ix "resize pointer" "" "2~5" ""
.Ix "resize pointer" "" "7~53" ""
.Ix "resizing layout" "" "4~19" ""
.Ix "response immediacy" "" "1~3" ""
.Ix "restore" "" "5~5" ""
.Ix "Restore" "" "5~7" ""
.Ix "Restore" "" "7~79" ""
.Ix "Retry" "" "4~22" ""
.Ix "Retry" "" "7~16" ""
.Iy "S"
.Ix "Sash" "" "4~2" ""
.Ix "Sash" "" "7~22" ""
.Ix "Sash" "" "7~51" ""
.Ix "Sash" "" "7~62" ""
.Ix "Sash" "" "B~1" ""
.Ix "Save As" "" "4~9" ""
.Ix "Save As" "" "7~23" ""
.Ix "Save" "" "4~9" ""
.Ix "Save" "" "7~23" ""
.Ix "Scale" "" "4~2" ""
.Ix "Scale" "" "7~22" ""
.Ix "Scale" "" "7~64" ""
.Ix "Scale" "" "B~1" ""
.Ix "scanning direction" "" "6~4" ""
.Ix "scanning direction" "" "ix" ""
.Ix "scroll bar" "" "4~8" ""
.Ix "scrollable component navigation" "" "2~7" ""
.Ix "scrollable component navigation" "" "2~16" ""
.Ix "ScrollBar" "" "4~2" ""
.Ix "ScrollBar" "" "7~22" ""
.Ix "ScrollBar" "" "7~66" ""
.Ix "ScrollBar" "" "B~1" ""
.Ix "ScrollBars" "" "4~6" ""
.Ix "ScrollBars" "" "4~8" ""
.Ix "ScrolledWindow" "" "4~3" ""
.Ix "ScrolledWindow" "" "7~30" ""
.Ix "ScrolledWindow" "" "7~68" ""
.Ix "ScrolledWindow" "" "B~1" ""
.Ix "scrolling" "" "2~16" ""
.Ix "secondary selection mechanism" "" "3~10" ""
.Ix "secondary windows" "" "2~11" ""
.Ix "secondary windows" "" "5~1" ""
.Ix "secondary windows" "" "5~2" ""
.Ix "secondary windows" "" "5~3" ""
.Ix "secondary windows" "application modal" "5~3" ""
.Ix "secondary windows" "interaction" "5~3" ""
.Ix "secondary windows" "modeless" "5~3" ""
.Ix "secondary windows" "modes" "5~3" ""
.Ix "secondary windows" "primary modal" "5~3" ""
.Ix "secondary windows" "system modal" "5~3" ""
.Ix "SelectAll" "" "3~6" ""
.Ix "selection actions" "" "3~1" ""
.Ix "selection actions" "clipboard" "3~11" ""
.Ix "Selection DialogBox" "" "4~15" ""
.Ix "Selection DialogBox" "" "7~71" ""
.Ix "selection model" "" "3~1" ""
.Ix "selection model" "" "3~2" ""
.Ix "selection model" "object~action" "3~9" ""
.Ix "selection" "" "4~21" ""
.Ix "selection" "browse" "3~2" ""
.Ix "selection" "browse" "3~3" ""
.Ix "selection" "browse" "3~6" ""
.Ix "selection" "browse" "7~69" ""
.Ix "selection" "canceling" "3~6" ""
.Ix "selection" "default" "7~15" ""
.Ix "selection" "deselecting" "3~6" ""
.Ix "selection" "discontiguous" "3~2" ""
.Ix "selection" "discontiguous" "3~4" ""
.Ix "selection" "discontiguous" "3~6" ""
.Ix "selection" "discontiguous" "7~69" ""
.Ix "selection" "keyboard" "3~5" ""
.Ix "selection" "mnemonics" "3~7" ""
.Ix "selection" "model" "7~69" ""
.Ix "selection" "multiple" "3~2" ""
.Ix "selection" "multiple" "3~3" ""
.Ix "selection" "multiple" "3~6" ""
.Ix "selection" "multiple" "7~69" ""
.Ix "selection" "primary" "3~8" ""
.Ix "selection" "primary" "7~55" ""
.Ix "selection" "quick" "3~9" ""
.Ix "selection" "range" "3~2" ""
.Ix "selection" "range" "3~3" ""
.Ix "selection" "range" "3~6" ""
.Ix "selection" "range" "7~69" ""
.Ix "selection" "secondary" "3~10" ""
.Ix "selection" "single" "3~2" ""
.Ix "selection" "single" "3~5" ""
.Ix "selection" "single" "7~69" ""
.Ix "selection" "undoing" "3~6" ""
.Ix "SelectionBox" "" "7~70" ""
.Ix "SelectionBox" "" "B~1" ""
.Ix "selections" "quick" "7~59" ""
.Ix "Separator" "" "4~1" ""
.Ix "Separator" "" "7~6" ""
.Ix "Separator" "" "7~72" ""
.Ix "Separator" "" "B~1" ""
.Ix "separators" "decimal" "6~2" ""
.Ix "separators" "grouping" "6~2" ""
.Ix "separators" "thousands" "6~2" ""
.Ix "sequences" "collating" "6~1" ""
.Ix "shapes" "pointer" "2~5" ""
.Ix "shapes" "pointer" "7~53" ""
.Ix "should" "" "ix" ""
.Ix "sighting pointer" "" "2~6" ""
.Ix "sighting pointer" "" "7~54" ""
.Ix "single selection" "" "3~2" ""
.Ix "single selection" "" "3~5" ""
.Ix "single selection" "" "7~69" ""
.Ix "single~choice components" "" "4~4" ""
.Ix "single~choice components" "" "4~5" ""
.Ix "Size" "" "5~7" ""
.Ix "Size" "" "7~79" ""
.Ix "spring~loaded" "" "2~7" ""
.Ix "Stop" "" "4~22" ""
.Ix "Stop" "" "7~16" ""
.Ix "structures" "menu" "4~21" ""
.Ix "submenus" "multiple cascading" "4~21" ""
.Ix "system Menu button" "" "5~6" ""
.Ix "system menus" "" "7~79" ""
.Ix "system modal" "" "4~22" ""
.Ix "system modal" "" "5~3" ""
.Iy "T"
.Ix "tab groups" "" "2~11" ""
.Ix "Tear~Off Menus" "" "4~3" ""
.Ix "Tear~Off Menus" "" "5~3" ""
.Ix "telephone numbers" "" "6~3" ""
.Ix "Text" "" "4~2" ""
.Ix "Text" "" "4~4" ""
.Ix "Text" "" "4~6" ""
.Ix "Text" "" "7~22" ""
.Ix "Text" "" "B~1" ""
.Ix "Text" "component" "7~73" ""
.Ix "text" "cursor" "2~9" ""
.Ix "text" "insertion cursor" "2~1" ""
.Ix "text" "toggle" "3~4" ""
.Ix "text" "toggle" "3~5" ""
.Ix "text" "translation" "6~5" ""
.Ix "text~like collections" "" "3~1" ""
.Ix "thousands separators" "" "6~2" ""
.Ix "time formats" "" "6~3" ""
.Ix "title area" "" "5~4" ""
.Ix "title area" "" "5~5" ""
.Ix "title bar" "" "5~5" ""
.Ix "toggle models" "" "3~4" ""
.Ix "toggle" "anchor" "3~4" ""
.Ix "toggle" "full" "3~5" ""
.Ix "toggle" "text" "3~4" ""
.Ix "toggle" "text" "3~5" ""
.Ix "ToggleButton" "" "4~1" ""
.Ix "ToggleButton" "" "7~6" ""
.Ix "ToggleButton" "" "7~10" ""
.Ix "ToggleButton" "" "7~60" ""
.Ix "ToggleButton" "" "7~77" ""
.Ix "ToggleButton" "" "B~1" ""
.Ix "track ball" "" "2~3" ""
.Ix "track ball" "" "7~36" ""
.Ix "track listener" "" "2~1" ""
.Ix "track pointer" "" "2~1" ""
.Ix "transient windows" "" "2~11" ""
.Ix "transient windows" "" "5~1" ""
.Ix "transient windows" "" "5~2" ""
.Ix "translating text" "" "6~5" ""
.Ix "traversal" "keyboard" "2~3" ""
.Ix "Tutorial" "" "4~12" ""
.Ix "types of windows" "" "5~1" ""
.Ix "typographic conventions" "" "viii" ""
.Iy "U"
.Ix "undo" "" "1~5" ""
.Ix "undo" "" "3~6" ""
.Ix "Undo" "" "4~10" ""
.Ix "Undo" "" "7~19" ""
.Iy "V"
.Ix "values" "poitive and negative" "6~2" ""
.Ix "vertical alignment" "" "4~19" ""
.Ix "vertical panes" "" "4~19" ""
.Ix "view menu" "" "4~8" ""
.Ix "view menu" "" "7~42" ""
.Ix "View" "" "7~42" ""
.Ix "virtual bindings" "" "viii" ""
.Ix "virtual buttons" "" "A~1" ""
.Ix "virtual buttons" "" "viii" ""
.Ix "virtual key mechanism" "" "7~36" ""
.Ix "virtual keys" "" "7~36" ""
.Ix "virtual keys" "" "A~1" ""
.Ix "virtual keys" "" "viii" ""
.Ix "virtual modifier keys" "" "A~1" ""
.Ix "visual cue" "" "2~1" ""
.Iy "W"
.Ix "Warning DialogBox" "" "4~17" ""
.Ix "Warning DialogBox" "" "7~78" ""
.Ix "warnings" "" "1~5" ""
.Ix "warnings" "" "4~27" ""
.Ix "warping" "" "2~7" ""
.Ix "watch pointer" "" "2~5" ""
.Ix "watch pointer" "" "7~53" ""
.Ix "window control buttons" "" "5~5" ""
.Ix "window family" "" "2~11" ""
.Ix "window manager" "design" "5~1" ""
.Ix "window manager" "functions" "5~3" ""
.Ix "window manager" "functions" "5~5" ""
.Ix "window Menu button" "" "5~4" ""
.Ix "window Menu button" "" "5~6" ""
.Ix "window menus" "" "7~79" ""
.Ix "window navigation" "" "2~11" ""
.Ix "window panes" "" "7~38" ""
.Ix "window panes" "" "7~51" ""
.Ix "window panes" "" "7~62" ""
.Ix "windows " "menu" "4~8" "bar""
.Ix "windows" "active" "2~1" ""
.Ix "windows" "components" "5~3" ""
.Ix "windows" "decoration" "5~3" ""
.Ix "windows" "frame components" "5~5" ""
.Ix "windows" "iconized" "5~2" ""
.Ix "windows" "main" "2~11" ""
.Ix "windows" "main" "5~1" ""
.Ix "windows" "main" "5~2" ""
.Ix "windows" "main" "7~41" ""
.Ix "windows" "menu" "5~2" ""
.Ix "windows" "minmized" "5~2" ""
.Ix "windows" "modes" "5~3" ""
.Ix "windows" "multiple" "5~5" ""
.Ix "windows" "navigation of" "7~47" ""
.Ix "windows" "navigation" "2~2" ""
.Ix "windows" "navigation" "5~7" ""
.Ix "windows" "navigation" "7~47" ""
.Ix "windows" "panes" "4~19" ""
.Ix "windows" "parent" "5~3" ""
.Ix "windows" "primary" "2~11" ""
.Ix "windows" "primary" "5~1" ""
.Ix "windows" "primary" "5~2" ""
.Ix "windows" "primary" "7~41" ""
.Ix "windows" "resize border" "5~5" ""
.Ix "windows" "secondary" "2~11" ""
.Ix "windows" "secondary" "5~1" ""
.Ix "windows" "secondary" "5~2" ""
.Ix "windows" "secondary" "5~3" ""
.Ix "windows" "transient" "2~11" ""
.Ix "windows" "transient" "5~1" ""
.Ix "windows" "transient" "5~2" ""
.Ix "windows" "types" "5~1" ""
.Ix "Working DialogBox" "" "4~18" ""
.Ix "Working DialogBox" "" "7~81" ""
.Ix "WorkingDialog" "" "7~45" ""
.Iy "X"
.Ix "X pointer" "" "2~5" ""
.Ix "X pointer" "" "7~53" ""
.Iy "Y"
.Ix "Yes" "" "4~22" ""
.Ix "Yes" "" "7~16" ""
.Iy "Z"
.Ix "zoom feature" "" "2~6" ""
...\"	index formatting macros
...\"
...\"     this simply restores one column text
.1C
