.TH macherr 1 3/25/87
.CM 4
.SH NAME
.nf
macherr \- print a Mach-related error message on stdout
.SH SYNOPSIS
.nf
    macherr [errno]

.SH DESCRIPTION
.I macherr
calls the 
.I mach_error_string
library routine and prints out the returned string on stdout.
If an errno is not input, 
.I macherr
will prompt for one.
 
.SH "SEE ALSO"
mach_error(3)
