...\"	index formatting macros
...\"
...\"
...\"	Iy  --  called between letters of the alphabet
.de Iy
.if !\\$1 \{\
.	fl
.	sp 5v
.	ne .75i
.	in \\n(I#u						\" do indent
\s30\&\\$1\s0
.	sp 1
.	rm I! I@
'	br \}
..
...\"
...\"
...\"	Ix  --  called for an individual index item
.de Ix
'in \\n(I#u						\" do indent
.if !\\$1\\*(I! \{\
.br
.sp .5v                           	\" make sure we're at the start of a line
.ti 0							\" major is always at left margin
\&\\$1\c\"						\" and - output "Major"
.ds I! \\$1\"					\" save major name
.	rm I@
'	br \}
.ie \\$2\\*(I@ \{\
.	ie \\$4 , \\$3\c\"	\" same minor - just output page #
.	el , \fB\\$3\fP\c\"			\"     highlight version
'	br \}
.el \{\
.	br							\" make sure we're on a new line
.	fl
.	ie \\$4 \&\\$2, \&\\$3\c\"	and output "Minor, page#"
.	el \&\\$2, \fB\\$3\fP\c\"	\"     highlight version
.	ds I@ \\$2\"				\" save minor name
'	br \}
..
...\"
...\"	the string I! is used to hold the last major index name
.ds I!
...\"
...\"	the string I@ is used to hold the last minor index name
.ds I@
...\"
...\"	the register I# is used to hold the current indent
.nr I# .5i
...\"
...\"	to get around formatter and sorting limitations:
'fl
...\"
...\"
...\"
...\"	do everything in two column mode:
.2C
.rs
.nh			\" NO hyphenation
.na			\" no justification
.nr Hu 1
.HU "Index"
.tr ~-^\&\"	\" tilde becomes a dash, hat goes to null
.Ix ".mwmrc" "" "2~12" ""
.Ix ".mwmrc" "" "2~23" ""
.Ix ".Xdefaults" "" "2~6" ""
.Iy "A"
.Ix "application environment" "" "1~1" "1"
.Ix "ApplicationShell" "" "2~33" ""
.Ix "atoms" "" "2~276" ""
.Ix "atoms" "" "2~283" ""
.Iy "B"
.Ix "borders" "resize" "2~4" ""
.Iy "C"
.Ix "CascadeButton functions" "XmCascadeButtonHighlight" "2~126" ""
.Ix "CascadeButtonGadget functions" "XmCascadeButtonGadgetHighlight" "2~125" ""
.Ix "click to type" "" "2~15" ""
.Ix "clipboard functions" "XmClipboardCancelCopy" "2~127" ""
.Ix "clipboard functions" "XmClipboardCopy" "2~128" ""
.Ix "clipboard functions" "XmClipboardCopyByName" "2~130" ""
.Ix "clipboard functions" "XmClipboardEndCopy" "2~132" ""
.Ix "clipboard functions" "XmClipboardEndRetrieve" "2~133" ""
.Ix "clipboard functions" "XmClipboardInquireCount" "2~134" ""
.Ix "clipboard functions" "XmClipboardInquireFormat" "2~136" ""
.Ix "clipboard functions" "XmClipboardInquireLength" "2~138" ""
.Ix "clipboard functions" "XmClipboardInquirePendingItems" "2~140" ""
.Ix "clipboard functions" "XmClipboardLock" "2~142" ""
.Ix "clipboard functions" "XmClipboardRegisterFormat" "2~143" ""
.Ix "clipboard functions" "XmClipboardRetrieve" "2~144" ""
.Ix "clipboard functions" "XmClipboardStartCopy" "2~146" ""
.Ix "clipboard functions" "XmClipboardStartRetrieve" "2~148" ""
.Ix "clipboard functions" "XmClipboardUndoCopy" "2~149" ""
.Ix "clipboard functions" "XmClipboardUnlock" "2~150" ""
.Ix "clipboard functions" "XmClipboardWithdrawFormat" "2~151" ""
.Ix "Color functions" "XmGetColors" "2~277" ""
.Ix "Command functions" "XmCommandAppendValue" "2~158" ""
.Ix "Command functions" "XmCommandError" "2~159" ""
.Ix "Command functions" "XmCommandGetChild" "2~160" ""
.Ix "Command functions" "XmCommandSetValue" "2~161" ""
.Ix "Composite" "" "2~37" ""
.Ix "compound string functions" "XmCvtCTToXmString" "2~221" ""
.Ix "compound string functions" "XmCvtXmStringToCT" "2~222" ""
.Ix "compound string functions" "XmFontListAdd" "2~254" ""
.Ix "compound string functions" "XmFontListCreate" "2~255" ""
.Ix "compound string functions" "XmFontListFree" "2~256" ""
.Ix "compound string functions" "XmStringBaseline" "2~453" ""
.Ix "compound string functions" "XmStringByteCompare" "2~454" ""
.Ix "compound string functions" "XmStringCompare" "2~455" ""
.Ix "compound string functions" "XmStringConcat" "2~456" ""
.Ix "compound string functions" "XmStringCopy" "2~457" ""
.Ix "compound string functions" "XmStringCreate" "2~458" ""
.Ix "compound string functions" "XmStringCreateSimple" "2~459" ""
.Ix "compound string functions" "XmStringDraw" "2~461" ""
.Ix "compound string functions" "XmStringDrawImage" "2~462" ""
.Ix "compound string functions" "XmStringDrawUnderline" "2~464" ""
.Ix "compound string functions" "XmStringEmpty" "2~466" ""
.Ix "compound string functions" "XmStringExtent" "2~467" ""
.Ix "compound string functions" "XmStringFree" "2~468" ""
.Ix "compound string functions" "XmStringHasSubstring" "2~469" ""
.Ix "compound string functions" "XmStringHeight" "2~470" ""
.Ix "compound string functions" "XmStringLength" "2~471" ""
.Ix "compound string functions" "XmStringLineCount" "2~472" ""
.Ix "compound string functions" "XmStringNConcat" "2~473" ""
.Ix "compound string functions" "XmStringNCopy" "2~474" ""
.Ix "compound string functions" "XmStringSeparatorCreate" "2~475" ""
.Ix "compound string functions" "XmStringWidth" "2~477" ""
.Ix "conformance" "" "1~3" ""
.Ix "conformance" "" "1~4" ""
.Ix "Constraint" "" "2~40" ""
.Ix "Core" "" "2~42" ""
.Ix "creation functions" "XmCreateArrowButton" "2~163" ""
.Ix "creation functions" "XmCreateArrowButtonGadget" "2~164" ""
.Ix "creation functions" "XmCreateBulletinBoard" "2~165" ""
.Ix "creation functions" "XmCreateBulletinBoardDialog" "2~166" ""
.Ix "creation functions" "XmCreateCascadeButton" "2~167" ""
.Ix "creation functions" "XmCreateCascadeButtonGadget" "2~168" ""
.Ix "creation functions" "XmCreateCommand" "2~169" ""
.Ix "creation functions" "XmCreateDialogShell" "2~170" ""
.Ix "creation functions" "XmCreateDrawingArea" "2~171" ""
.Ix "creation functions" "XmCreateDrawnButton" "2~172" ""
.Ix "creation functions" "XmCreateErrorDialog" "2~173" ""
.Ix "creation functions" "XmCreateFileSelectionBox" "2~174" ""
.Ix "creation functions" "XmCreateFileSelectionDialog" "2~175" ""
.Ix "creation functions" "XmCreateForm" "2~176" ""
.Ix "creation functions" "XmCreateFormDialog" "2~177" ""
.Ix "creation functions" "XmCreateFrame" "2~178" ""
.Ix "creation functions" "XmCreateInformationDialog" "2~179" ""
.Ix "creation functions" "XmCreateLabel" "2~180" ""
.Ix "creation functions" "XmCreateLabelGadget" "2~181" ""
.Ix "creation functions" "XmCreateList" "2~182" ""
.Ix "creation functions" "XmCreateMainWindow" "2~183" ""
.Ix "creation functions" "XmCreateMenuBar" "2~184" ""
.Ix "creation functions" "XmCreateMenuShell" "2~186" ""
.Ix "creation functions" "XmCreateMessageBox" "2~187" ""
.Ix "creation functions" "XmCreateMessageDialog" "2~188" ""
.Ix "creation functions" "XmCreateOptionMenu" "2~189" ""
.Ix "creation functions" "XmCreatePanedWindow" "2~191" ""
.Ix "creation functions" "XmCreatePopupMenu" "2~192" ""
.Ix "creation functions" "XmCreatePromptDialog" "2~194" ""
.Ix "creation functions" "XmCreatePulldownMenu" "2~195" ""
.Ix "creation functions" "XmCreatePushButton" "2~197" ""
.Ix "creation functions" "XmCreatePushButtonGadget" "2~198" ""
.Ix "creation functions" "XmCreateQuestionDialog" "2~199" ""
.Ix "creation functions" "XmCreateRadioBox" "2~200" ""
.Ix "creation functions" "XmCreateRowColumn" "2~201" ""
.Ix "creation functions" "XmCreateScale" "2~202" ""
.Ix "creation functions" "XmCreateScrollBar" "2~203" ""
.Ix "creation functions" "XmCreateScrolledList" "2~204" ""
.Ix "creation functions" "XmCreateScrolledText" "2~206" ""
.Ix "creation functions" "XmCreateScrolledWindow" "2~208" ""
.Ix "creation functions" "XmCreateSelectionBox" "2~209" ""
.Ix "creation functions" "XmCreateSelectionDialog" "2~211" ""
.Ix "creation functions" "XmCreateSeparator" "2~213" ""
.Ix "creation functions" "XmCreateSeparatorGadget" "2~214" ""
.Ix "creation functions" "XmCreateText" "2~215" ""
.Ix "creation functions" "XmCreateToggleButton" "2~216" ""
.Ix "creation functions" "XmCreateToggleButtonGadget" "2~217" ""
.Ix "creation functions" "XmCreateWarningDialog" "2~218" ""
.Ix "creation functions" "XmCreateWorkArea" "2~219" ""
.Ix "creation functions" "XmCreateWorkingDialog" "2~220" ""
.Iy "D"
.Ix "data types" "XmFontList" "2~253" ""
.Ix "data types" "XmString" "2~452" ""
.Ix "data types" "XmStringDirection" "2~460" ""
.Ix "data types" "XmStringTable" "2~476" ""
.Ix "data types" "XmTextPosition" "2~513" ""
.Iy "E"
.Ix "explicit" "" "2~15" ""
.Ix "explicit" "" "2~6" ""
.Iy "F"
.Ix "FileSelectionBox functions" "XmFileSelectionBoxGetChild" "2~250" ""
.Ix "FileSelectionBox functions" "XmFileSelectionDoSearch" "2~252" ""
.Ix "focus policy" "click to type" "2~15" ""
.Ix "focus policy" "click to type" "2~6" ""
.Ix "focus policy" "explicit" "2~15" ""
.Ix "focus policy" "explicit" "2~6" ""
.Ix "focus policy" "pointer" "2~15" ""
.Ix "focus policy" "real estate" "2~15" ""
.Ix "focus policy" "real estate" "2~6" ""
.Ix "full use" "" "1~5" ""
.Ix "full use" "" "1~6" ""
.Ix "full use" "" "1~6" "1"
.Iy "I"
.Ix "icon box" "" "2~5" ""
.Ix "icons" "" "2~4" ""
.Ix "implementation" "" "1~1" "1"
.Ix "input focus" "" "2~15" ""
.Ix "input focus" "" "2~6" ""
.Ix "input focus" "click to type" "2~15" ""
.Ix "input focus" "click to type" "2~6" ""
.Ix "input focus" "explicit" "2~15" ""
.Ix "input focus" "explicit" "2~6" ""
.Ix "input focus" "pointer" "2~15" ""
.Ix "input focus" "real estate" "2~15" ""
.Ix "internal interfaces" "" "1~2" "1"
.Iy "L"
.Ix "List functions" "XmListAddItem" "2~311" ""
.Ix "List functions" "XmListAddItems" "2~312" ""
.Ix "List functions" "XmListAddItemUnselected" "2~313" ""
.Ix "List functions" "XmListDeleteAllItems" "2~314" ""
.Ix "List functions" "XmListDeleteItem" "2~315" ""
.Ix "List functions" "XmListDeleteItems" "2~316" ""
.Ix "List functions" "XmListDeleteItemsPos" "2~317" ""
.Ix "List functions" "XmListDeletePos" "2~318" ""
.Ix "List functions" "XmListDeselectAllItems" "2~319" ""
.Ix "List functions" "XmListDeselectItem" "2~320" ""
.Ix "List functions" "XmListDeselectPos" "2~321" ""
.Ix "List functions" "XmListGetMatchPos" "2~322" ""
.Ix "List functions" "XmListGetSelectedPos" "2~323" ""
.Ix "List functions" "XmListItemExists" "2~324" ""
.Ix "List functions" "XmListItemPos" "2~325" ""
.Ix "List functions" "XmListReplaceItems" "2~326" ""
.Ix "List functions" "XmListReplaceItemsPos" "2~327" ""
.Ix "List functions" "XmListSelectItem" "2~328" ""
.Ix "List functions" "XmListSelectPos" "2~329" ""
.Ix "List functions" "XmListSetAddMode" "2~330" ""
.Ix "List functions" "XmListSetBottomItem" "2~331" ""
.Ix "List functions" "XmListSetBottomPos" "2~332" ""
.Ix "List functions" "XmListSetHorizPos" "2~333" ""
.Ix "List functions" "XmListSetItem" "2~334" ""
.Ix "List functions" "XmListSetPos" "2~335" ""
.Iy "M"
.Ix "MainWindow functions" "XmMainWindowSep1" "2~340" ""
.Ix "MainWindow functions" "XmMainWindowSep2" "2~341" ""
.Ix "MainWindow functions" "XmMainWindowSep3" "2~342" ""
.Ix "MainWindow functions" "XmMainWindowSetAreas" "2~343" ""
.Ix "manual page" "format" "x" ""
.Ix "maximize button" "" "2~4" ""
.Ix "maximize" "" "2~4" ""
.Ix "membership review" "" "1~5" "1"
.Ix "menu button" "" "2~4" ""
.Ix "menu" "" "2~4" ""
.Ix "MessageBox functions" "XmMessageBoxGetChild" "2~360" ""
.Ix "minimize button" "" "2~4" ""
.Ix "minimize" "" "2~4" ""
.Ix "MrmCloseHierarchy" "" "2~45" ""
.Ix "MrmFetchColorLiteral" "" "2~46" ""
.Ix "MrmFetchIconLiteral" "" "2~47" ""
.Ix "MrmFetchLiteral" "" "2~48" ""
.Ix "MrmFetchSetValues" "" "2~49" ""
.Ix "MrmFetchWidget" "" "2~51" ""
.Ix "MrmFetchWidgetOverride" "" "2~53" ""
.Ix "MrmInitialize" "" "2~55" ""
.Ix "MrmOpenHierarchy" "" "2~56" ""
.Ix "MrmRegisterClass" "" "2~59" ""
.Ix "MrmRegisterNames" "" "2~60" ""
.Ix "MrmRegisterNamesInHierarchy" "" "2~62" ""
.Ix "mwm" "" "2~3" ""
.Ix "mwm" "resources" "2~10" ""
.Ix "mwm" "resources" "2~12" ""
.Ix "mwm" "resources" "2~13" ""
.Ix "mwm" "resources" "2~14" ""
.Ix "mwm" "resources" "2~15" ""
.Ix "mwm" "resources" "2~16" ""
.Ix "mwm" "resources" "2~17" ""
.Ix "mwm" "resources" "2~18" ""
.Ix "mwm" "resources" "2~20" ""
.Ix "mwm" "resources" "2~21" ""
.Ix "mwm" "resources" "2~22" ""
.Ix "mwm" "resources" "2~23" ""
.Ix "mwm" "resources" "2~7" ""
.Ix "mwm" "resources" "2~8" ""
.Ix "mwm" "resources" "2~9" ""
.Iy "O"
.Ix "Object" "" "2~64" ""
.Ix "OverrideShell" "" "2~65" ""
.Iy "P"
.Ix "pixmaps" "" "2~225" ""
.Ix "pixmaps" "" "2~279" ""
.Ix "pixmaps" "" "2~282" ""
.Ix "pixmaps" "" "2~548" ""
.Ix "pointer" "" "2~15" ""
.Ix "portability interface" "" "1~2" "1"
.Ix "protocols" "" "2~223" ""
.Ix "protocols" "" "2~224" ""
.Ix "protocols" "" "2~388" ""
.Ix "protocols" "" "2~389" ""
.Ix "protocols" "" "2~391" ""
.Ix "protocols" "" "2~392" ""
.Ix "protocols" "" "2~450" ""
.Ix "protocols" "" "2~451" ""
.Ix "protocols" "" "2~91" ""
.Ix "protocols" "" "2~92" ""
.Ix "protocols" "" "2~93" ""
.Ix "protocols" "" "2~94" ""
.Ix "protocols" "" "2~96" ""
.Ix "protocols" "" "2~97" ""
.Iy "R"
.Ix "real estate" "" "2~15" ""
.Ix "real estate" "" "2~6" ""
.Ix "RectObj" "" "2~67" ""
.Ix "resize borders" "" "2~4" ""
.Ix "resource description file" "" "2~12" ""
.Ix "resource description file" "" "2~23" ""
.Ix "resources" "" "2~10" ""
.Ix "resources" "" "2~12" ""
.Ix "resources" "" "2~13" ""
.Ix "resources" "" "2~14" ""
.Ix "resources" "" "2~15" ""
.Ix "resources" "" "2~16" ""
.Ix "resources" "" "2~17" ""
.Ix "resources" "" "2~18" ""
.Ix "resources" "" "2~20" ""
.Ix "resources" "" "2~21" ""
.Ix "resources" "" "2~22" ""
.Ix "resources" "" "2~23" ""
.Ix "resources" "" "2~6" ""
.Ix "resources" "" "2~7" ""
.Ix "resources" "" "2~8" ""
.Ix "resources" "" "2~9" ""
.Ix "RowColumn functions" "XmGetMenuCursor" "2~278" ""
.Ix "RowColumn functions" "XmGetPostedFromWidget" "2~281" ""
.Ix "RowColumn functions" "XmMenuPosition" "2~349" ""
.Ix "RowColumn functions" "XmOptionButtonGadget" "2~361" ""
.Ix "RowColumn functions" "XmOptionLabelGadget" "2~362" ""
.Ix "RowColumn functions" "XmSetMenuCursor" "2~449" ""
.Iy "S"
.Ix "Scale functions" "XmScaleGetValue" "2~415" ""
.Ix "Scale functions" "XmScaleSetValue" "2~416" ""
.Ix "ScrollBar functions" "XmScrollBarGetValues" "2~425" ""
.Ix "ScrollBar functions" "XmScrollBarSetValues" "2~426" ""
.Ix "ScrolledWindow functions" "XmScrolledWindowSetAreas" "2~433" ""
.Ix "SelectionBox functions" "XmSelectionBoxGetChild" "2~442" ""
.Ix "service outline" "" "1~5" ""
.Ix "service outline" "" "1~5" "1"
.Ix "session manager" "" "2~3" ""
.Ix "Shell" "" "2~69" ""
.Ix "support levels" "" "1~4" ""
.Ix "support levels" "" "1~4" "1"
.Ix "support levels" "" "1~5" ""
.Ix "support levels" "" "1~6" ""
.Ix "support levels" "" "1~7" ""
.Iy "T"
.Ix "temporary use" "" "1~5" ""
.Ix "temporary use" "" "1~6" "1"
.Ix "temporary use" "" "1~7" ""
.Ix "Text functions" "XmTextClearSelection" "2~497" ""
.Ix "Text functions" "XmTextCopy" "2~498" ""
.Ix "Text functions" "XmTextCut" "2~499" ""
.Ix "Text functions" "XmTextGetBaseline" "2~500" ""
.Ix "Text functions" "XmTextGetEditable" "2~501" ""
.Ix "Text functions" "XmTextGetInsertionPosition" "2~502" ""
.Ix "Text functions" "XmTextGetLastPosition" "2~503" ""
.Ix "Text functions" "XmTextGetMaxLength" "2~504" ""
.Ix "Text functions" "XmTextGetSelection" "2~505" ""
.Ix "Text functions" "XmTextGetSelectionPosition" "2~506" ""
.Ix "Text functions" "XmTextGetSource" "2~507" ""
.Ix "Text functions" "XmTextGetString" "2~508" ""
.Ix "Text functions" "XmTextGetTopCharacter" "2~509" ""
.Ix "Text functions" "XmTextInsert" "2~510" ""
.Ix "Text functions" "XmTextPaste" "2~511" ""
.Ix "Text functions" "XmTextPosToXY" "2~512" ""
.Ix "Text functions" "XmTextRemove" "2~514" ""
.Ix "Text functions" "XmTextReplace" "2~515" ""
.Ix "Text functions" "XmTextScroll" "2~516" ""
.Ix "Text functions" "XmTextSetAddMode" "2~517" ""
.Ix "Text functions" "XmTextSetEditable" "2~518" ""
.Ix "Text functions" "XmTextSetHighlight" "2~519" ""
.Ix "Text functions" "XmTextSetInsertionPosition" "2~520" ""
.Ix "Text functions" "XmTextSetMaxLength" "2~521" ""
.Ix "Text functions" "XmTextSetSelection" "2~522" ""
.Ix "Text functions" "XmTextSetSource" "2~523" ""
.Ix "Text functions" "XmTextSetString" "2~524" ""
.Ix "Text functions" "XmTextSetTopCharacter" "2~525" ""
.Ix "Text functions" "XmTextShowPosition" "2~526" ""
.Ix "Text functions" "XmTextXYToPos" "2~527" ""
.Ix "title bar" "" "2~4" ""
.Ix "ToggleButton functions" "XmToggleButtonGetState" "2~545" ""
.Ix "ToggleButton functions" "XmToggleButtonSetState" "2~546" ""
.Ix "ToggleButtonGadget functions" "XmToggleButtonGadgetGetState" "2~543" ""
.Ix "ToggleButtonGadget functions" "XmToggleButtonGadgetSetState" "2~544" ""
.Ix "Toolkit functions" "XmTrackingLocate" "2~547" ""
.Ix "TopLevelShell" "" "2~72" ""
.Ix "TransientShell" "" "2~75" ""
.Ix "trial use" "" "1~5" ""
.Ix "trial use" "" "1~6" ""
.Ix "trial use" "" "1~6" "1"
.Iy "U"
.Ix "uid file" "" "2~46" ""
.Ix "uid hierarchy" "" "2~45" ""
.Ix "uil compiler" "" "2~78" ""
.Ix "uil functions" "MrmCloseHierarchy" "2~45" ""
.Ix "uil functions" "MrmFetchColorLiteral" "2~46" ""
.Ix "uil functions" "MrmFetchIconLiteral" "2~47" ""
.Ix "uil functions" "MrmFetchLiteral" "2~48" ""
.Ix "uil functions" "MrmFetchSetValues" "2~49" ""
.Ix "uil functions" "MrmFetchWidget" "2~51" ""
.Ix "uil functions" "MrmFetchWidgetOverride" "2~53" ""
.Ix "uil functions" "MrmInitialize" "2~55" ""
.Ix "uil functions" "MrmOpenHierarchy" "2~56" ""
.Ix "uil functions" "MrmRegisterClass" "2~59" ""
.Ix "uil functions" "MrmRegisterNames" "2~60" ""
.Ix "uil functions" "MrmRegisterNamesInHierarchy" "2~62" ""
.Ix "uil functions" "Uil" "2~78" ""
.Ix "Uil" "" "2~78" ""
.Iy "V"
.Ix "VendorShell functions" "XmActivateProtocol" "2~91" ""
.Ix "VendorShell functions" "XmActivateWMProtocol" "2~92" ""
.Ix "VendorShell functions" "XmAddProtocolCallback" "2~93" ""
.Ix "VendorShell functions" "XmAddProtocols" "2~94" ""
.Ix "VendorShell functions" "XmAddWMProtocolCallback" "2~96" ""
.Ix "VendorShell functions" "XmAddWMProtocols" "2~97" ""
.Ix "VendorShell functions" "XmDeactivateProtocol" "2~223" ""
.Ix "VendorShell functions" "XmDeactivateWMProtocol" "2~224" ""
.Ix "VendorShell functions" "XmRemoveProtocolCallback" "2~388" ""
.Ix "VendorShell functions" "XmRemoveProtocols" "2~389" ""
.Ix "VendorShell functions" "XmRemoveWMProtocolCallback" "2~391" ""
.Ix "VendorShell functions" "XmRemoveWMProtocols" "2~392" ""
.Ix "VendorShell functions" "XmSetProtocolHooks" "2~450" ""
.Ix "VendorShell functions" "XmSetWMProtocolHooks" "2~451" ""
.Ix "VendorShell" "" "2~81" ""
.Iy "W"
.Ix "widget class" "ApplicationShell" "2~33" ""
.Ix "widget class" "ArrowButton" "2~98" ""
.Ix "widget class" "ArrowButtonGadget" "2~103" ""
.Ix "widget class" "BulletinBoard" "2~107" ""
.Ix "widget class" "CascadeButton" "2~114" ""
.Ix "widget class" "CascadeButtonGadget" "2~120" ""
.Ix "widget class" "Command" "2~152" ""
.Ix "widget class" "Composite" "2~37" ""
.Ix "widget class" "Constraint" "2~40" ""
.Ix "widget class" "Core" "2~42" ""
.Ix "widget class" "DialogShell" "2~226" ""
.Ix "widget class" "DrawingArea" "2~229" ""
.Ix "widget class" "DrawnButton" "2~233" ""
.Ix "widget class" "FileSelectionBox" "2~239" ""
.Ix "widget class" "Form" "2~257" ""
.Ix "widget class" "Frame" "2~271" ""
.Ix "widget class" "Gadget" "2~274" ""
.Ix "widget class" "Label" "2~285" ""
.Ix "widget class" "LabelGadget" "2~292" ""
.Ix "widget class" "List" "2~298" ""
.Ix "widget class" "MainWindow" "2~336" ""
.Ix "widget class" "Manager" "2~344" ""
.Ix "widget class" "MenuShell" "2~350" ""
.Ix "widget class" "MessageBox" "2~354" ""
.Ix "widget class" "Object" "2~64" ""
.Ix "widget class" "OverrideShell" "2~65" ""
.Ix "widget class" "PanedWindow" "2~363" ""
.Ix "widget class" "Primitive" "2~368" ""
.Ix "widget class" "PushButton" "2~375" ""
.Ix "widget class" "PushButtonGadget" "2~382" ""
.Ix "widget class" "RectObj" "2~67" ""
.Ix "widget class" "RowColumn" "2~395" ""
.Ix "widget class" "Scale" "2~407" ""
.Ix "widget class" "ScrollBar" "2~417" ""
.Ix "widget class" "ScrolledWindow" "2~427" ""
.Ix "widget class" "SelectionBox" "2~434" ""
.Ix "widget class" "Separator" "2~443" ""
.Ix "widget class" "SeparatorGadget" "2~446" ""
.Ix "widget class" "Shell" "2~69" ""
.Ix "widget class" "Text" "2~478" ""
.Ix "widget class" "ToggleButton" "2~528" ""
.Ix "widget class" "ToggleButtonGadget" "2~536" ""
.Ix "widget class" "TopLevelShell" "2~72" ""
.Ix "widget class" "TransientShell" "2~75" ""
.Ix "widget class" "VendorShell" "2~81" ""
.Ix "widget class" "WMShell" "2~85" ""
.Ix "window manager" "" "2~3" ""
.Ix "window menu" "" "2~4" ""
.Ix "WMShell" "" "2~85" ""
.Iy "X"
.Ix "XmActivateProtocol" "" "2~91" ""
.Ix "XmActivateWMProtocol" "" "2~92" ""
.Ix "XmAddProtocolCallback" "" "2~93" ""
.Ix "XmAddProtocols" "" "2~94" ""
.Ix "XmAddTabGroup" "" "2~95" ""
.Ix "XmAddWMProtocolCallback" "" "2~96" ""
.Ix "XmAddWMProtocols" "" "2~97" ""
.Ix "XmArrowButton" "" "2~98" ""
.Ix "XmArrowButtonGadget" "" "2~103" ""
.Ix "XmBulletinBoard" "" "2~107" ""
.Ix "XmCascadeButton" "" "2~114" ""
.Ix "XmCascadeButtonGadget" "" "2~120" ""
.Ix "XmCascadeButtonGadgetHighlight" "" "2~125" ""
.Ix "XmCascadeButtonHighlight" "" "2~126" ""
.Ix "XmClipboardCancelCopy" "" "2~127" ""
.Ix "XmClipboardCopy" "" "2~128" ""
.Ix "XmClipboardCopyByName" "" "2~130" ""
.Ix "XmClipboardEndCopy" "" "2~132" ""
.Ix "XmClipboardEndRetrieve" "" "2~133" ""
.Ix "XmClipboardInquireCount" "" "2~134" ""
.Ix "XmClipboardInquireFormat" "" "2~136" ""
.Ix "XmClipboardInquireLength" "" "2~138" ""
.Ix "XmClipboardInquirePendingItems" "" "2~140" ""
.Ix "XmClipboardLock" "" "2~142" ""
.Ix "XmClipboardRegisterFormat" "" "2~143" ""
.Ix "XmClipboardRetrieve" "" "2~144" ""
.Ix "XmClipboardStartCopy" "" "2~146" ""
.Ix "XmClipboardStartRetrieve" "" "2~148" ""
.Ix "XmClipboardUndoCopy" "" "2~149" ""
.Ix "XmClipboardUnlock" "" "2~150" ""
.Ix "XmClipboardWithdrawFormat" "" "2~151" ""
.Ix "XmCommand" "" "2~152" ""
.Ix "XmCommandAppendValue" "" "2~158" ""
.Ix "XmCommandError" "" "2~159" ""
.Ix "XmCommandGetChild" "" "2~160" ""
.Ix "XmCommandSetValue" "" "2~161" ""
.Ix "XmConvertUnits" "" "2~162" ""
.Ix "XmCreateArrowButton" "" "2~163" ""
.Ix "XmCreateArrowButtonGadget" "" "2~164" ""
.Ix "XmCreateBulletinBoard" "" "2~165" ""
.Ix "XmCreateBulletinBoardDialog" "" "2~166" ""
.Ix "XmCreateCascadeButton" "" "2~167" ""
.Ix "XmCreateCascadeButtonGadget" "" "2~168" ""
.Ix "XmCreateCommand" "" "2~169" ""
.Ix "XmCreateDialogShell" "" "2~170" ""
.Ix "XmCreateDrawingArea" "" "2~171" ""
.Ix "XmCreateDrawnButton" "" "2~172" ""
.Ix "XmCreateErrorDialog" "" "2~173" ""
.Ix "XmCreateFileSelectionBox" "" "2~174" ""
.Ix "XmCreateFileSelectionDialog" "" "2~175" ""
.Ix "XmCreateForm" "" "2~176" ""
.Ix "XmCreateFormDialog" "" "2~177" ""
.Ix "XmCreateFrame" "" "2~178" ""
.Ix "XmCreateInformationDialog" "" "2~179" ""
.Ix "XmCreateLabel" "" "2~180" ""
.Ix "XmCreateLabelGadget" "" "2~181" ""
.Ix "XmCreateList" "" "2~182" ""
.Ix "XmCreateMainWindow" "" "2~183" ""
.Ix "XmCreateMenuBar" "" "2~184" ""
.Ix "XmCreateMenuShell" "" "2~186" ""
.Ix "XmCreateMessageBox" "" "2~187" ""
.Ix "XmCreateMessageDialog" "" "2~188" ""
.Ix "XmCreateOptionMenu" "" "2~189" ""
.Ix "XmCreatePanedWindow" "" "2~191" ""
.Ix "XmCreatePopupMenu" "" "2~192" ""
.Ix "XmCreatePromptDialog" "" "2~194" ""
.Ix "XmCreatePulldownMenu" "" "2~195" ""
.Ix "XmCreatePushButton" "" "2~197" ""
.Ix "XmCreatePushButtonGadget" "" "2~198" ""
.Ix "XmCreateQuestionDialog" "" "2~199" ""
.Ix "XmCreateRadioBox" "" "2~200" ""
.Ix "XmCreateRowColumn" "" "2~201" ""
.Ix "XmCreateScale" "" "2~202" ""
.Ix "XmCreateScrollBar" "" "2~203" ""
.Ix "XmCreateScrolledList" "" "2~204" ""
.Ix "XmCreateScrolledText" "" "2~206" ""
.Ix "XmCreateScrolledWindow" "" "2~208" ""
.Ix "XmCreateSelectionBox" "" "2~209" ""
.Ix "XmCreateSelectionDialog" "" "2~211" ""
.Ix "XmCreateSeparator" "" "2~213" ""
.Ix "XmCreateSeparatorGadget" "" "2~214" ""
.Ix "XmCreateText" "" "2~215" ""
.Ix "XmCreateToggleButton" "" "2~216" ""
.Ix "XmCreateToggleButtonGadget" "" "2~217" ""
.Ix "XmCreateWarningDialog" "" "2~218" ""
.Ix "XmCreateWorkArea" "" "2~219" ""
.Ix "XmCreateWorkingDialog" "" "2~220" ""
.Ix "XmCvtCTToXmString" "" "2~221" ""
.Ix "XmCvtXmStringToCT" "" "2~222" ""
.Ix "XmDeactivateProtocol" "" "2~223" ""
.Ix "XmDeactivateWMProtocol" "" "2~224" ""
.Ix "XmDestroyPixmap" "" "2~225" ""
.Ix "XmDialogShell" "" "2~226" ""
.Ix "XmDrawingArea" "" "2~229" ""
.Ix "XmDrawnButton" "" "2~233" ""
.Ix "XmFileSelectionBox" "" "2~239" ""
.Ix "XmFileSelectionBoxGetChild" "" "2~250" ""
.Ix "XmFileSelectionDoSearch" "" "2~252" ""
.Ix "XmFontList" "" "2~253" ""
.Ix "XmFontListAdd" "" "2~254" ""
.Ix "XmFontListCreate" "" "2~255" ""
.Ix "XmFontListFree" "" "2~256" ""
.Ix "XmForm" "" "2~257" ""
.Ix "XmFrame" "" "2~271" ""
.Ix "XmGadget" "" "2~274" ""
.Ix "XmGetAtomName" "" "2~276" ""
.Ix "XmGetColors" "" "2~277" ""
.Ix "XmGetMenuCursor" "" "2~278" ""
.Ix "XmGetPixmap" "" "2~279" ""
.Ix "XmGetPostedFromWidget" "" "2~281" ""
.Ix "XmInstallImage" "" "2~282" ""
.Ix "XmInternAtom" "" "2~283" ""
.Ix "XmIsMotifWMRunning" "" "2~284" ""
.Ix "XmLabel" "" "2~285" ""
.Ix "XmLabelGadget" "" "2~292" ""
.Ix "XmList" "" "2~298" ""
.Ix "XmListAddItem" "" "2~311" ""
.Ix "XmListAddItems" "" "2~312" ""
.Ix "XmListAddItemUnselected" "" "2~313" ""
.Ix "XmListDeleteAllItems" "" "2~314" ""
.Ix "XmListDeleteItem" "" "2~315" ""
.Ix "XmListDeleteItems" "" "2~316" ""
.Ix "XmListDeleteItemsPos" "" "2~317" ""
.Ix "XmListDeletePos" "" "2~318" ""
.Ix "XmListDeselectAllItems" "" "2~319" ""
.Ix "XmListDeselectItem" "" "2~320" ""
.Ix "XmListDeselectPos" "" "2~321" ""
.Ix "XmListGetMatchPos" "" "2~322" ""
.Ix "XmListGetSelectedPos" "" "2~323" ""
.Ix "XmListItemExists" "" "2~324" ""
.Ix "XmListItemPos" "" "2~325" ""
.Ix "XmListReplaceItems" "" "2~326" ""
.Ix "XmListReplaceItemsPos" "" "2~327" ""
.Ix "XmListSelectItem" "" "2~328" ""
.Ix "XmListSelectPos" "" "2~329" ""
.Ix "XmListSetAddMode" "" "2~330" ""
.Ix "XmListSetBottomItem" "" "2~331" ""
.Ix "XmListSetBottomPos" "" "2~332" ""
.Ix "XmListSetHorizPos" "" "2~333" ""
.Ix "XmListSetItem" "" "2~334" ""
.Ix "XmListSetPos" "" "2~335" ""
.Ix "XmMainWindow" "" "2~336" ""
.Ix "XmMainWindowSep1" "" "2~340" ""
.Ix "XmMainWindowSep2" "" "2~341" ""
.Ix "XmMainWindowSep3" "" "2~342" ""
.Ix "XmMainWindowSetAreas" "" "2~343" ""
.Ix "XmManager" "" "2~344" ""
.Ix "XmMenuPosition" "" "2~349" ""
.Ix "XmMenuShell" "" "2~350" ""
.Ix "XmMessageBox" "" "2~354" ""
.Ix "XmMessageBoxGetChild" "" "2~360" ""
.Ix "XmOptionButtonGadget" "" "2~361" ""
.Ix "XmOptionLabelGadget" "" "2~362" ""
.Ix "XmPanedWindow" "" "2~363" ""
.Ix "XmPrimitive" "" "2~368" ""
.Ix "XmProcessTraversal" "" "2~373" ""
.Ix "XmPushButton" "" "2~375" ""
.Ix "XmPushButtonGadget" "" "2~382" ""
.Ix "XmRemoveProtocolCallback" "" "2~388" ""
.Ix "XmRemoveProtocols" "" "2~389" ""
.Ix "XmRemoveTabGroup" "" "2~390" ""
.Ix "XmRemoveWMProtocolCallback" "" "2~391" ""
.Ix "XmRemoveWMProtocols" "" "2~392" ""
.Ix "XmResolvePartOffsets" "" "2~393" ""
.Ix "XmRowColumn" "" "2~395" ""
.Ix "XmScale" "" "2~407" ""
.Ix "XmScaleGetValue" "" "2~415" ""
.Ix "XmScaleSetValue" "" "2~416" ""
.Ix "XmScrollBar" "" "2~417" ""
.Ix "XmScrollBarGetValues" "" "2~425" ""
.Ix "XmScrollBarSetValues" "" "2~426" ""
.Ix "XmScrolledWindow" "" "2~427" ""
.Ix "XmScrolledWindowSetAreas" "" "2~433" ""
.Ix "XmSelectionBox" "" "2~434" ""
.Ix "XmSelectionBoxGetChild" "" "2~442" ""
.Ix "XmSeparator" "" "2~443" ""
.Ix "XmSeparatorGadget" "" "2~446" ""
.Ix "XmSetMenuCursor" "" "2~449" ""
.Ix "XmSetProtocolHooks" "" "2~450" ""
.Ix "XmSetWMProtocolHooks" "" "2~451" ""
.Ix "XmString" "" "2~452" ""
.Ix "XmStringBaseline" "" "2~453" ""
.Ix "XmStringByteCompare" "" "2~454" ""
.Ix "XmStringCompare" "" "2~455" ""
.Ix "XmStringConcat" "" "2~456" ""
.Ix "XmStringCopy" "" "2~457" ""
.Ix "XmStringCreate" "" "2~458" ""
.Ix "XmStringCreateSimple" "" "2~459" ""
.Ix "XmStringDirection" "" "2~460" ""
.Ix "XmStringDraw" "" "2~461" ""
.Ix "XmStringDrawImage" "" "2~462" ""
.Ix "XmStringDrawUnderline" "" "2~464" ""
.Ix "XmStringEmpty" "" "2~466" ""
.Ix "XmStringExtent" "" "2~467" ""
.Ix "XmStringFree" "" "2~468" ""
.Ix "XmStringHasSubstring" "" "2~469" ""
.Ix "XmStringHeight" "" "2~470" ""
.Ix "XmStringLength" "" "2~471" ""
.Ix "XmStringLineCount" "" "2~472" ""
.Ix "XmStringNConcat" "" "2~473" ""
.Ix "XmStringNCopy" "" "2~474" ""
.Ix "XmStringSeparatorCreate" "" "2~475" ""
.Ix "XmStringTable" "" "2~476" ""
.Ix "XmStringWidth" "" "2~477" ""
.Ix "XmText" "" "2~478" ""
.Ix "XmTextClearSelection" "" "2~497" ""
.Ix "XmTextCopy" "" "2~498" ""
.Ix "XmTextCut" "" "2~499" ""
.Ix "XmTextGetBaseline" "" "2~500" ""
.Ix "XmTextGetEditable" "" "2~501" ""
.Ix "XmTextGetInsertionPosition" "" "2~502" ""
.Ix "XmTextGetLastPosition" "" "2~503" ""
.Ix "XmTextGetMaxLength" "" "2~504" ""
.Ix "XmTextGetSelection" "" "2~505" ""
.Ix "XmTextGetSelectionPosition" "" "2~506" ""
.Ix "XmTextGetSource" "" "2~507" ""
.Ix "XmTextGetString" "" "2~508" ""
.Ix "XmTextGetTopCharacter" "" "2~509" ""
.Ix "XmTextInsert" "" "2~510" ""
.Ix "XmTextPaste" "" "2~511" ""
.Ix "XmTextPosition" "" "2~513" ""
.Ix "XmTextPosToXY" "" "2~512" ""
.Ix "XmTextRemove" "" "2~514" ""
.Ix "XmTextReplace" "" "2~515" ""
.Ix "XmTextScroll" "" "2~516" ""
.Ix "XmTextSetAddMode" "" "2~517" ""
.Ix "XmTextSetEditable" "" "2~518" ""
.Ix "XmTextSetHighlight" "" "2~519" ""
.Ix "XmTextSetInsertionPosition" "" "2~520" ""
.Ix "XmTextSetMaxLength" "" "2~521" ""
.Ix "XmTextSetSelection" "" "2~522" ""
.Ix "XmTextSetSource" "" "2~523" ""
.Ix "XmTextSetString" "" "2~524" ""
.Ix "XmTextSetTopCharacter" "" "2~525" ""
.Ix "XmTextShowPosition" "" "2~526" ""
.Ix "XmTextXYToPos" "" "2~527" ""
.Ix "XmToggleButton" "" "2~528" ""
.Ix "XmToggleButtonGadget" "" "2~536" ""
.Ix "XmToggleButtonGadgetGetState" "" "2~543" ""
.Ix "XmToggleButtonGadgetSetState" "" "2~544" ""
.Ix "XmToggleButtonGetState" "" "2~545" ""
.Ix "XmToggleButtonSetState" "" "2~546" ""
.Ix "XmTrackingLocate" "" "2~547" ""
.Ix "XmUninstallImage" "" "2~548" ""
.Ix "XmUpdateDisplay" "" "2~549" ""
...\"	index formatting macros
...\"
...\"     this simply restores one column text
.1C
