#define urmcompress_h		1
#define URMcError			0
#define URMcUnknown			1
#define URMcMinCompressValue		2
#define URMcMaxCompressValue		324
#define URMcaccelerator			2
#define URMcacceleratorText			3
#define URMcactivateCallback			4
#define URMcadjustLast			5
#define URMcadjustMargin			6
#define URMcalignment			7
#define URMcallowOverlap			8
#define URMcallowResize			9
#define URMcallowShellResize			10
#define URMcarmCallback			11
#define URMcarmPixmap			12
#define URMcarrowDirection			13
#define URMcautoShowCursorPosition			14
#define URMcautoUnmanage			15
#define URMcbackground			16
#define URMcbackgroundPixmap			17
#define URMcblinkRate			18
#define URMcborderColor			19
#define URMcborderPixmap			20
#define URMcborderWidth			21
#define URMcbottomAttachment			22
#define URMcbottomOffset			23
#define URMcbottomPosition			24
#define URMcbottomShadowColor			25
#define URMcbottomShadowPixmap			26
#define URMcbottomWidget			27
#define URMcbrowseSelectionCallback			28
#define URMcbuttonFontList			29
#define URMccancelButton			30
#define URMccancelCallback			31
#define URMccancelLabelString			33
#define URMccascadePixmap			35
#define URMccascadingCallback			36
#define URMcclipWindow			37
#define URMccolumns			38
#define URMccommandChangedCallback			39
#define URMccommandEnteredCallback			40
#define URMccreateCallback			43
#define URMcdecrementCallback			44
#define URMcdefaultActionCallback			45
#define URMcdefaultButton			46
#define URMcdefaultPosition			47
#define URMcdeleteResponse			49
#define URMcdestroyCallback			50
#define URMcdialogStyle			51
#define URMcdialogTitle			52
#define URMcdialogType			53
#define URMcdisarmCallback			54
#define URMcdoubleClickInterval			55
#define URMcdragCallback			56
#define URMceditMode			57
#define URMceditable			58
#define URMcentryAlignment			64
#define URMcentryBorder			65
#define URMcentryClass			66
#define URMcexposeCallback			68
#define URMcextendedSelectionCallback			69
#define URMcfillOnSelect			70
#define URMcfocusCallback			71
#define URMcfont			72
#define URMcforeground			73
#define URMcfractionBase			74
#define URMcheight			75
#define URMchelpCallback			77
#define URMchelpLabelString			79
#define URMchighlightColor			81
#define URMchighlightOnEnter			82
#define URMchighlightPixmap			83
#define URMchighlightThickness			84
#define URMchorizontalScrollBar			87
#define URMchorizontalSpacing			88
#define URMcincrement			89
#define URMcincrementCallback			90
#define URMcindicatorOn			91
#define URMcindicatorType			92
#define URMcinitialDelay			93
#define URMcinputCallback			94
#define URMccursorPositionVisible			95
#define URMcisAligned			98
#define URMcisHomogeneous			99
#define URMcitemCount			100
#define URMcitems			101
#define URMclabelFontList			103
#define URMclabelPixmap			105
#define URMclabelString			106
#define URMclabelType			107
#define URMcleftAttachment			108
#define URMcleftOffset			109
#define URMcleftPosition			110
#define URMcleftWidget			111
#define URMclistItemCount			112
#define URMclistItems			113
#define URMclistMarginHeight			114
#define URMclistMarginWidth			115
#define URMclistSizePolicy			116
#define URMclistSpacing			117
#define URMclistVisibleItemCount			118
#define URMclosingFocusCallback			119
#define URMcmapCallback			120
#define URMcmappedWhenManaged			121
#define URMcmappingDelay			122
#define URMcmargin			123
#define URMcmarginBottom			124
#define URMcmarginHeight			125
#define URMcmarginLeft			126
#define URMcmarginRight			127
#define URMcmarginTop			128
#define URMcmarginWidth			129
#define URMcmaxLength			131
#define URMcmaximum			132
#define URMcmenuAccelerator			133
#define URMcmenuHelpWidget			134
#define URMcmenuHistory			135
#define URMcmessageAlignment			136
#define URMcmessageString			138
#define URMcminimum			141
#define URMcmnemonic			142
#define URMcmotionVerifyCallback			144
#define URMcmultipleSelectionCallback			145
#define URMcmustMatch			146
#define URMcnoMatchCallback			147
#define URMcnumColumns			148
#define URMcorientation			149
#define URMcpacking			150
#define URMcpageDecrementCallback			151
#define URMcpageIncrement			152
#define URMcpageIncrementCallback			153
#define URMcpendingDelete			154
#define URMcpopupEnabled			156
#define URMcprocessingDirection			157
#define URMcpromptString			158
#define URMcradioAlwaysOne			159
#define URMcradioBehavior			160
#define URMcrefigureMode			161
#define URMcrepeatDelay			162
#define URMcresizable			163
#define URMcresizeCallback			164
#define URMcresizeHeight			165
#define URMcresizePolicy			166
#define URMcresizeWidth			167
#define URMcrightAttachment			168
#define URMcrightOffset			169
#define URMcrightPosition			170
#define URMcrightWidget			171
#define URMcrowColumnType			172
#define URMcrows			173
#define URMcrubberPositioning			174
#define URMcsashHeight			175
#define URMcsashIndent			176
#define URMcsashShadowThickness			177
#define URMcsashWidth			178
#define URMcsaveUnder			179
#define URMcscrollBarDisplayPolicy			180
#define URMcscrollBarPlacement			181
#define URMcscrollHorizontal			182
#define URMcscrollLeftSide			183
#define URMcscrollTopSide			184
#define URMcscrollVertical			185
#define URMcscrollingPolicy			186
#define URMcselectPixmap			187
#define URMcselectThreshold			188
#define URMcselectedItemCount			189
#define URMcselectedItems			190
#define URMcselectionArray			191
#define URMcselectionLabelString			193
#define URMcselectionPolicy			195
#define URMcsensitive			196
#define URMcseparatorOn			197
#define URMcseparatorType			198
#define URMcset			199
#define URMcshadowThickness			200
#define URMcshadowType			201
#define URMcshowArrows			202
#define URMcsingleSelectionCallback			203
#define URMcsizePolicy			204
#define URMcskipAdjust			205
#define URMcsliderSize			206
#define URMcspacing			207
#define URMcstringDirection			208
#define URMcsubMenuId			210
#define URMcsymbolPixmap			211
#define URMctextColumns			214
#define URMctextFontList			215
#define URMctextTranslations			216
#define URMctextValue			217
#define URMctoBottomCallback			218
#define URMctoTopCallback			219
#define URMctopAttachment			220
#define URMctopOffset			221
#define URMctopPosition			222
#define URMctopShadowColor			223
#define URMctopShadowPixmap			224
#define URMctopWidget			225
#define URMctranslations			226
#define URMctraversalOn			227
#define URMcunitType			228
#define URMcunmapCallback			229
#define URMcupdateSliderSize			230
#define URMcuserData			231
#define URMcvalue			232
#define URMcvalueChangedCallback			233
#define URMcverticalScrollBar			234
#define URMcverticalSpacing			235
#define URMcvisibleItemCount			236
#define URMcvisibleWhenOff			237
#define URMcvisualPolicy			238
#define URMcwidth			239
#define URMcwordWrap			240
#define URMcworkWindow			241
#define URMcx			242
#define URMcy			243
#define URMcapplyCallback			244
#define URMcapplyLabelString			245
#define URMccursorPosition			256
#define URMcdecimalPoints			257
#define URMcdefaultButtonType			258
#define URMcdirMask			259
#define URMcdirSpec			260
#define URMcfileSearchProc			270
#define URMcfilterLabelString			271
#define URMcfontList			272
#define URMchistoryItemCount			273
#define URMchistoryItems			274
#define URMchistoryVisibleItemCount			275
#define URMcfillOnArm			276
#define URMckeyboardFocusPolicy			277
#define URMclabelInsensitivePixmap			278
#define URMclistUpdated			279
#define URMcmainWindowMarginHeight			280
#define URMcmainWindowMarginWidth			281
#define URMcmodifyVerifyCallback			282
#define URMcmwmMenu			286
#define URMcokCallback			287
#define URMcokLabelString			288
#define URMcpushButtonEnabled			289
#define URMcscaleHeight			290
#define URMcscaleWidth			291
#define URMcscrolledWindowMarginHeight			292
#define URMcscrolledWindowMarginWidth			293
#define URMcselectInsensitivePixmap			294
#define URMcshellUnitType			295
#define URMcshowAsDefault			296
#define URMcshowValue			297
#define URMcmenuBar			298
#define URMccommand			299
#define URMccommandWindow			300
#define URMctitleString			301
#define URMcmwmFunctions			303
#define URMcmwmDecorations			304
#define URMcmwmInputMode			305
#define URMcancestorSensitive			306
#define URMcentryCallback			307
#define URMchistoryMaxItems			308
#define URMcrecomputeSize			309
#define URMcarmColor			310
#define URMcautomaticSelection			311
#define URMcselectColor			312
#define URMcshowSeparator			313
#define URMcwhichButton			314
#define URMctextAccelerators			315
#define URMclistLabelString			316
#define URMcminimizeButtons			317
#define URMcnoResize			318
#define URMctextString			319
#define URMcinsertPosition			320
#define URMcaccelerators			321
#define URMccolormap			322
#define URMcdepth			323
#define URMcscreen			324
