static String code_to_string_keytable[] =
  {
    NULL			/* 0 */
    ,NULL			/* 1 */
    ,XmNaccelerator			/* 2 */
    ,XmNacceleratorText			/* 3 */
    ,XmNactivateCallback			/* 4 */
    ,XmNadjustLast			/* 5 */
    ,XmNadjustMargin			/* 6 */
    ,XmNalignment			/* 7 */
    ,XmNallowOverlap			/* 8 */
    ,XmNallowResize			/* 9 */
    ,XmNallowShellResize			/* 10 */
    ,XmNarmCallback			/* 11 */
    ,XmNarmPixmap			/* 12 */
    ,XmNarrowDirection			/* 13 */
    ,XmNautoShowCursorPosition			/* 14 */
    ,XmNautoUnmanage			/* 15 */
    ,XmNbackground			/* 16 */
    ,XmNbackgroundPixmap			/* 17 */
    ,XmNblinkRate			/* 18 */
    ,XmNborderColor			/* 19 */
    ,XmNborderPixmap			/* 20 */
    ,XmNborderWidth			/* 21 */
    ,XmNbottomAttachment			/* 22 */
    ,XmNbottomOffset			/* 23 */
    ,XmNbottomPosition			/* 24 */
    ,XmNbottomShadowColor			/* 25 */
    ,XmNbottomShadowPixmap			/* 26 */
    ,XmNbottomWidget			/* 27 */
    ,XmNbrowseSelectionCallback			/* 28 */
    ,XmNbuttonFontList			/* 29 */
    ,XmNcancelButton			/* 30 */
    ,XmNcancelCallback			/* 31 */
    ,NULL			/* 32 */
    ,XmNcancelLabelString			/* 33 */
    ,NULL			/* 34 */
    ,XmNcascadePixmap			/* 35 */
    ,XmNcascadingCallback			/* 36 */
    ,XmNclipWindow			/* 37 */
    ,XmNcolumns			/* 38 */
    ,XmNcommandChangedCallback			/* 39 */
    ,XmNcommandEnteredCallback			/* 40 */
    ,NULL			/* 41 */
    ,NULL			/* 42 */
    ,NULL			/* 43 */
    ,XmNdecrementCallback			/* 44 */
    ,XmNdefaultActionCallback			/* 45 */
    ,XmNdefaultButton			/* 46 */
    ,XmNdefaultPosition			/* 47 */
    ,NULL			/* 48 */
    ,XmNdeleteResponse			/* 49 */
    ,XmNdestroyCallback			/* 50 */
    ,XmNdialogStyle			/* 51 */
    ,XmNdialogTitle			/* 52 */
    ,XmNdialogType			/* 53 */
    ,XmNdisarmCallback			/* 54 */
    ,XmNdoubleClickInterval			/* 55 */
    ,XmNdragCallback			/* 56 */
    ,XmNeditMode			/* 57 */
    ,XmNeditable			/* 58 */
    ,NULL			/* 59 */
    ,NULL			/* 60 */
    ,NULL			/* 61 */
    ,NULL			/* 62 */
    ,NULL			/* 63 */
    ,XmNentryAlignment			/* 64 */
    ,XmNentryBorder			/* 65 */
    ,XmNentryClass			/* 66 */
    ,NULL			/* 67 */
    ,XmNexposeCallback			/* 68 */
    ,XmNextendedSelectionCallback			/* 69 */
    ,XmNfillOnSelect			/* 70 */
    ,XmNfocusCallback			/* 71 */
    ,XmNfont			/* 72 */
    ,XmNforeground			/* 73 */
    ,XmNfractionBase			/* 74 */
    ,XmNheight			/* 75 */
    ,NULL			/* 76 */
    ,XmNhelpCallback			/* 77 */
    ,NULL			/* 78 */
    ,XmNhelpLabelString			/* 79 */
    ,NULL			/* 80 */
    ,XmNhighlightColor			/* 81 */
    ,XmNhighlightOnEnter			/* 82 */
    ,XmNhighlightPixmap			/* 83 */
    ,XmNhighlightThickness			/* 84 */
    ,NULL			/* 85 */
    ,NULL			/* 86 */
    ,XmNhorizontalScrollBar			/* 87 */
    ,XmNhorizontalSpacing			/* 88 */
    ,XmNincrement			/* 89 */
    ,XmNincrementCallback			/* 90 */
    ,XmNindicatorOn			/* 91 */
    ,XmNindicatorType			/* 92 */
    ,XmNinitialDelay			/* 93 */
    ,XmNinputCallback			/* 94 */
    ,XmNcursorPositionVisible			/* 95 */
    ,NULL			/* 96 */
    ,NULL			/* 97 */
    ,XmNisAligned			/* 98 */
    ,XmNisHomogeneous			/* 99 */
    ,XmNitemCount			/* 100 */
    ,XmNitems			/* 101 */
    ,NULL			/* 102 */
    ,XmNlabelFontList			/* 103 */
    ,NULL			/* 104 */
    ,XmNlabelPixmap			/* 105 */
    ,XmNlabelString			/* 106 */
    ,XmNlabelType			/* 107 */
    ,XmNleftAttachment			/* 108 */
    ,XmNleftOffset			/* 109 */
    ,XmNleftPosition			/* 110 */
    ,XmNleftWidget			/* 111 */
    ,XmNlistItemCount			/* 112 */
    ,XmNlistItems			/* 113 */
    ,XmNlistMarginHeight			/* 114 */
    ,XmNlistMarginWidth			/* 115 */
    ,XmNlistSizePolicy			/* 116 */
    ,XmNlistSpacing			/* 117 */
    ,XmNlistVisibleItemCount			/* 118 */
    ,XmNlosingFocusCallback			/* 119 */
    ,XmNmapCallback			/* 120 */
    ,XmNmappedWhenManaged			/* 121 */
    ,XmNmappingDelay			/* 122 */
    ,XmNmargin			/* 123 */
    ,XmNmarginBottom			/* 124 */
    ,XmNmarginHeight			/* 125 */
    ,XmNmarginLeft			/* 126 */
    ,XmNmarginRight			/* 127 */
    ,XmNmarginTop			/* 128 */
    ,XmNmarginWidth			/* 129 */
    ,NULL			/* 130 */
    ,XmNmaxLength			/* 131 */
    ,XmNmaximum			/* 132 */
    ,XmNmenuAccelerator			/* 133 */
    ,XmNmenuHelpWidget			/* 134 */
    ,XmNmenuHistory			/* 135 */
    ,XmNmessageAlignment			/* 136 */
    ,NULL			/* 137 */
    ,XmNmessageString			/* 138 */
    ,NULL			/* 139 */
    ,NULL			/* 140 */
    ,XmNminimum			/* 141 */
    ,XmNmnemonic			/* 142 */
    ,NULL			/* 143 */
    ,XmNmotionVerifyCallback			/* 144 */
    ,XmNmultipleSelectionCallback			/* 145 */
    ,XmNmustMatch			/* 146 */
    ,XmNnoMatchCallback			/* 147 */
    ,XmNnumColumns			/* 148 */
    ,XmNorientation			/* 149 */
    ,XmNpacking			/* 150 */
    ,XmNpageDecrementCallback			/* 151 */
    ,XmNpageIncrement			/* 152 */
    ,XmNpageIncrementCallback			/* 153 */
    ,XmNpendingDelete			/* 154 */
    ,NULL			/* 155 */
    ,XmNpopupEnabled			/* 156 */
    ,XmNprocessingDirection			/* 157 */
    ,XmNpromptString			/* 158 */
    ,XmNradioAlwaysOne			/* 159 */
    ,XmNradioBehavior			/* 160 */
    ,XmNrefigureMode			/* 161 */
    ,XmNrepeatDelay			/* 162 */
    ,XmNresizable			/* 163 */
    ,XmNresizeCallback			/* 164 */
    ,XmNresizeHeight			/* 165 */
    ,XmNresizePolicy			/* 166 */
    ,XmNresizeWidth			/* 167 */
    ,XmNrightAttachment			/* 168 */
    ,XmNrightOffset			/* 169 */
    ,XmNrightPosition			/* 170 */
    ,XmNrightWidget			/* 171 */
    ,XmNrowColumnType			/* 172 */
    ,XmNrows			/* 173 */
    ,XmNrubberPositioning			/* 174 */
    ,XmNsashHeight			/* 175 */
    ,XmNsashIndent			/* 176 */
    ,XmNsashShadowThickness			/* 177 */
    ,XmNsashWidth			/* 178 */
    ,XmNsaveUnder			/* 179 */
    ,XmNscrollBarDisplayPolicy			/* 180 */
    ,XmNscrollBarPlacement			/* 181 */
    ,XmNscrollHorizontal			/* 182 */
    ,XmNscrollLeftSide			/* 183 */
    ,XmNscrollTopSide			/* 184 */
    ,XmNscrollVertical			/* 185 */
    ,XmNscrollingPolicy			/* 186 */
    ,XmNselectPixmap			/* 187 */
    ,XmNselectThreshold			/* 188 */
    ,XmNselectedItemCount			/* 189 */
    ,XmNselectedItems			/* 190 */
    ,XmNselectionArray			/* 191 */
    ,NULL			/* 192 */
    ,XmNselectionLabelString			/* 193 */
    ,NULL			/* 194 */
    ,XmNselectionPolicy			/* 195 */
    ,XmNsensitive			/* 196 */
    ,XmNseparatorOn			/* 197 */
    ,XmNseparatorType			/* 198 */
    ,XmNset			/* 199 */
    ,XmNshadowThickness			/* 200 */
    ,XmNshadowType			/* 201 */
    ,XmNshowArrows			/* 202 */
    ,XmNsingleSelectionCallback			/* 203 */
    ,XmNsizePolicy			/* 204 */
    ,XmNskipAdjust			/* 205 */
    ,XmNsliderSize			/* 206 */
    ,XmNspacing			/* 207 */
    ,XmNstringDirection			/* 208 */
    ,NULL			/* 209 */
    ,XmNsubMenuId			/* 210 */
    ,XmNsymbolPixmap			/* 211 */
    ,NULL			/* 212 */
    ,NULL			/* 213 */
    ,XmNtextColumns			/* 214 */
    ,XmNtextFontList			/* 215 */
    ,XmNtextTranslations			/* 216 */
    ,XmNtextValue			/* 217 */
    ,XmNtoBottomCallback			/* 218 */
    ,XmNtoTopCallback			/* 219 */
    ,XmNtopAttachment			/* 220 */
    ,XmNtopOffset			/* 221 */
    ,XmNtopPosition			/* 222 */
    ,XmNtopShadowColor			/* 223 */
    ,XmNtopShadowPixmap			/* 224 */
    ,XmNtopWidget			/* 225 */
    ,XmNtranslations			/* 226 */
    ,XmNtraversalOn			/* 227 */
    ,XmNunitType			/* 228 */
    ,XmNunmapCallback			/* 229 */
    ,XmNupdateSliderSize			/* 230 */
    ,XmNuserData			/* 231 */
    ,XmNvalue			/* 232 */
    ,XmNvalueChangedCallback			/* 233 */
    ,XmNverticalScrollBar			/* 234 */
    ,XmNverticalSpacing			/* 235 */
    ,XmNvisibleItemCount			/* 236 */
    ,XmNvisibleWhenOff			/* 237 */
    ,XmNvisualPolicy			/* 238 */
    ,XmNwidth			/* 239 */
    ,XmNwordWrap			/* 240 */
    ,XmNworkWindow			/* 241 */
    ,XmNx			/* 242 */
    ,XmNy			/* 243 */
    ,XmNapplyCallback			/* 244 */
    ,XmNapplyLabelString			/* 245 */
    ,NULL			/* 246 */
    ,NULL			/* 247 */
    ,NULL			/* 248 */
    ,NULL			/* 249 */
    ,NULL			/* 250 */
    ,NULL			/* 251 */
    ,NULL			/* 252 */
    ,NULL			/* 253 */
    ,NULL			/* 254 */
    ,NULL			/* 255 */
    ,XmNcursorPosition			/* 256 */
    ,XmNdecimalPoints			/* 257 */
    ,XmNdefaultButtonType			/* 258 */
    ,XmNdirMask			/* 259 */
    ,XmNdirSpec			/* 260 */
    ,NULL			/* 261 */
    ,NULL			/* 262 */
    ,NULL			/* 263 */
    ,NULL			/* 264 */
    ,NULL			/* 265 */
    ,NULL			/* 266 */
    ,NULL			/* 267 */
    ,NULL			/* 268 */
    ,NULL			/* 269 */
    ,XmNfileSearchProc			/* 270 */
    ,XmNfilterLabelString			/* 271 */
    ,XmNfontList			/* 272 */
    ,XmNhistoryItemCount			/* 273 */
    ,XmNhistoryItems			/* 274 */
    ,XmNhistoryVisibleItemCount			/* 275 */
    ,XmNfillOnArm			/* 276 */
    ,XmNkeyboardFocusPolicy			/* 277 */
    ,XmNlabelInsensitivePixmap			/* 278 */
    ,XmNlistUpdated			/* 279 */
    ,XmNmainWindowMarginHeight			/* 280 */
    ,XmNmainWindowMarginWidth			/* 281 */
    ,XmNmodifyVerifyCallback			/* 282 */
    ,NULL			/* 283 */
    ,NULL			/* 284 */
    ,NULL			/* 285 */
    ,XmNmwmMenu			/* 286 */
    ,XmNokCallback			/* 287 */
    ,XmNokLabelString			/* 288 */
    ,XmNpushButtonEnabled			/* 289 */
    ,XmNscaleHeight			/* 290 */
    ,XmNscaleWidth			/* 291 */
    ,XmNscrolledWindowMarginHeight			/* 292 */
    ,XmNscrolledWindowMarginWidth			/* 293 */
    ,XmNselectInsensitivePixmap			/* 294 */
    ,XmNshellUnitType			/* 295 */
    ,XmNshowAsDefault			/* 296 */
    ,XmNshowValue			/* 297 */
    ,XmNmenuBar			/* 298 */
    ,XmNcommand			/* 299 */
    ,XmNcommandWindow			/* 300 */
    ,XmNtitleString			/* 301 */
    ,NULL			/* 302 */
    ,XmNmwmFunctions			/* 303 */
    ,XmNmwmDecorations			/* 304 */
    ,XmNmwmInputMode			/* 305 */
    ,XmNancestorSensitive			/* 306 */
    ,XmNentryCallback			/* 307 */
    ,XmNhistoryMaxItems			/* 308 */
    ,XmNrecomputeSize			/* 309 */
    ,XmNarmColor			/* 310 */
    ,XmNautomaticSelection			/* 311 */
    ,XmNselectColor			/* 312 */
    ,XmNshowSeparator			/* 313 */
    ,XmNwhichButton			/* 314 */
    ,XmNtextAccelerators			/* 315 */
    ,XmNlistLabelString			/* 316 */
    ,XmNminimizeButtons			/* 317 */
    ,XmNnoResize			/* 318 */
    ,XmNtextString			/* 319 */
    ,XtNinsertPosition			/* 320 */
    ,XmNaccelerators			/* 321 */
    ,XmNcolormap			/* 322 */
    ,XmNdepth			/* 323 */
    ,XmNscreen			/* 324 */
  };
